### ISSUE TITLE
Missing 'error message' in SSH_FXP_STATUS causing 'index out of range' panic

### ISSUE THREAD

**Issue by akupas** [pkg/sftp#110]
The SSH-2.0-Cisco-2.0 server implementation does not return the SSH_FXP_STATUS 'error message' in response to a ReadDir packet causing an "index out of range" panic. The sftp unix utility gracefully handles this case. I propose that the 'error message' is made optional in unmarshalStatus to handle this case.

**Comment by davecheney** [comment]
Can you please include the panic message.

**Comment by akupas** [comment]
goroutine 1 [running]:
panic(0xc4b2e0, 0xc82000a140)
	go/gc/src/runtime/panic.go:478 +0x3cb
src/github.com/pkg/sftp/sftp.unmarshalStatus(0xc800000004, 0xc8204ce125, 0x0, 0x0, 0x0, 0x0)
	src/github.com/pkg/sftp/client.go:1167 +0x5d9
src/github.com/pkg/sftp/sftp.(*Client).close(0xc8204ba0f0, 0xc82040f444, 0x4, 0x0, 0x0)
	src/github.com/pkg/sftp/client.go:468 +0x169
panic(0xc4b2e0, 0xc82000a140)
	go/gc/src/runtime/panic.go:443 +0x4f2
src/github.com/pkg/sftp/sftp.unmarshalStatus(0xc800000003, 0xc82040fec5, 0x0, 0x0, 0x0, 0x0)
	src/github.com/pkg/sftp/client.go:1167 +0x5d9
src/github.com/pkg/sftp/sftp.(*Client).ReadDir(0xc8204ba0f0, 0xd9b1d0, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0)
	src/github.com/pkg/sftp/client.go:226 +0x353
main.New(0xc820332000, 0xc8202a9a40, 0x0, 0x0)
	ssh.go:122 +0x8a3
main.main()
	ssh.go:217 +0x26b

panic: runtime error: index out of range
	panic: runtime error: index out of range

goroutine 1 [running]:
panic(0xc4b2e0, 0xc82000a140)
	go/gc/src/runtime/panic.go:483 +0x3ef
src/github.com/pkg/sftp/sftp.unmarshalStatus(0xc800000004, 0xc8204ce125, 0x0, 0x0, 0x0, 0x0)
	src/github.com/pkg/sftp/client.go:1167 +0x5d9
src/github.com/pkg/sftp/sftp.(*Client).close(0xc8204ba0f0, 0xc82040f444, 0x4, 0x0, 0x0)
	src/github.com/pkg/sftp/client.go:468 +0x169
panic(0xc4b2e0, 0xc82000a140)
	go/gc/src/runtime/panic.go:443 +0x4f2
src/github.com/pkg/sftp/sftp.unmarshalStatus(0xc800000003, 0xc82040fec5, 0x0, 0x0, 0x0, 0x0)
	src/github.com/pkg/sftp/client.go:1167 +0x5d9
src/github.com/pkg/sftp/sftp.(*Client).ReadDir(0xc8204ba0f0, 0xd9b1d0, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0)
	src/github.com/pkg/sftp/client.go:226 +0x353
main.New(0xc820332000, 0xc8202a9a40, 0x0, 0x0)
	ssh.go:122 +0x8a3
main.main()
	ssh.go:217 +0x26b
