### ISSUE TITLE
Cannot compile package with gccgo

### ISSUE THREAD

**Issue by timkrumenacker** [pkg/sftp#121]
I am trying to compile hugo, getting this:
```
github.com/pkg/sftp
# github.com/pkg/sftp

code/go/src/github.com/pkg/sftp/server_statvfs_linux.go:17:35: error: reference to undefined field or method ‘X__val’
   Fsid:    uint64(uint64(stat.Fsid.X__val[1])<<32 | uint64(stat.Fsid.X__val[0])), // endianness?
                                   ^
code/go/src/github.com/pkg/sftp/server_statvfs_linux.go:17:69: error: reference to undefined field or method ‘X__val’
   Fsid:    uint64(uint64(stat.Fsid.X__val[1])<<32 | uint64(stat.Fsid.X__val[0])), // endianness?
```

**Comment by davecheney** [comment]
Thank you for your error report, can you please provide some more details.

Which version of gccgo are you using? Which operating system are you using? Which cpu are you using?

**Comment by timkrumenacker** [comment]
Excuse me, - of course.

gccgo: gccgo (GCC) 6.1.1 20160602
OS: arch linux
CPU: Intel Core i7-4712MQ

**Comment by davecheney** [comment]
@timkrumenacker have a look at #122. I don't have a working gccgo install atm so this is done by feel, but hopefully it should get you compiling again.

**Comment by minusnine** [comment]
I think the above change is not exactly correct. It causes both server_statvfs_impl.go and server_statvfs_stubs.go to be compiled in Linux under gccgo.

I'm not an expert, but I think the build directive on server_statvfs_impl.go should be:

// +build darwin linux,!gccgo

(I also don't have a gccgo installation at the ready for creating a pull request, but I've verified that the above change does work with the convoluted internal gccgo installation I have available).

**Comment by minusnine** [comment]
To be clearer, here are the build directives for all three files that work for me in both gc and gccgo on Linux:

$ head -1 server_statvfs_{impl,linux,stubs}.go
==> server_statvfs_impl.go <==
// +build darwin linux,!gccgo

==> server_statvfs_linux.go <==
// +build !gccgo,linux

==> server_statvfs_stubs.go <==
// +build !darwin,!linux gccgo

**Comment by davecheney** [comment]
Could you please send a PR. I don't have a working gccgo installation to
test on at the moment.
