### ISSUE TITLE
Panic on file close

### ISSUE THREAD

**Issue by purpleidea** [pkg/sftp#134]
I was able to cause this panic:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x6baef4]

goroutine 174 [running]:
github.com/pkg/sftp.(*File).Close(0x0, 0x0, 0x0)
    /home/james/code/gopath/src/github.com/pkg/sftp/client.go:638 +0x24
```

The line in question is:
`
    return f.c.close(f.handle)
`
https://github.com/pkg/sftp/blob/master/client.go#L638

and it seems in this case f.c was nil. woops!
I'm sure this was my fault for having a race in my code, but the panic actually happened in the library, not in my code, so perhaps there should be a lock around this check so that the close is always a safe operation?

If you agree, I'm happy to write this patch.

**Comment by davecheney** [comment]
Thanks for confirming. This sounds like you forgot to check an error, and
used a nil value by accident.

**Comment by purpleidea** [comment]
@davecheney Sorry I didn't understand your comment... Isn't it possible this is a library bug? (Although one that is only triggered by less than ideal circumstances on my part.)

**Comment by davecheney** [comment]
The general practice in Go is to no protect against being called on a nil
receiver in the general case. It sounds like the problem you hit was you
ended up with a nil *sftp.File, possibly by mistake. Can you show some code
that triggered the problem?

**Comment by purpleidea** [comment]
On Tue, Aug 30, 2016 at 4:09 AM, Dave Cheney <notifications@github.com>
wrote:

> The general practice in Go is to no protect against being called on a nil
> receiver in the general case. It sounds like the problem you hit was you
> ended up with a nil *sftp.File, possibly by mistake. Can you show some code
> that triggered the problem?
>


If that's the convention, then so be it. Again it was definitely my fault.
I just figured close() would "noop" if there was nothing to close. Does the
stdlib behave the same way? (I should read that part...)

Cheers!

PS: Happy to show you code, but it's a bit of a mess... WIP
https://github.com/purpleidea/mgmt/tree/feat/remote
