### ISSUE TITLE
SSH_FX_FAILURE for removing (some) directories

### ISSUE THREAD

**Issue by SommerEngineering** [pkg/sftp#137]
Like #35, I get for some directories I would like to remove, an `SSH_FX_FAILURE` error. I updated your package's Go code yesterday. Therefore, I should have the fix of #35. What can I do in order to analyse this issue?

At the moment, all directories with this error uses UTF8 characters, e.g. umlauts like ö, ü, ä, etc.

As I am writing this, I got an idea: I switched from Windows 10 to Mac OS X, thus, my Go program runs now under Mac. I recognised yesterday, that the same Go code handles such file names with umlauts differently (Windows vs Mac). Or, at least, both operating systems deliver different strings to Go and therefore to this library. Because: All remote directories, which I cannot delete right now (`SSH_FX_FAILURE`) are created from the Go program under Windows 10 and cannot deleted from within Mac OS.

Perhaps, this post helps some other users/developers. I will investigate this issue further and can close this issue later, if I had a solution. Thanks.

**Comment by eikenb** [comment]
I'm not sure I understand your issue completely. Is it an issue with it not recognizing the directory and something making RemoveDirectory public as discussed in #146 would work? Or is this more an OS filename consistency issue?

If you have any more on this please add a note, particularly if RemoveDirectory would fix it or if you have a code sample that would allow me to reproduce it (best if it didn't require multiple platforms). If not I don't think there is any way to address your issue.

Thanks.

**Comment by ncw** [comment]
If it is umlauts Mac vs Windows, then you are almost certainly having a problem with Unicode normalization on OS X.

OS X stores its non ASCII filenames in a weird un-normalised format which will be different to the format writen by Windows (which uses normalized UTF-8 like you would expect).

Some of the gory details here...

https://developer.apple.com/legacy/library/technotes/tn/tn1150.html

(I've had a lot of problems with this in rclone, eg [#194](https://github.com/ncw/rclone/issues/194))

**Comment by SommerEngineering** [comment]
Thanks for your response. I have investigated this issue some time now. Best example was a week ago: I tried to delete > 60,000 directories and each had an umlaut. On the first run, none of these directories could be deleted. With each additional run, a random amount of the queued directories gets deleted. After approx. six runs no directory was left.

Therefore, my conclusion is: The issue gets caused by the remote SFTP server and is not triggered by the Go code. Unfortunately, the remote server gets managed by an external company. Thus, I cannot change nor investigate their configuration...

**Comment by eikenb** [comment]
@SommerEngineering Thank you for following up and Closing the ticket.

**Comment by mojocn** [comment]
> Like #35, I get for some directories I would like to remove, an `SSH_FX_FAILURE` error. I updated your package's Go code yesterday. Therefore, I should have the fix of #35. What can I do in order to analyse this issue?
> 
> At the moment, all directories with this error uses UTF8 characters, e.g. umlauts like ö, ü, ä, etc.
> 
> As I am writing this, I got an idea: I switched from Windows 10 to Mac OS X, thus, my Go program runs now under Mac. I recognised yesterday, that the same Go code handles such file names with umlauts differently (Windows vs Mac). Or, at least, both operating systems deliver different strings to Go and therefore to this library. Because: All remote directories, which I cannot delete right now (`SSH_FX_FAILURE`) are created from the Go program under Windows 10 and cannot deleted from within Mac OS.
> 
> Perhaps, this post helps some other users/developers. I will investigate this issue further and can close this issue later, if I had a solution. Thanks.

i have got the same problem with my Windows10 PC,
