### ISSUE TITLE
Doesn't compile on linux/s390x

### ISSUE THREAD

**Issue by mundaym** [pkg/sftp#141]
Seems to be a similar problem to https://github.com/pkg/sftp/issues/121.

The problem is that the `X__val` member of `syscall.Fsid` is not exported on s390x. I've created an issue for this in go (https://github.com/golang/go/issues/17298), but technically the syscall package is frozen, deprecated and marked dragons-be-here...

The line which doesn't compile is: https://github.com/pkg/sftp/blob/8197a2e580736b78d704be0fc47b2324c0591a32/server_statvfs_linux.go#L19.

Would it be possible to do one of the following:

1. delete the line of code,
2. use the `unix` package instead of the `syscall` package (which I can then fix),
3. or add a gccgo-like exception for s390x?

Thanks!

**Comment by davecheney** [comment]
Closed by #142

**Comment by mundaym** [comment]
Thanks a lot Dave. stftp compiles and runs on s390x now :+1:
