### ISSUE TITLE
ReadFrom() deadlock

### ISSUE THREAD

**Issue by nekrondev** [pkg/sftp#145]
File: client.go, conn.go
References to #55 and #63 

Checking the commited fix for issue #55 today I found out that the ReadFrom() deadlock is still existing. I digged a bit deeper and found the problem.

At the beginning of ReadFrom() function the ch channel is buffered with capacity of 1 result struct object. This was the fix introduced with #63. 

``` go
func (f *File) ReadFrom(r io.Reader) (int64, error) {
    // ...
    offset := f.offset
    ch := make(chan result, 1) // this was fixed with #63, making the channel non-blocking
    // ...
```

Then data is read and packed into sshFxpWritePacket struct and dispatched by calling dispatchRequest().

``` go
       // ...
    for inFlight > 0 || firstErr == nil {
        for inFlight < desiredInFlight && firstErr == nil {
            n, err := r.Read(b)
            if err != nil {
                firstErr = err
            }
            f.c.dispatchRequest(ch, sshFxpWritePacket{
                ID:     f.c.nextID(),
                Handle: f.handle,
                Offset: offset,
                Length: uint32(n),
                Data:   b[:n],
            })
            inFlight++
                       //...
```

dispatchRequest() will send the packet data and returns to ReadFrom() for waiting on a result channel value. In case an error occures dispatchRequest() will return an error result to channel ch.

``` go
func (c *clientConn) dispatchRequest(ch chan<- result, p idmarshaler) {
    c.Lock()
    c.inflight[p.id()] = ch
    if err := c.conn.sendPacket(p); err != nil {
        delete(c.inflight, p.id())
        ch <- result{err: err} 
    }
    c.Unlock()
}
```

Back to ReadFrom() the function waits for a result on channel ch by using a blocking select.

``` go
select {
        case res := <-ch:
            inFlight--
            if res.err != nil {
                firstErr = res.err
                break
            }
            switch res.typ {
            case ssh_FXP_STATUS:
                id, _ := unmarshalUint32(res.data)
                err := normaliseError(unmarshalStatus(id, res.data))
                if err != nil && firstErr == nil {
                    firstErr = err
                    break
                }
                if desiredInFlight < maxConcurrentRequests {
                    desiredInFlight++
                }
```

In case there was no tx error inFlight is decreased (back to 0), but on the other hand desiredInFlight increased once per loop until maxConcurrentRequests are reached (which are by default 64).

As long as no error occures or EOF is reached, the outer for-loop (for inflight > 0 || firstErr == nil) continues. The inner for-loop however will now call dispatchRequest() with the previously assigned ch channel as long as inFlight < desiredInFlight.

Lets think about that you have a wonky SSH connection, but a few megabytes had already been transferred so that desiredInFlight var has reached the maximum of 64 concurrent requests. Suddenly the remote devices connection drops, i.e. dispatchRequest() queues an error result to ch, but the inner for-loop has not yet reached desiredInFlight count. The next dispatchRequest() call will also result in an error. 

Now the bad thing that will happen here is since ch was made with size one the second dispatchRequest() error handling ch <- result{} assignment will block dispatchRequest call (ch is already allocated with the first error from the previous loop) and therefor deadlock ReadFrom() since the select{} where the channel is read will never be reached.

**Comment by eikenb** [comment]
I read through this and get the basic problem but it would take a good bit of work for me to get up to speed on the client code enough to have an idea of how to address this. Given that currently my focus is almost entirely on the server side code, this may not happen. I would however have time to review a pull request. So if you have an idea of how to fix things perhaps you would consider submitting a pull request with the fix + test. I don't mean to be dismissive of your issue, rather just honest about my time and what your best chances are of getting this fixed.

Thanks.

**Comment by eikenb** [comment]
This looks very much like the hang in WriteTo fixed in PR #152. I'm thinking it might be exactly the same. I'm going to look to see if the same fix would work here.

**Comment by nekrondev** [comment]
Thanks for your support! I am currently buried into different projects so there is little time for me right now to write test cases to probe the deadlock bug. For the tool where I used to transfer data to unreliable mobile WLAN connections the deadlock did not reappear after I fixed the sftp package like mentioned earlier.

Cheers and keep on the good work!
Nek

**Comment by eikenb** [comment]
I was reviewing the code and I think all that this would take to trigger would be 1 successfully received packet followed by 2 errors. After 1 packet inFlight would be 0 (one added, one remove) and desiredInFlight would be 2 (started at 1, incremented once). So then if it received 2 errors in a row, they would both hit the immediate channel write in dispatchRequest causing the 2nd to lock.

I'm trying to figure out a way to write a test for this right now. I have yet to find a good place to force it to start returning errors after N packets are sent. I'm thinking maybe I could change things so I could replace packet.sendPacket() with a version of it that fails after N.

**Comment by eikenb** [comment]
I replicated it! :)

**Comment by eikenb** [comment]
Note that this also effects client.Write() as well.
