### ISSUE TITLE
Some SFTP appliances return file does not exist for directories during a Remove

### ISSUE THREAD

**Issue by crazed** [pkg/sftp#146]
Similar to #62,  non-compliant servers return unexpected results when you try to call Remove on a directory. Maybe it is best to expose RemoveDirectory, as I bet there's endless servers out there doing all kinds of weird things. The specific server I'm dealing with winds up with error:

"file does not exist"

I did not have time to track down which specific server this is, or what packet that error correlates with, but I do know with the standard openssh client an rmdir works fine, but an rm fails with the same response.

**Comment by eikenb** [comment]
After reading through #62 and #35 I agree that the best solution would probably be to make RemoveDirectory public. Parity with go's os package is nice, but given the non-compliance of some servers out there having a way to work around it when they aren't in compliance would be better than trying to fix each one. At least at this stage in the project.

I'll leave the comment open for a time to allow for others to chime in before moving forward with the change.

**Comment by eikenb** [comment]
I see you already did a PR for this, #147. Thanks.

**Comment by eikenb** [comment]
Merged #147, so this is fixed.
