### ISSUE TITLE
Connection Hang at File upload to Windows SFTP server

### ISSUE THREAD

**Issue by udayskyport** [pkg/sftp#149]
Hi Team,
I am trying to upload an 30GB file to Windows sftp server using golang sftp client.
The connection hangs after 6-7gigs. However, the same file upload happens smoothly using the linux sftp client.
Any help/advise regarding this might be helpful for me

**Comment by davecheney** [comment]
Can you please post some code that reproduced the issue. Thank you.

**Comment by eikenb** [comment]
I'm helping maintain the project now and would like to ask again for a example to replicate the issue before closing. Thanks.

**Comment by eikenb** [comment]
I believe this is probably a case of hitting one of the deadlocks reported in #145 or #152. These deadlocks affected Write, ReadFrom, Read and WriteTo. They are all fixed now and with no more feedback on reproducing it, I'm closing.
