### ISSUE TITLE
Slow downloads compared to FileZilla

### ISSUE THREAD

**Issue by vanbroup** [pkg/sftp#15]
I noticed some serious difference when comparing the download speed via this package with the same download via FileZilla.

When downloading with Filezilla I can download at 30Mpbs+ with 10 concurrent files (over a VPN), but when downloading with the GO program directly on a high speed internet connection I can't get above the 20Mpbs with 16 concurrent downloads (or about 10 with 10 concurrent).

_The readme already lists that currently all traffic with the server is serialized and I can imagine that this is influencing the download performance. But maybe also other factors as packet size and or compression can play a role here._

The code that is facilitating the download:
```
log.Printf("[%s] Starting to download", f)

// check if file already exists
if _, err := os.Stat(file); !os.IsNotExist(err) {
	log.Printf("[%s] Already downloaded", f)
	return
}

// open local file to save download
out, err := os.Create(file)
if err != nil {
	log.Printf("[%s] Error (%s)", f, err.Error())
	return
}
defer out.Close()

// open file to download
dl, err := s.Open(f)
if err != nil {
	log.Fatal(err)
}
defer dl.Close()

// copy the bytes
nb, err := io.Copy(out, dl)
if err != nil {
	log.Println("error downloading file", err)

	// delete
	err = os.Remove(file)
	if err != nil {
		log.Println("error deleting file after download error", err)
	}
	return
}

log.Printf("[%s] Download completed (%d bytes)", f, nb)
```

**Comment by davecheney** [comment]
I believe this was addressed in #41
