### ISSUE TITLE
Hanging occurs when opening multi-connection download

### ISSUE THREAD

**Issue by zhaoyuxi** [pkg/sftp#150]
I create more than one sftp.NewClient to do the download. One or two seconds later all connections hang up. And no data to be downloaded. 

If there is one connection, all is ok.

The 'WriteTo' or 'Copy' has no response forever:
nSize, err := rFile.WriteTo(wFile)
//nSize, err := io.Copy(wFile, rFile)

**Comment by eikenb** [comment]
Could you provide a minimal, self-contained example to reproduce the issue?

**Comment by zhaoyuxi** [comment]
@eikenb Creating multi clients instances by calling sftp.NewClient. Then dispatch different downloading files to each intance in load balance. Run a moment then hang up. If just creating one client instance, no problem.
