### ISSUE TITLE
request-example prevents code from compiling on windows

### ISSUE THREAD

**Issue by lespea** [pkg/sftp#157]
Updated the package with glide and now compiling throws an error:

`vendor\github.com\pkg\sftp\request-example.go:190: undefined: syscall.Stat_t`

**Comment by lespea** [comment]
If I delete the offending file out of vendor everything compiles fine

**Comment by saurabhnitte** [comment]
I am facing the same issue.

Updated the package with "go get -u ", go compiler throws an error:

 # github.com/pkg/sftp
..\github.com\pkg\sftp\request-example.go:190: undefined: syscall.Stat_t

**Comment by eikenb** [comment]
Sorry for the issue. I'll look at this ASAP. But in general Windows support will lag behind until we have a solution for automated testing. Travis doesn't support Windows builds yet and I don't have access to windows. I will try to be more cognizant of OS dependent things though.
