### ISSUE TITLE
proposal: add / remove build targets

### ISSUE THREAD

**Issue by kardianos** [pkg/sftp#161]
Travis CI is currently testing back to go1.5.

Now that go1.8 is out, perhaps add go1.8 and keep go1.7 and tip.

If #160 is merged, add a windows CI?

**Comment by eikenb** [comment]
I was going to advance the travis test versions (dropping 1.5, adding 1.8). Dave had it checking going back to 1.4 and I think it better not to restrict to much to recent versions. A 3 version window (plus tip) I think seems reasonable. I was mainly just waiting a bit to give travis time to add go 1.8 support.

**Comment by kardianos** [comment]
SGTM

**Comment by davecheney** [comment]
SGTM. Anything less than 1.7 can be dropped

**Comment by eikenb** [comment]
I'll take Dave's lead then and standardize on current stable, previous stable and tip for the travis testing.

> If #160 is merged, add a windows CI?

I'm looking into #160 as improved windows support is something I'd like to see and it will help with a couple of outstanding tickets I'd like to see resolved. But we'll tackle that when we get to that point.
