### ISSUE TITLE
example sftp-server doesn't handle exit well (EOF)

### ISSUE THREAD

**Issue by dolanor** [pkg/sftp#169]
Hi,

running the example:
```
s/src/github.com/pkg/sftp/examples/sftp-server$ go run main.go 
Listening on [::]:2022
2017/03/02 11:47:17 sftp server completed with error:EOF
exit status 1
```
exits badly if sent an exit/bye/quit command in sftp client
```
$ sftp -P 2022  testuser@localhostThe authenticity of host 
testuser@localhost's password: 
Connected to localhost.
sftp> ls
README.md  id_rsa     main.go    
sftp> exit
Connection to localhost closed by remote host.
```
What is not handled well in that example?

**Comment by eikenb** [comment]
It exits as it should. The error is EOF, which is what server.Serve() returns when the client exists and it is finished handling the session. This is similar to file handles which also return EOF when they are done reading a file.

**Comment by eikenb** [comment]
The only possible bug here is that the example code doesn't special case the EOF error which server.Serve() returns when the client quits the session. It is supposed to return EOF to indicate the end of the session. The example code probably should make this more obvious. Maybe that is what you were asking for in the first place and I misunderstood.

**Comment by dolanor** [comment]
That was exactly that. You sir are an oracle to find my not well expressed thought!
Thank you very much!
