### ISSUE TITLE
get SSH connection information on each request

### ISSUE THREAD

**Issue by dolanor** [pkg/sftp#170]
Hi,

I'm using the current work from @eikenb in #130 , but I can't figure out how to get SSH connection information (like user, ssh fingerprint) from a request.
My use case is that my server is just a gateway to somewhere else, so I need to pass authentication information down the line.
Is there an easy way to do that?

If not, I was thinking that maybe enhancing the request server with some `context` would help pass whatever information we need.

**Comment by eikenb** [comment]
The auth info is in the data passed to the callbacks passed to the ssh.ServerConfig{}. The callbacks get passed a [ConnMetadata](https://godoc.org/golang.org/x/crypto/ssh#ConnMetadata) object with some of the data you need while the rest (such as the password or pubkey) are passed as a separate argument. Here's some snippets from another project I'm working on that uses PAM based auth (w/ github.com/msteinert/pam)...

`	
	config := &ssh.ServerConfig{
		PasswordCallback:  sshLogin,
	}

func sshLogin(c ssh.ConnMetadata, pass []byte) (*ssh.Permissions, error) {
	err := pamAuth(c.User(), string(pass))
	if err == nil {
		count("auth.pam")
		return nil, nil
	}
	log.Error("auth.pam", "error", err)
	return nil, fmt.Errorf("password rejected for %v", c.User())
}

func pamAuth(username, passwd string) error {
	t, err := pam.StartFunc(pam_service, username,
		func(s pam.Style, msg string) (string, error) {
			switch s {
			case pam.PromptEchoOff:
				return passwd, nil
			case pam.PromptEchoOn, pam.ErrorMsg, pam.TextInfo:
				return "", nil
			}
			return "", fmt.Errorf("Unknown PAM message: %v", s)
		})

	if err == nil {
		// this returns an error when auth fails
		err = t.Authenticate(0)
	}

	return err
}
`

**Comment by eikenb** [comment]
You'll obviously need to add something to get the data back out of those callback (eg. pass a callback into the callback). But I think that is about it.
