### ISSUE TITLE
AppEngine

### ISSUE THREAD

**Issue by MaVo159** [pkg/sftp#173]
Due to the use of the os and syscall package, it is currently not possible to use this package with the Google AppEngine standard environment. I looked at a couple of places and suspect that it may be possible to avoid these imports. You can also use appengine as conditional in build constraints, in to include and exclude particular files from the build only on AppEngine. Any chance of this getting fixed?

**Comment by eikenb** [comment]
I'll look at any pull request that attempts to address this, but it is not going to be a priority of mine anytime soon. Do you (or anyone else watching) want to take a stab at it?

**Comment by MaVo159** [comment]
I don't have the time to do this right now. Maybe in the future (depends how much we'll depend on the sftp package in future projects).

**Comment by eikenb** [comment]
With nobody planning on working on this idea anytime soon I'm just going to close it.

**Comment by rboyc** [comment]
Any plans to re-open this issue?

Unknowingly, I tried to use it under appEngine and received the following error:

`go-app-builder: Failed parsing input: parser: bad import "syscall" in github.com\pkg\sftp\attrs.go from GOPATH`

**Comment by eikenb** [comment]
I have no plans to work on eliminating the syscall uses in the near future. I'm planning on reworking the filesystem based server in server.go into a backend for the request server. If that is factored out into a sub-package then I think it might be possible to eliminate syscall from the rest of the code, but that is a ways off.
