### ISSUE TITLE
winscp stat issue on request

### ISSUE THREAD

**Issue by purha** [pkg/sftp#178]
I get weird behavior on when winscp runs stat command before downloading a file,

here's log output:

```
DEBU[0161] 3 fileinfo Method=Stat, Filepath=/jepa, Attrs=[], Target=, translated path: admin/jepa 
DEBU[0161] getfile: jepa                                
DEBU[0161] getFile returned jepa size=0 isdir=true modtime=2017-04-20 06:46:32.739372035 +0200 CEST mode=drwxr-xr-x sys=&{0 0 0 2147484141 65534 65534 0 0 0 0 0 {0 0} {0 0} {0 0} [0 0 0]} 
2017/04/20 06:46:32 incoming id: 32775
2017/04/20 06:46:32 break! -- outgoing: 0; incoming: 1
2017/04/20 06:46:32 outgoing pkt: 32775
2017/04/20 06:46:32 break! -- outgoing: 0; incoming: 0
2017/04/20 06:46:32 incoming id: 33027
2017/04/20 06:46:32 break! -- outgoing: 0; incoming: 1
2017/04/20 06:46:32 outgoing pkt: 33027
2017/04/20 06:46:32 break! -- outgoing: 0; incoming: 0
DEBU[0162] 3 fileinfo Method=Stat, Filepath=/jepa/test.jpg, Attrs=[], Target=, translated path: admin/jepa/test.jpg 
DEBU[0162] getfile: jepa/test.jpg 
DEBU[0162] getFile returned jepa/test.jpg size=151303 isdir=false modtime=2017-03-07 20:20:24.652 +0000 UTC mode=-rw-r--r-- sys=&{0 0 0 420 65534 65534 0 0 151303 0 0 {0 0} {0 0} {0 0} [0 0 0]} 
2017/04/20 06:46:32 incoming id: 33288
2017/04/20 06:46:32 break! -- outgoing: 0; incoming: 1
2017/04/20 06:46:32 outgoing pkt: 33027
----- client keeps waiting here ----                   
INFO[0201] sftp client exited session. 
```

code is pretty similar from request example:

```
func (f *FSX) Fileinfo(r sftp.Request) ([]os.FileInfo, error) {
	key := f.customer.GetPath(r.Filepath)
	name := strings.Trim(r.Filepath, "/")

	log.Debugf("%v fileinfo Method=%v, Filepath=%v, Attrs=%v, Target=%v, translated path: %v",
		f.number, r.Method, r.Filepath, r.Attrs, r.Target, key)

	f.filesLock.Lock()
	defer f.filesLock.Unlock()

	switch r.Method {
	case "List":
		return f.listPath(r.Filepath), nil
	case "Stat":
		// get file from the list of items
		file, err := f.getFile(name)
		if err != nil {
			log.Errorf("getFile %v error: %v", name, err)
			return nil, err
		}

		defer log.Debugf("getFile returned %v size=%v isdir=%v modtime=%v mode=%v sys=%v",
			file.name, file.Size(), file.IsDir(), file.ModTime(), file.Mode(), file.Sys())

		return []os.FileInfo{file}, nil
	}

	return nil, fmt.Errorf("not implemented")
} 
```

for me it looks like it's resending some old packet (based on id).

This is latest master with golang 1.8.

I'll try to check this further, but I'm not familiar with the code yet

**Comment by eikenb** [comment]
I may have just fixed this. I just today realized that I hadn't updated the request-server to use the latest packet ordering code. I meant to do this before merging but forgot. I just pushed the updates today. Could you please test to see if you still get this error. Thanks.

**Comment by purha** [comment]
Unfortunately the problem still exists with the latest master (63cbed8), the last packet which gets the client stuck has the same id as one of the previous

```
2017/04/24 09:16:59 incoming id: 77315
2017/04/24 09:16:59 break! -- outgoing: 0; incoming: 1
2017/04/24 09:16:59 outgoing pkt: 77315
2017/04/24 09:16:59 break! -- outgoing: 0; incoming: 0
2017/04/24 09:16:59 incoming id: 77576
2017/04/24 09:16:59 break! -- outgoing: 0; incoming: 1
DEBU[0135] 3 fileinfo Method=Stat, Filepath=/FileZilla_3.24.0_win64-setup.exe, Attrs=[], Target=, translated path: admin/FileZilla_3.24.0_win64-setup.exe 
DEBU[0135] getfile: FileZilla_3.24.0_win64-setup.exe    
DEBU[0135] getFile returned FileZilla_3.24.0_win64-setup.exe size=6975096 isdir=false modtime=2017-04-10 12:14:27 +0000 UTC mode=-rw-r--r-- sys=&{0 0 0 420 65534 65534 0 0 6975096 0 0 {0 0} {0 0} {0 0} [0 0 0]} 
2017/04/24 09:16:59 outgoing pkt: 77315
```
I dont experience this with other clients, but winscp seems to send the stat packet which the others dont send

**Comment by eikenb** [comment]
It looks like this is a bug in the way it handles the FSTAT packet. I was able to recreate the issue with winscp (via wine) and then recreate it just using our own sftp.Client.  Calls using FSTAT, which acts on an open file handle, hang while STAT and LSTAT, which both just take a path, work fine.

**Comment by eikenb** [comment]
I added a test case for fstat and have fixed the issue. I implemented it by grabbing the file info from the handle and converting the call into a standard Stat call (at least as far as the Fileinfo handler is concerned). I implemented it this way as it was the most straightforward way to keep the handler requirements the same.

It is implemented in the issue178 branch I just pushed up to github so I you could take a look at and to make sure travis liked it as well as my local testing.

**Comment by eikenb** [comment]
I included some additional fixes for (f)setstat in that branch, but it should still fix your issue.

**Comment by purha** [comment]
issue178 indeed seems to fix the issue, thank you!

**Comment by eikenb** [comment]
I've merged the branch with the fix. Master should work for you now. Thanks for the report and feedback.
