### ISSUE TITLE
Get username inside Fileread(r sftp.Request)

### ISSUE THREAD

**Issue by fmpwizard** [pkg/sftp#182]
I'm using the new request style server and when inside the FileRead/Write, etc I would need to access the current username, so I can limit what each user can see. (So user A only sees their files, etc)

Thanks

**Comment by fmpwizard** [comment]
If anyone gets here, the solution I'm going with is this:
The example request server has a line like:

    _, chans, reqs, err := ssh.NewServerConn(nConn, config)

but the variable we are omitting there is the serverConn that has access to the underlaying session, which has the `User()` method, it also has things like SessionID, etc

    srvConnWithMeta, chans, reqs, err := ssh.NewServerConn(nConn, config)

a few lines later I pass this username to the handler that inits the inMemoryFS (I renamed mine)

    root := fsHandler(srvConnWithMeta.User())

and updated code to:

```
func fsHandler(username string) sftp.Handlers {
	root := &root{
		files:    make(map[string]*memFile),
		username: username,
	}
	root.memFile = newMemFile("/", true)
	return sftp.Handlers{
		FileCmd:  root,
		FileGet:  root,
		FileInfo: root,
		FilePut:  root,
	}
}
```

**Comment by eikenb** [comment]
@fmpwizard Would a good solution to this be changing the ssh connection example to this...

	sconn, chans, reqs, err := ssh.NewServerConn(nConn, config)
	if err != nil {
		log.Fatal("failed to handshake", err)
	}
	log.Println("login detected:", sconn.User())
	fmt.Fprintf(debugStream, "SSH server established\n")

That is, instead of ignoring the return we accept it and log the username as a way to indicate the availability of data on that ssh connection object?

**Comment by fmpwizard** [comment]
yes, updating the example to that would be great!
