### ISSUE TITLE
failed to send packet header: EOF on file with size >= 300 KB

### ISSUE THREAD

**Issue by vvsh** [pkg/sftp#185]
Hi All,

I am trying to upload local files to SFTP.

     
`   client = openSSHConnection(config)
    ftpClient, err := sftp.NewClient(client, sftp.MaxPacket(10240000))
    if err != nil {
        log.Fatal(err)
    }
    defer ftpClient.Close()

    for _, jar := range newJars {
        w, err := ftpClient.Create(config["directory"] + "/" + jar.Name)
        if err != nil {
            log.Println("create error: ", jar.Name)
            log.Fatal(err)
        }
        defer w.Close()

        f, err := os.Open(jar.Path)
        if err != nil {
            log.Fatal(err)
        }
        defer f.Close()

        _, uploadError := io.Copy(w, f)
        if uploadError != nil {
            log.Println("copy error: ", jar.Name)
            log.Fatal(uploadError)
        }

        log.Print(jar.Name + " uploaded")
    }

    func openSSHConnection(config map[string]string) *ssh.Client {
    hostname := config["host"]
    port := config["port"]

    sshConfig := &ssh.ClientConfig{
        User: config["user"],
        Auth: []ssh.AuthMethod{
            ssh.Password(config["password"]),
        },
        HostKeyCallback: func(hostname string, remote net.Addr, key ssh.PublicKey) error {
            return nil
        },
        Timeout: time.Duration(90) * time.Second,
    }

    connection, err := ssh.Dial("tcp", hostname+":"+port, sshConfig)
    if err != nil {
        log.Fatal("Failed to dial: ", err.Error())
    }
    return connection
}`

But if a file is larger than ~ 300 KB it does not upload.

I receive the following in the log:

2017/07/13 18:46:07 create error 123.jar
2017/07/13 18:46:07 failed to send packet header: EOF

and file size is 0 on the server.

What am I doing wrong?

Thanks,
Uladzimir

**Comment by eikenb** [comment]
What server are you uploading to? Openssh's sftp server?

**Comment by eikenb** [comment]
@vvsh  What server are you uploading to? Openssh's sftp server?

**Comment by vvsh** [comment]
@eikenb, OpenSSH_6.6.1p1, OpenSSL 1.0.1e-fips 11 Feb 2013

**Comment by eikenb** [comment]
I cannot reproduce any issue like you describe. I can upload anywhere from empty files to multi-gigabyte files.

The error is happening when you are calling client.Create() and it is returning an EOF when trying to write to the io.Writer() that is the one returned by the ssh libs Session.StdinPipe() [1].

You might want to double check your ssh setup. Test with some other actions or something. As far as I can tell this looks like it must be a problem in your code or on your test setup.

[1] https://godoc.org/golang.org/x/crypto/ssh#Session.StdinPipe

**Comment by eikenb** [comment]
I was able to reproduce it. On my first try I missed where you were setting the max packet size for you client.

> ftpClient, err := sftp.NewClient(client, sftp.MaxPacket(10240000))

When I added that setting I was able to reproduce the issue. I'm not sure why that is a problem. There might be an upper limit to what you can set the packet size to, I've found several undocumented 'standards' when working w/ sftp clients and servers.

After a bit of playing, the magic number where it starts producing that error for me is 262120. If I set the MaxPacket to that I get the EOF error, if I set it to 262119 I don't get the error.

So for now a temp fix is to just set your  MaxPacket size <= 262119.

**Comment by eikenb** [comment]
@vvsh Not sure if you get notified if I don't mention you and I forgot to in my last comment.  I was able to reproduce the issue and have a workaround, details in my previous comment.

**Comment by eikenb** [comment]
Looked in the openssh sftp-server code and found this...

	if (msg_len > SFTP_MAX_MSG_LENGTH) {
		error("bad message from %s local user %s",
		    client_addr, pw->pw_name);
		sftp_server_cleanup_exit(11);
	}

I checked my logs, and that exact error was getting logged when I triggered the problem. Looked up that value...

    #define SFTP_MAX_MSG_LENGTH	(256 * 1024)

That is 262144, and 262144 - 262120 = 24. That is probably the packet overhead.

So you hit the max value in openssh's implementation.

**Comment by vvsh** [comment]
@eikenb, thanks a lot, it helped!

Does it make sense to throw an error when packet size is too large?

**Comment by eikenb** [comment]
I'm definitely going to add a note to the MaxPacket's godoc comment. I think it should probably enforce a max maxpacket size. Returning an error if you try to set it > some amount.

Openssh's max accepted is 1<<18. According to the spec, the packet overhead should be 5bytes/40bits (a uint32  length field and a 1 byte type field), but there must be more to it than that as the overhead in this case is 24 or 25 bytes.  So maybe be generous and allow 1KB for overhead, and use (1<<18) - 1024 as a max-max packet size?
