### ISSUE TITLE
"internal inconsistency" documentation?

### ISSUE THREAD

**Issue by eldondevcg** [pkg/sftp#190]
We recently received an error about an "internal inconsistency" when using this package, but I didn't see any explanation in the documentation about it. Could someone point me in the right direction to understand what is going on here?
Thanks!

**Comment by eikenb** [comment]
This comes from WriteTo(). In client.WriteTo() it sends a bunch of requests to the server for data from the file referenced and counts these ongoing requests in the variable inFlight. These requests can be replied to out of order, and it saves the data from the out of order responses in a map pendingWrites[offset]data. This loop should normally keep going until the inFlight counter reaches 0 indicating completion.

For this error to happen inFlight must equal 0, no errors could of occurred, but... there are still pendingWrites waiting. If len(pendingWrites) > 0, inFlight SHOULD also be > 0. If not this error is raised.

I haven't found the chain of events that would trigger this yet. So if you have any more information on what you were doing when it happend or if you could even reproduce it I'd appreciate anything more you have.

Thanks.

**Comment by eikenb** [comment]
I added the documentation but will leave this open in hopes of more information. I still haven't figured out what series of events triggered the error and would like to understand in case it is a bug.

**Comment by eldondevcg** [comment]
Sorry I just realized that for some reason I didn't seem to receive an email notification about your response to this issue. We are only doing directory listing and file download with the program throwing this error. We have some instances where we are attempting to download a directory that contains cache files or log files, where it is likely that the file contents is changing mid-file-retrieval. I am not sure which server software is on the other end here, but I wouldn't be surprised if it is behaving badly. I think my primary question is, if we have a client performing multiple operations, is it safe to continue after this error with the same client to download subsequent files, or is the client in an unsafe state?

**Comment by eikenb** [comment]
@eldondevcg Thanks for the followup. I'll look into that and, once I figure it out, I'll add it to the documentation and let you know here.

**Comment by eikenb** [comment]
@eldondevcg Sorry for the incredibly long delay. But the client is still OK for use after receiving this error. All the bad state is local to the function/call and would not affect other calls with that client instance. I'm updating the doc for that error now.
