### ISSUE TITLE
sftp.ListerAt processing seems broken

### ISSUE THREAD

**Issue by mjgarton** [pkg/sftp#196]
When calling ListAt(), the returned count is not used to increment the value for the next offset. Instead MaxFilelist seems to always be used.  This breaks ListerAt implementations that chose not to (or are unable to) return MaxFilelist entries each time.

This seems to be broken since 733115c415560ff2068431f5e9a540e387694fc8

**Comment by eikenb** [comment]
I modeled ListAt() after ReadAt() is supposed to return an error if it returns fewer entries than the length of the slice passed in. As such, if this was followed, there would be no next call after it returns less than the set offset as it doesn't continue after an error. The documentation of the ListerAt interface closely follows the ReaderAt documentation in laying out this expectation.

The code doesn't actually check that the returned length (n) is the same the length of the slice, so what you say is possible. I looked at uses of ReadAt() in the standard lib to see what they did and I couldn't find one that checked this. They mostly just ignore the returned int (n).

Implementing your patch would make for a more forgiving API.. but at what cost. I'm not sure. Can anyone come up with a downside? I'm going to sleep on it and see if I can think of any reason not to merge this patch.

**Comment by mjgarton** [comment]
Thanks for the explanation. I _could_ make my implementation block until it has enough data to fill the entire slice, and in my implementation if would probably not have much or a downside, other than making the code more complex. In other cases, I wonder whether it might have a performance penalty.

Two thoughts come to mind
* Not allowing the implementation to return fewer than n entries effectively removes its ability to be in control of the page size, so it cannot use an optimal one even if it knows how to. We end up using always MaxFileList which is fairly arbitrary.
* While modeling after io.ReaderAt makes sense from a consistency point of view, I wonder why that design decision was made in the standard library (having to fill the buffer or return an error) and I believe it is to optimise for ease of use by the caller, rather than for ease of implementation in of ReadAt.  This is perhaps the right trade-off in the standard library, because for each io.ReaderAt implementation there are potentially many, many callers due to the generic nature and intent of the interface.
In our case though, there will always only be one caller of our Reader (i.e., this library) and many potential implementations. So it may make sense to add slight complexity here to make implementation easier for the many users of this library?

I'm going to try to think of other ways to allow the implementation to somehow control page size and keep implementation simple.  This may involve an API change though.

**Comment by eikenb** [comment]
Sorry I didn't get to this earlier, got deep into the race condition bug.

I'm leaning towards implementing your suggestions just because I haven't come up with any good reason not to. It would still work with the documented API for ListAt, but just be more flexible and handle cases like yours w/o just breaking silently (which is the main thing I don't like). The alternative would be adding a check and return an error in that case which seems less useful.

Oh, and BTW MaxFileList is a variable. So you can change it.
