### ISSUE TITLE
Proposal: (*File) ReadAt(b []byte, off int64) (n int, err error)

### ISSUE THREAD

**Issue by a-urth** [pkg/sftp#199]
I'm missing this particular interface for reading zip archives from sftp.
Its part of os.File implemented interfaces and seems like its doable, can judge only quickly running through the code.
Is there any reasoning why its impossible/not needed?

Also after searching through issues seems like its planned?

**Comment by eikenb** [comment]
Sorry for the long silence on this. Being a feature request for the client, I put it on the back burner and kind of forgot it was there.

> Is there any reasoning why its impossible/not needed?

I think it would be possible as it seems like the protocol would support it. 
Assuming it would work, there is no real reason for it not being there other than no one did it.

> Also after searching through issues seems like its planned?

I have no immediate plans to implement it and I'm currently the primary active developers. My focus is more on the server, more so than the client. I've been fixing bugs in the client, but hadn't given much thoughts to extending it. But I'm always open to pull requests, particularly for the client.

**Comment by qrpike** [comment]
This would be quite nice. ZIP package requires it to be able to decode the stream instead of having to download locally, then decode.

**Comment by mjgarton** [comment]
Isn't it possible just with a `Seek` followed by `Read`?  There are probably subtleties that I am overlooking.

**Comment by greatroar** [comment]
This has been fixed by #285, right?

**Comment by puellanivis** [comment]
:woman_facepalming: yes.
