### ISSUE TITLE
IETF file rather than filezilla?

### ISSUE THREAD

**Issue by puellanivis** [pkg/sftp#202]
By the source code, it seems that this library is based on the SFTP draft 04, but IETF has a draft up to 13, https://tools.ietf.org/id/draft-ietf-secsh-filexfer-13.txt

I’m not sure what has changed (a naïve diff shows a lot of changes, but it is a lot of formatting changes as well). But certainly, we should be using a superceding draft from the source that the spec specifically says the spec should be accessible from?

**Comment by eikenb** [comment]
The code targets https://tools.ietf.org/html/draft-ietf-secsh-filexfer-02, which is revision 3 of the protocol (revisions started counting at 1, filenames started counting at 0). This is the same revision implemented by the Openssh's server. It is generally considered the simplest version that is complete. I can't speak for everyone, but I have no plans to support anything past revision 3 if that's what you were asking. I'm not 100% as I can't quite parse that last sentence of yours.

**Comment by puellanivis** [comment]
“I have no plans to support anything past revision 3” answers the last question. (i.e. which reference/source should we be using?)

Should the reference in the godoc be fixed then still? It points to a filezilla address, and points to a revision 5…

**Comment by eikenb** [comment]
I'm sorry I misunderstood your original issue and thought you were asking if we would start supporting newer revisions. So are you talking about the reference to the spec [on line 2 of sftp.go](https://github.com/pkg/sftp/blob/master/sftp.go#L2)? That is the only filezilla reference I can find, but the copy of the spec at that URL is still revision 3, just formatted as text vs the ietf hosted one.

I'm not saying we shouldn't change that doc/comment to use the same URL as the all the others scattered about the code. I just wanted to be sure I was looking at the right thing.

**Comment by puellanivis** [comment]
Yes, that. I was curious about the newer revisions, but an answer of “like, no one supports them” is a good answer.

And yeah, now the only thing left is that the reference to the spec is on filezilla rather than an ietf link.
