### ISSUE TITLE
Creating sftp new client hangs the application 

### ISSUE THREAD

**Issue by ghengao** [pkg/sftp#203]
I wrote a application which can handle thousands of concurrent sftp connections to download some files form these sftp connections. However, a few times not a lot I noticed that my application is hanging during requesting a new client using sftp.NewClient. The error i got from the printout after 16 mimitues is EOF.  After some investigation, I think the root cause of this issue is because of the networking issues generated from the server which causing few hosts have verb bad connectivity.  However, I still want this piece of code to handle such exceptional cases. After looking into the sftp code, I suspect the hanging is generate from following procedure:

if err := sftp.sendInit(); err != nil {
		wr.Close()
		return nil, err
	}
	if err := sftp.recvVersion(); err != nil {
		wr.Close()
		return nil, err
	}

Can you guys help me to solve this issue?

Thanks a lot

**Comment by eikenb** [comment]
Sounds like you should add a timeout to the code around the NewClient() call.  Go has a fairly standard way of using channels for timeouts that might be useful. Here are a couple resources to get you started...

https://blog.golang.org/go-concurrency-patterns-timing-out-and
https://gobyexample.com/timeouts

**Comment by ghengao** [comment]
@eikenb , it is exactly what I did as a workaround. Basic i create a wrapper around NewClient():
`// NewSftpClient is a workaround to fix the issue of hanging when creating a sftp client on a bad connectivity towards the target host.
//
func NewSftpClient(sshConn *ssh.Client, timeout time.Duration) (sftpConn *sftp.Client, err error) {
	type ts struct {
		sf  *sftp.Client
		err error
	}
	tsChan := make(chan ts, 1)
	to := time.After(timeout)
	go func(s *ssh.Client, tsChan chan ts) {
		sf, err := sftp.NewClient(s)
		tsChan <- ts{
			sf:  sf,
			err: err,
		}
	}(sshConn, tsChan)
	select {
	case <-to:
		go func(tsChan chan ts) {
			defer close(tsChan)
			<-tsChan
		}(tsChan)
		return nil, fmt.Errorf("timeout creating sftp session")
	case t := <-tsChan:
		close(tsChan)
		return t.sf, t.err
	}
}`

Now, the application can exit correctly. However the problem with this approach is that the this goroutine will leak if sftp.NewClient(s) never returns.  
`
go func(s *ssh.Client, tsChan chan ts) {
		sf, err := sftp.NewClient(s)
		tsChan <- ts{
			sf:  sf,
			err: err,
		}
	}(sshConn, tsChan)
`
My application is actually running as a service, so i have been very careful about this type of leak. My suggestion for solving this kind of problem might be more simple just adding timeout channels directly when sftp.sendInit() ,sftp.recvVersion() and in client.go:429 where the closing the client:
c.sendPacket(sshFxpClosePacket{
		ID:     id,
		Handle: handle,
	})

**Comment by eikenb** [comment]
Doesn't the client connect timeout eventually at the OS level? You mention it timing out after 16 minutes in your initial post. I don't think moving the logic inside would change that. It'd still hang until the system timed it out.

Have you tried setting the timeout on the ssh client connection you pass in? 
https://godoc.org/golang.org/x/crypto/ssh#ClientConfig
