### ISSUE TITLE
Could this be refactored to support non-filesystem backed sftp servers?

### ISSUE THREAD

**Issue by jmunson** [pkg/sftp#204]
Unless I'm missing something it seems like the filesystem implementation is hardcoded -- Things expect a *Server, not a *Server interface,  and the *Server object doesn't abstract the FS operations.

I have an application that I was trying to add an SFTP interface too, but I didn't want to have to make actual files on an actual filesystem, I'd like to just handle the list files operation by enumerating them from our database, and then have uploading trigger a parser in my application. Downloading requests would be a matter of me mapping the filenames to AWS S3 paths from my database, then grabbing and serving them to the client.

From looking at the code, I think I'd need to be able to provide my own handlePacket(), but that refers to other unexported functionality, so I don't know where the best way to add a layer of abstraction would be.

**Comment by eikenb** [comment]
@jmunson .. Take a look at the files starting with "request-", they might be just what you are looking for. I implemented them as an alternative server that uses a set of 4 interfaces for all functionality. So you can, for example, write an SFTP server that uses S3 directly as its backend (my use case). 

The request-example.go is probably the easiest place to start as it implements a simple, in-memory, backend using the interfaces. Please let me know if you have any questions.

**Comment by jmunson** [comment]
Thank you, I completely missed that earlier
