### ISSUE TITLE
request-server ignoring errors from reader|writer close

### ISSUE THREAD

**Issue by Mayank1791989** [pkg/sftp#208]

**Comment by puellanivis** [comment]
More details would be able to focus people towards where the problem is, while excluding any work that lead you to find this issue.

**Comment by eikenb** [comment]
@puellanivis Thanks for responding to this and the previous ticket in my absence. And @Mayank1791989, thanks for the PR, I'll try to make time to look at it over today.

**Comment by puellanivis** [comment]
Me: “Could you elaborate on the problem?”
Mayank1791989: “Do you take answers in the form of a pull request?”
Me: “Oh… wow. Yeah, that’s pretty clear now. :)”

**Comment by Mayank1791989** [comment]
:)
