### ISSUE TITLE
request-server: problem with Request.setFileState() 

### ISSUE THREAD

**Issue by an2deg** [pkg/sftp#215]
Hi!

I faced with strange performance degradation during file download - upload shows 33 Mb/s while download shows just 16 Mb/s. 
Also during downloading a huge file from SFTP server, it did a lot of open() calls and  time to time went out of limit of 1024 max open files.
  
I started digging into RequestServer source code and here are my findings:
Let's take a look into fileget function:

    func fileget(h FileReader, r *Request, pd packet_data) responsePacket {
        var err error
        reader := r.getReader()

        if reader == nil {
            reader, err = h.Fileread(r)
            if err != nil {
                return statusFromError(pd, err)
            }
            r.setFileState(reader)
        }
        ...

In fileget() we expect that r.setFileState(reader) will assign `reader` to r.state.readerAt. 
Now let's see what is inside of Request.setFileState():

    // manage file read/write state
    func (r *Request) setFileState(s interface{}) {
        r.stateLock.Lock()
        defer r.stateLock.Unlock()
        switch s := s.(type) {
        case io.WriterAt:
            r.state.writerAt = s
        case io.ReaderAt:
            r.state.readerAt = s
        case ListerAt:
            r.state.listerAt = s
        case int64:
            r.state.lsoffset = s
        }
    }

But what if  `h.Fileread(r)` in fileget() returns an implements of both io.ReaderAt and io.WriterAt? That is exactly my case and r.setFileState(reader) sets reader to `r.state.writerAt` instead of `r.state.readerAt`

**Comment by eikenb** [comment]
@an2deg Thanks for the report. The fix might be as simple as splitting out the setFileState() into separate code for each use (reader, write,  lister) instead of the one generic method. I'm 99% sure that there is no reason those need to be together in one switch/method, but I want to review the code a bit more to be sure.
