### ISSUE TITLE
error handling and SSH_FXP_STATUS

### ISSUE THREAD

**Issue by sigmonsays** [pkg/sftp#219]
I am interested in having more control over the errors returned. For instance, if I want downloading of files disabled, i'd like to tell the user. Is there a way (perhaps a special type) to have replies populate the fields for SSH_FXP_STATUS?

The specific interface i'm interested in is FileReader, but I would like the same error handling for all Handlers methods. ie https://godoc.org/github.com/pkg/sftp#FileReader

Would a PR be accepted to accomplish this?

**Comment by sigmonsays** [comment]
As an example sftp-server snippet
<pre>
func (me *MyHandler) Fileread(r *sftp.Request) (io.ReaderAt, error) {
 err := &sftp.StatusError{
  msg: "Downloading is disabled",
 }
 return nil, err
}
</pre>

**Comment by eikenb** [comment]
This seems reasonable enough. I'll need to review the code a bit to see how feasible, but unless there is some API breaking stopper I'll be happy to do it.

**Comment by sigmonsays** [comment]
Sounds good. I can prepare a PR too if I find the time. Honestly not sure when I can, but I may have free time on a weekend

**Comment by eikenb** [comment]
It looks like this already works. If you return an error from any of the handlers, it gets wrapped in a StatusErorr with the StatusError.Code set to ssh_FX_FAILURE and the message set to err.Error().

So converting your example...

    func (me *MyHandler) Fileread(r *sftp.Request) (io.ReaderAt, error) {
        err := errors.New("Downloading is disabled")
        return nil, err
    }

Should do what you want as long as you want the code to be ssh_FX_FAILURE, which is the general purpose failure code. Though your example code would have used the default, 0, code which is ssh_FX_OK...  did you want an OK return with an error message?

If you wanted an OK code with a different message or other codes, that would require a small change but should be easy. The error handling code could just check for a StatusError type and just pass it through.

Though some clients might behave unusually if you send an OK message back for some things and they may or may not display the message, as that is usually paired with an error.

Section 7 of the spec covers it.
https://tools.ietf.org/html/draft-ietf-secsh-filexfer-02#section-7

**Comment by sigmonsays** [comment]
I will have to debug the sftp client then. All I see is "Failure" when i return errors.New("Whatever"). I find it strange why the client wouldn't show the proper error. Good to know, sorry for the confusion

**Comment by eikenb** [comment]
Interesting. This might be a bug in the way the client handles errors. I'll poke around there as well.

**Comment by eikenb** [comment]
I'm guessing you mean an external client application, as it looks like the sftp client code should return custom error messages correctly.

**Comment by sigmonsays** [comment]
FWIW, I am using the sftp client on ubuntu xenial from the openssh-client package.

**Comment by eikenb** [comment]
Yeah, looking at the sftp client code, it looks like in most cases the sftp client just ignores the returned error message.

**Comment by eikenb** [comment]
Closing this as the server code already sends the custom error messages and it it the client in use doesn't display them.
