### ISSUE TITLE
Filewrite does not provide a close hook

### ISSUE THREAD

**Issue by sigmonsays** [pkg/sftp#221]
I am working on providing sftp server into a storage api. When processing a Filewrite, it is required to return a io.WriterAt. However, io.WriterAt has no Close method. A close method would be required to know when writes have stopped and the file can be uploaded to the storage api.

Am I missing something in the API or does it make sense to change io.WriterAt to something more flexible?

**Comment by eikenb** [comment]
When the upload is complete, it does check to see if the object returned for the io.WriterAt supports io.Closer and calls Close if it does. The idea was that by requiring io.WriterAt but checking for io.Closer it would be more flexible.

Perhaps this is a documentation issue?

**Comment by sigmonsays** [comment]
oh, I must have missed that. This is perfect then. I did not see anything in the docs either.

**Comment by eikenb** [comment]
You wouldn't have seen anything in the docs... they don't mention it. I'll take this bug issue to mean that and add some documentation about checking for io.Closer.

Thanks for the input.
