### ISSUE TITLE
Returning ssh_FX_OP_UNSUPPORTED from sftp.Handlers

### ISSUE THREAD

**Issue by crazed** [pkg/sftp#223]
From what I can tell following the code, it does not seem possible to send the unsupported error since `statusFromError` does not include a way to set it. I'd propose that the sftp package define an error such as `ErrOperationUnsupported` and the `statusFromError` be updated to check for that error and set the return `StatusError.Code` appropriately.

**Comment by eikenb** [comment]
This sounds appropriate. I'll look into adding it.

**Comment by eikenb** [comment]
I'm going to add new errors for all the (revision 3) SSH_FXP_STATUS codes. Give the person implementing the new request-server handlers more control over their return codes. It will have some obvious overlap with the existing code in statusFromError and it gives the author the ability to break stuff, but it seems like a good option for those who want the greater control.
