### ISSUE TITLE
Allow creating write-only files

### ISSUE THREAD

**Issue by p886** [pkg/sftp#227]
`client.Create` currently has the `os.O_RDWR` flag [hardcoded](https://github.com/pkg/sftp/blob/c2bca6d35797804fcd48b2a092932abe708204fe/client.go#L119). This results in a `file does not exist` error when trying to create files as a user that does not have read rights.

Would it be possible to make these permission flags configurable?

**Comment by martinseener** [comment]
👍 we had this problem as well but "fixed" it on the server side, with more permissive permissions (more like a workaround). Would be nice to have this flag configurable somehow!

**Comment by eikenb** [comment]
The version of `client.Create` that lets you choose which flags you want to set already exists as `client.OpenFile`. So to create a file that is write-only, it would be something like...
```go
    client.OpenFile("/path", os.O_WRONLY|os.O_CREATE|os.O_TRUNC)
```
Is there some reason this won't work? Or is it lack of knowledge and maybe a mention in client.Create's documentation about it would help?

**Comment by eikenb** [comment]
Note that the Create/Open/Openfile API was designed to follow the pattern of the `os` package's File methods.
