### ISSUE TITLE
reads/writes with server example fails with Cyberduck

### ISSUE THREAD

**Issue by buyology** [pkg/sftp#229]
Reads and writes with the example servers fail with Cyberduck (ls works). 

I'm seeing a similar behaviour to what @unclejack reported in #132 in that I can get the upload work if it's the first request after a reconnect:

> Cyberduck failed to upload any file at all. I could get it to upload by closing the SSH+sftp server and letting Cyberduck reconnect after the restart. I think this may have simply performed the upload as the first operation without any file listing operations.

Any pointers to how I can embark on debugging this?

I've tried to tap in and see if I recieve anything at all but it's just stuck waiting at https://github.com/pkg/sftp/blob/1.4.0/request-server.go#L126

**Comment by eikenb** [comment]
I'll have to look into setting up Windows in a VM to test this as Cyberduck doesn't work with wine. I'll see what I can do, but it adds some overhead so will take me longer to find the time.

The server waiting at that line (request-server.go#126) means it is blocking on the incoming network socket waiting for data that never comes. I'd start trying to debug this by watching the incoming vs outgoing packets. A simple first view into this would be to print the packets in packet-manager.go, in the incomingPacket and readyPacket methods. You'd see all packets coming and going (they might out of order based on when those methods are called, but you can pair them up by the packet id).

**Comment by crazed** [comment]
@buyology do you mind confirming this is resolved with the latest commit on master? I gave it a shot with cyberduck and everything looks good now.

**Comment by buyology** [comment]
Sorry for the belated update on this issue, I was actually able to get the request server up and running before the update. (I should do a proper bisect of how I was able to solve it because I can't remember exactly now, but I think it was about Cyberduck being _very_ strict about the exact right `Mode` of the files).

Anyhow — very glad to hear about more features that tame some of the wild behaviour of some of the clients. 

Curious: when you tested it with `Cyberduck`/`WS_FTP` — what difference in behaviour did you see with your update? Fewer random errors?

**Comment by eikenb** [comment]
@buyology Please follow up with how you were able to get it working before if you can find the time. I'd like to be sure we are doing everything we can to keep all the various clients working and this info seems like it might be useful.
