### ISSUE TITLE
Support for file attributes on file open?

### ISSUE THREAD

**Issue by crazed** [pkg/sftp#232]
I was looking through the RFC and it seems that file attributes can be sent with the open file packet. Looking at `requestFromPacket`, it seems to only fill in the attributes on `sshFxpSetstatPacket`. I'm not sure how many clients actually send attributes on the `sshFxpOpenPacket`, but it would be useful to have things such as the file size available for optimizations when storing the file.

**Comment by eikenb** [comment]
@crazed Do you mean in the client or server code? If the server, do you mean the filesystem based server or the request based server framework? None of them support attributes on open, so I just want to be sure which you mean. Thanks.

**Comment by crazed** [comment]
Sorry I should have specified. In this case I'm talking about a server
handling a request from a client to create a new file.

**Comment by eikenb** [comment]
Thanks for clarifying. I think I can add it without introducing any backwards incompatibilities. I'll have to add it from the packet level up as the current packet (un)marshaling code ignores the file attributes on open packets. I haven't messed with the packet marshaling code yet, so I'll be cautious and it might take a bit.

I'll update here once I make progress and possible do a pull request for interested parties to review before merging.

**Comment by sigmonsays** [comment]
I have some interest in this as well. Using the openssh client, sftp command put -p (-P) sends file times and permissions which can not be received.

**Comment by eikenb** [comment]
I just merged PR #244 by @sigmonsays which fixes this.
