### ISSUE TITLE
Unknown extended packet handling

### ISSUE THREAD

**Issue by crazed** [pkg/sftp#233]
I was testing out integration with a few different clients and came across the fact that WS_FTP (a terrible windows client) sends an extended packet for something called "xquota". I wound up having to throw a `fmt.Println` in [packet.go#L900](https://github.com/pkg/sftp/blob/master/packet.go#L900) to pull this out.

It seems to me there should be some way for the server to tell the client this is unsupported and continue on just fine, but am unclear on the right approach there. 

I was looking over [this rfc](https://tools.ietf.org/html/draft-ietf-secsh-filexfer-extensions-00), which seems to indicate an SSH_FXP_STATUS packet can be returned to indicate an error. I wonder if it makes sense to add a struct that implements `sshFxpExtendedPacket.SpecificPacket` which writes an appropriate `SSH_FXP_STATUS` packet by default rather than returning an error here?

**Comment by crazed** [comment]
Probably opened this issue too soon, but after further debugging a simple fix is:

https://github.com/crazed/sftp/commit/9e3f1cbea8c3e0e3ba999bb4120337a633eb3ed0

If this looks okay I don't mind opening a PR.

**Comment by eikenb** [comment]
That doesn't quit work as the `pkt` returned with the error is nil and it needs to fit the ider interface (ie. have an `id()uint32` method). The easy fix would just be to return the partially unpacket extended packet from makePacket, as the ID value would have been unmarshalled before the error and it has the id() method.

The only thing is that smells a bit as returning a value with an error is not common practice. The alternative would be to unmarshal it again either using the same sshFxpExtendedPacket or a specialized one that only populates the ID field... and I don't think either is much better.

Unless you have a better idea I think just going with having makePacket() return the packet when it hits an error in UnmarshalBinary is the best solution.

**Comment by eikenb** [comment]
And this breaks TestInvalidExtendedPacket.
https://github.com/pkg/sftp/blob/master/server_test.go#L201

**Comment by eikenb** [comment]
This also might be the cause of the issue with Cyberduck, #229

**Comment by crazed** [comment]
Ah I see what you mean with the nil `pkt`. I think it makes sense to return the packet when it hits an error. There's some rare but possible cases for a partial value + error in the `io` packages around short writes, so I think this is okay?

I did not run the tests, but glad this may also help with another bug.

**Comment by eikenb** [comment]
Yeah. The io package is the one place I thought of as well... and I do think it makes more sense than the alternatives.

And the 2 `if err ==` checks in a row. I'd probably make that a switch statement or an if/else-if.

**Comment by puellanivis** [comment]
I would generally recommend testing for err != nil first, which leaves the common path short, and then in the “exceptional” path, where err != nil, then you test for specific values of err.

You’re already in an unexpected code path, and have likely thrown out (as we learned from Spectre) hundreds or thousands of speculative operations already, so complicating that path further is not such a bad deal…

Ugh, I’m pre-optimizing again aren’t I? …

**Comment by eikenb** [comment]
@crazed Did you still want to submit a PR for this? If not, I'd be happy to do it. 

I'd like to see this fixed, but would also like to let you contribute if that is your wish.

**Comment by crazed** [comment]
Sure I can contribute the fix, I'll open a PR tomorrow morning.
