### ISSUE TITLE
ReadFrom deadlock 

### ISSUE THREAD

**Issue by CodyDWJones** [pkg/sftp#234]
We discovered one of our file transfer goroutines was hanging trying to send a packet from a ~15MB file:

```
goroutine 361973 [chan send, 9270 minutes]:
delivery-service/vendor/github.com/pkg/sftp.(*clientConn).dispatchRequest(0xc421b34180, 0xc421cb7440, 0xf96840, 0xc42195c800)
        /go/src/delivery-service/vendor/github.com/pkg/sftp/conn.go:110 +0x1f3
delivery-service/vendor/github.com/pkg/sftp.(*File).ReadFrom(0xc420a4a660, 0xf90f80, 0xc420100310, 0x2540be400, 0x1, 0x0)
        /go/src/delivery-service/vendor/github.com/pkg/sftp/client.go:1016 +0x25b
```

The only explanation I can think of is `clientConn.broadcastErr()` ran concurrently to `dispatchRequest()` and there were `maxConcurrentRequests` requests in flight at the time. I sent SIGQUIT to the process but neither `clientConn.loop()` nor `clientConn.recv()` appeared in the resulting stack traces, suggesting `broadcastErr()` not only ran but it finished too.

I wonder if the #181 fix should be changed to create a channel of length `maxConcurrentRequests + 1`, rather than `maxConcurrentRequests`.

Suppose there are 63 in flight requests. `dispatchRequest()` is called, and it adds the 64th request, but sending the packet fails. Before it is able to remove the request from the in-flight map, `broadcastErr()` runs and queues 64 responses. `dispatchRequest` then acquires the lock, removes the 64th request, and blocks trying to queue a 65th response.

I'm too busy at work for the next two weeks to write a fix and test case, but wanted to record my thoughts before they were lost. I'll try to return to this issue in April.

**Comment by eikenb** [comment]
Looking over things I realized the tests that exercise these issues are both read tests (which hit Read and WriteTo). There are no corresponding write tests. I just added one that would hit ReadFrom and think I've reproduced the issue. Here's the test so you can reproduce it. Also note that your suggested fix does fix it. I want to read through things some more before committing to the fix, but it looks promising.

	// sftp/issue/42, abrupt server hangup would result in client hangs.
	func TestServerRoughDisconnect3(t *testing.T) {
		if *testServerImpl {
			t.Skipf("skipping with -testserver")
		}
		sftp, cmd := testClient(t, READWRITE, NO_DELAY)
		defer cmd.Wait()
		defer sftp.Close()

		rf, err := sftp.OpenFile("/dev/null", os.O_RDWR)
		if err != nil {
			t.Fatal(err)
		}
		defer rf.Close()
		lf, err := os.Open("/dev/zero")
		if err != nil {
			t.Fatal(err)
		}
		defer lf.Close()
		go func() {
			time.Sleep(100 * time.Millisecond)
			cmd.Process.Kill()
		}()

		io.Copy(rf, lf)
	}

If you run that (`go test -integration -v -run Disconnect3 -timeout 3s`) it spits out pretty much the same thing you got...

    goroutine 6 [chan send]:
    github.com/pkg/sftp.(*clientConn).dispatchRequest(0xc420078420, 0xc4200785a0, 0x87a3a0, 0xc420074c80)
	go/mylib/src/github.com/pkg/sftp/conn.go:110 +0x1c0
    github.com/pkg/sftp.(*File).ReadFrom(0xc42008b2c0, 0x876ba0, 0xc42000e098, 0x7fb55865b0a8, 0xc42008b2c0, 0x1)
    go/mylib/src/github.com/pkg/sftp/client.go:1039 +0x19e

**Comment by eikenb** [comment]
With a similar test I was able to reproduce it with Write() as well.

**Comment by eikenb** [comment]
I'd really like to understand why Read/WriteTo are find with a chan w/ a buffer of length maxConcurrentRequests while the Write/ReadFrom need maxConcurrentRequests+1. Is it that the code code allows different numbers of packets in flight, or is it a race and the more work required in the read methods just makes it very hard to trigger.

@CodyDWJones .. You looked over the code recently. If you any thoughts please share.

**Comment by eikenb** [comment]
Oh, I forgot to thank you for the bug report. I appreciate the time you took to file it. Thanks.

**Comment by CodyDWJones** [comment]
You're welcome! It's a good library.

The only explanation I can think of is that one or more buffers are coming back out of order. Then
`for inFlight+len(pendingWrites) < desiredInFlight {` won't allow the full 64 write requests to be issued simultaneously.

Besides that the code has the same pattern and (by my reading at least!) should also require the `+1`.

**Comment by eikenb** [comment]
That is my reading as well... which is why it bugs me that the read code works as is. I'm leaning toward adding the +1 chan buffer to the read methods as well. It doesn't cost much resource wise and keeps things consistent even if it happens to be impossible to trigger, and I really don't have the time to wade through that code enough to really understand what could be happening  right now.

**Comment by CodyDWJones** [comment]
I agree with that approach. It's pragmatic.
