### ISSUE TITLE
Extended packet handling, possible security issue in RequestServer?

### ISSUE THREAD

**Issue by crazed** [pkg/sftp#236]
While looking around the code I realized if someone formats an `sshFxpExtendedPacket` with request type `posix-rename@openssh.com`, they will be able to rename any file that the process has access to. Additionally a stat response can be obtained with a `statvfs@openssh.com` packet.

I wonder if it makes sense to support an option to just disable all handling of these extended packets in request server or exposing a way for the caller to handle them as desired?

**Comment by crazed** [comment]
Looked a little closer and realized the RequestServer explicitly checks for specific packet types and defaults to an error. I'm not sure if anyone wants custom extended packet handling but will close this for now.

**Comment by ncw** [comment]
It would be good to be able to implement the StatVFS call to return the total size available.

Ideally the interface would be extended to include StatVFS in one of the file handlers as I think it is a pretty normal thing to want to do.
