### ISSUE TITLE
Request server file list should not return io.EOF when n == 0

### ISSUE THREAD

**Issue by eikenb** [pkg/sftp#240]
Currently the code wrapping/calling the FileLister handler will return an io.EOF (indicating the end of the list) when the underlying handler returns 0 entries. I've come upon a situation where it is possible to return 0 entries in one batch, but still possibly have more entries to send.

https://github.com/pkg/sftp/blob/6d8540e9cf6a6bc6e49896da10ea33277e5993c0/request.go#L273

This was originally put there as a safeguard, in case the underlying FileLister code was ill-behaved and didn't properly return io.EOF.

I'd like to remove this check but wanted to post about it first to give others a chance to raise issues.

**Comment by eikenb** [comment]
Poking around this is going to require a bit more than just removing that check. I'll put together a pull request with the changes, but the idea is going to be to trust the returned error/io.EOF instead of checking `n`.

**Comment by eikenb** [comment]
Deleted the message about a PR  as I don't think it is needed... the change is very simple. Instead of removing the test, it instead just becomes...

`if err == io.EOF && n == 0 {`

This allows it to return when it receives an io.EOF and no results. Which should be the case after it has received all list entries. We don't want to just check for io.EOF as the final return is allowed to return n > 0 (some list entries) and the io.EOF. There is no SFTP packet semantics for indicating more entries and end of the list so we only accept io.EOF when n == 0 which should be returned every call after all the entries have been handled.

**Comment by eikenb** [comment]
@crazed @puellanivis @buyology @an2deg

Pinging you guys in case you want to chime in on this. Thanks.

**Comment by crazed** [comment]
This seems fine with me, thanks for the ping
