### ISSUE TITLE
Filecmd Mkdir unable to return SSH_FX_FILE_ALREADY_EXISTS

### ISSUE THREAD

**Issue by sigmonsays** [pkg/sftp#242]
Hello,

After reviewing the error handling it appears impossible to return specific error codes since they are all not exported. 

In this instance, I need to return SSH_FX_FILE_ALREADY_EXISTS when processing a Mkdir Filecmd. However after looking at how errors are converted to the SSH_FXP_STATUS response, I noticed that not all codes are exported. Is this by design?

in request-errors.go you have a handful of codes with exported types. For instance, ErrSshFxPermissionDenied is SSH_FX_PERMISSION_DENIED.

would a PR be accepted to export the remaining SSH_FX_ constants as ErrSshFX errors?

**Comment by eikenb** [comment]
This library implements SFTP  version 3 which doesn't support SSH_FX_FILE_ALREADY_EXISTS. That error was added in version 4 of the spec. So even if it was added, the clients wouldn't recognize it and might not be able to handle it (might crash/error). Version 3 was used as it is the only version that is universally supported.

**Comment by sigmonsays** [comment]
Ah that makes sense.  i'll refer to V3 of the spec from now on. 

I dont think there is anything to do for this task, we can probably close it.
