### ISSUE TITLE
SSH_FXP_FSETSTAT does not handle Attributes in RequestServer

### ISSUE THREAD

**Issue by sigmonsays** [pkg/sftp#243]
the openssh sftp clients put command has a flag, -p which specifies preserving file modified time. However, issuing put -p does not get passed through.

further debugging shows that the sftp server is receiving a SSH_FXP_FSETSTAT but is not populating the attributes. More specifically *sshFxpFsetstatPacket Attrs is empty in the RequestServer Setstat command. It appears that the packetWorker routine hasHandle case does not load attributes into the request from the underlying packet.

Should sshFxpFsetstatPacket result in a Setstat method being dispatched, and if so, how does one access the attributes?

I am looking to support preserving modified time on file upload which does not seem to be possible right now.

**Comment by sigmonsays** [comment]
while i'm not entirely aware of how this code is laid out, this fixes the issue I was seeing. The issue is how open file handles do not properly dispatch Attrs.

PR https://github.com/pkg/sftp/pull/244

**Comment by eikenb** [comment]
Merged PR #244 which fixes this.
