### ISSUE TITLE
static compilation and glibc

### ISSUE THREAD

**Issue by sigmonsays** [pkg/sftp#249]
the sftp server does not allow for static compilation, ie when glibc is not available. The package makes use of os/user LookupId [1] and LookupGroupId. Calls to these functions do not fail gracefully for some reason. I have seen 2 different panics from deep in the stdlib while making the cgo call. The panics do not always happen and different panics occur (uid or gid lookup).

[1] https://gist.github.com/sigmonsays/d38ffa60c87526e3c119a52b545f429d

i'm not sure what is actually happening here but it seems like cgo calls are not safe to make at all times. It could be because I am statically linking or something but I was unable to reproduce this in my own test case. 

Given that the server needs to lookup uid/gid for populating listings, can we make it extensible to avoid the system calls entirely?

It would be nice if it was optional behavior as there are no system users available which describe the uid/gid. I'd also prefer to not use glibc.

**Comment by eikenb** [comment]
This is unfortunate and makes me wish for a tool that reported if a build required cgo or not. I'll look into how to make this possible.

**Comment by eikenb** [comment]
There is no overly obvious way to make this optional at this point, so I think I'm just going to remove/revert the change where I added the lookup.

**Comment by eikenb** [comment]
A PR is always welcome! I was thinking about how to user and group lookup something that could be plugged in but haven't had a great idea yet... so if you want to get the ball rolling I'm all for it.

Also I'm about to push the revert of the user/group lookup changes that caused this. 

Thanks.
