### ISSUE TITLE
detecting early termination of clients in RequestServer

### ISSUE THREAD

**Issue by sigmonsays** [pkg/sftp#251]
If you upload a large file using plain old scp cli and ^C it mid transfer, the upload is still processed in my servers implementation (more on this later).  This results in a partial upload (truncated file) being processed as if it was a successful upload.

The issue is, afaik the FileWriter interface (https://godoc.org/github.com/pkg/sftp#FileWriter ) does not provide a way for the SFTP server tell the FileWriter interface that an error has occurred and the client has aborted. The FileWriter interface has a single method FileWrite, which returns a io.WriterAt. The io.WriterAt is allowed to have a Close method (ie, be an io.Closer) which can be used to process the upload on success. Ideally there would be a way to close a file and provide a error indicating the client has went away.

However, if the server provided a callback which fired globally for the entire RequestServer which indicated a client has closed its tcp connection prematurely, we'd be able to detect that the client has gone away and avoid the processing in the Close method.

Curious if you've thought about detecting premature client disconnects and want to provide a way to handle them gracefully.

**Comment by crazed** [comment]
I'm also interested in this but I believe you could do this by storing the file size as provided by the client in the initial file open call, then on close check to verify you have received that much data. The file size should be available in [Request.Attributes](https://godoc.org/github.com/pkg/sftp#Request.Attributes) results.

**Comment by eikenb** [comment]
I'm not sure how a callback would fit into the design so am not really thinking along those lines at the moment. If you have an idea about this please post it.

That seems to leave closing/finalizing the requests as the best place to handle this, similar to the how it works with Close. Maybe just a CloseWithError interface. The error would need to be propagated to the request objects and then passed along if that interface was available. I'm not sure this is the best way, just my first idea.

**Comment by sigmonsays** [comment]
@crazed So I spent some time and dug into the protocol and it appears that comparing the file size during open is not possible because the openssh client does not send the size in the SSH_FXP_OPEN packet. If the spec doesn't require size to be given then it can't be trusted.

walk through of decoding the SSH_FXP_OPEN packet https://gist.github.com/sigmonsays/ca0fc96c7a559841b7da770d8ca61b33

**Comment by crazed** [comment]
That's unfortunate and I kind of suspected this since the size is not required. 

As for how to handle this, I think a `CloseWithError` method like @eikenb suggested makes sense. The only thing I'd say is should we consider making handling this error required? I can't imagine someone would want to process partial files, especially once we have the ability to notify the implemented request server.

**Comment by sigmonsays** [comment]
i'm a little lost at the moment trying to find out where in code to detect an aborted client. If I sftp into my test sftp server using openssh sftp client, I do not see anything in the debug lines which indicate the server is closing. Its almost as if the openssh client is intentionally catching the SIGINT and closing the file correctly.

**Comment by eikenb** [comment]
> Its almost as if the openssh client is intentionally catching the SIGINT and closing the file correctly.

It does catch SIGINT and exits normally (including sending close to the server). So yeah.

**Comment by eikenb** [comment]
> The only thing I'd say is should we consider making handling this error required?

Can't make it required as that would break backwards compatibility. We could recommend it.

> I can't imagine someone would want to process partial files, especially once we have the ability to notify the implemented request server.

Client's can resume interrupted uploads. So maybe you might just not care how the client existed? You just save what you have and if they client didn't get it all uploaded they will just resume it.

**Comment by sigmonsays** [comment]
fair point, just now how I imagined it functioning. Allowing truncated files to be served seems like poor design choice (on the sftp protocol authors and openssh client code, not this package). We can just close this ticket because I dont see anything that we can do besides change the client.
