### ISSUE TITLE
OPENDIR is not processed correctly

### ISSUE THREAD

**Issue by LordRalex** [pkg/sftp#253]
As part of the SFTP Version 3 spec related to OPENDIR:

```
   The SSH_FXP_OPENDIR opens a directory for reading.  It has the
   following format:

        uint32     id
        string     path

   where `id' is the request identifier and `path' is the path name of
   the directory to be listed (without any trailing slash).  See Section
   ``File Names'' for more information on file names.  This will return
   an error if the path does not specify a directory or if the directory
   is not readable.  The server will respond to this request with either
   a SSH_FXP_HANDLE or a SSH_FXP_STATUS message.
```

In the case of both the request-server and server implementation, it will never return a SSH_FXP_STATUS  because this call is validated to ensure the directory exists. In the case of the server, it should check if the path requested exists on the server. In the case of the request-server, it should ask the handler if the directory exists.

In the case where the directory does not exist, then this call should be failing. However, what is happening is this call successes, so the SFTP client assumes the directory exists. A READDIR then is attempted, which errors.

Filezilla in this case burns because of it, as it followed the spec and assumed it was there. It doesn't react too well with this violation.

**Comment by LordRalex** [comment]
I made an example patch for this on a fork of the repo to provide a "fix", although the code is more of a hack for the project to work, and is definitely a breaking change with how I did it.

https://github.com/PufferPanel/sftp/commit/ccad98c8fe91b681f56c29a30712bb39bfdfead6

Essentially, in the case of the server.go, I just have it check to see if it can stat the file. If it can, we are good. If not, return a bad status code.

In the case of the request-server, I had to make a new interface to handle this request, as I did not see any other interface really suitable for this. I then have the request-server validate that the path is correct and accessible, and if not to return an error.

**Comment by eikenb** [comment]
I don't want to add another handler and I think the basic way you handled it for the Server will work for the RequestServer. That is have Opendir packets work like a Stat request when calling the handler and return based on that.

I'm going to take a run at doing it this way. I'll push the branch when I have something.

**Comment by eikenb** [comment]
Oh... and thanks for reporting the issue. It is a big help.

**Comment by eikenb** [comment]
Just pushed my branch and created a PR for it.

See #255
