### ISSUE TITLE
Make tags conform to what the new Go modules require

### ISSUE THREAD

**Issue by fd0** [pkg/sftp#261]
Hi,

thank you very much for all your work! I'm a very happy user :)

Can you please create tags for new releases in the form `v1.2.3`, with the `v` prefix? This is required for Go modules to recognize the version tags...

For the latest version, I think it'd be sufficient to just add a second tag `v1.8.0` pointing to the same commit as `1.8.0`.

Thanks a lot!

**Comment by eikenb** [comment]
There you go.

**Comment by fd0** [comment]
Awesome, thank you!
