### ISSUE TITLE
Issue with rename ** resolved

### ISSUE THREAD

**Issue by danfletcher1** [pkg/sftp#264]
Hi, 
I noticed an issue with the latest download, when I rename a file, I am using the request-example.go. The rename does not show but it does not show in the directory listing as changed but it has in the background as the file does not exist on the old name. I have added a line that resolved the issue.

Line 86-89 on request-example.go, I added the middle line. The files name is in 2 places.

fs.files[r.Target] = file
fs.files[r.Target].name = r.Target
delete(fs.files, r.Filepath)

**Comment by eikenb** [comment]
Thank you for not only submitting this issue, but for diagnosing and fixing it. I'll be pushing a fix in a couple.
