### ISSUE TITLE
SFTP Session Start Bug?

### ISSUE THREAD

**Issue by JackWink** [pkg/sftp#270]
Couple questions about the example server. The RFC for SFTP/SSH says that [only one request should be accepted per channel](https://tools.ietf.org/html/rfc4254#section-6.5). 

The [code in question](https://github.com/pkg/sftp/blob/master/examples/request-server/main.go#L106) will respond affirmatively more than once per channel. Is this intentional/have you observed bad SFTP clients that need this behavior?

Likewise, it seems like we shouldn't pass the channel into the SFTP server/handler until the client has sent a channel request for SFTP, otherwise they might request a "shell" or "exec". I'm wondering if this is due to poorly implemented clients, me misunderstanding the RFC, or just a bug in the sample.

Lastly, are there any timeouts or ways for the server to close a connection if the client isn't using it as an SFTP server?  Like if someone connects, but continues to issue requests for a shell, would this keep the connection open indefinitely?

**Comment by eikenb** [comment]
Hey Jack, good to hear from you.

First note that the doc says that only one of the those 3 types of requests should be accepted per channel and there are other types of requests that can be sent. The openssh sftp client, for example, first sends an 'env' request before it sends the 'subsystem' request. So it needs to process and (in this case ignore) that before it can receive the subsystem request. 

It doesn't limit those 3 types though, and a misbehaving client could continue to send requests even after receiving a success. I haven't seen that in practice, but a bad actor could do it on purpose. Though that code doesn't get run until after the login is successful, so the exposure is limited.

If you wanted to make that code extra-safe you could add a WaitGroup to keep it from kicking off the server until it has received the appropriate subsystem request along with a timeout or a limit on the number of requests. But I'm not sure if that level of robustness is appropriate for an example.

**Comment by JackWink** [comment]
Right, as I understand it the requests are based on the server's capabilities -- I guess I'm wondering if I can process the requests synchronously first, until the client sends the SFTP subsystem command, then pass the channel off to the SFTP handler instead of processing the requests out of band?  It seems like the sample code passes the channel to the SFTP server before the client has actually requested an SFTP session.

**Comment by JackWink** [comment]
And thanks for getting back to me so quick!

**Comment by eikenb** [comment]
I think a WaitGroup is might be simpler than your sync-then-async request handling, but they'd probably be pretty close. I just tried it using a WaitGroup to gate launching the server and it works with the openssh sftp client. I have no idea if there are clients that fail to send the subsystem request. I'd doubt it, but the clients vary quite a bit and make some odd decisions... so anything is possible.

I tend to look at openssh's sftp server/client when I wonder about the 'standard' way of doing things and if I'm reading it's code correctly it doesn't kick off the sftp subsystem process until it has received the systems/sftp request. So it looks like that should be OK. Note that it does continue to process and ignore requests during the entire session.

**Comment by JackWink** [comment]
Wouldn't https://github.com/pkg/sftp/blob/master/examples/request-server/main.go#L122-L123 start treating the channel as an SFTP session as soon as a session channel is opened, but prior to receiving the subsystem request?

I should have mentioned that we did a similar thing on our end -- instead of a WaitGroup, we're launching the SFTP server in a new routine from the goroutine that's servicing the channel requests, and ensuring that the server will only be spawned once even if the client sends duplicate requests for the SFTP subsystem. We're still deciding whether or not to tear down the connection if the client requests a shell, or fails to send any request after a certain timeout, but we'll probably push that down the line until we see some misbehaving clients.

Thanks for looking into this!

**Comment by eikenb** [comment]
I believe it would start up the server and would work even if the client doesn't send the subsystem request as you think... but this will depend on the behaviour of the client. The Openssh client, for instance, doesn't try to do anything with the connection until the requests have all been sent through. It assumes the server won't work until the requests have been processed (and it wouldn't with the Openssh's sftp server). 

So in practice the fact that the server is started before the requests are all handled probably doesn't matter. But you should be able to make it matter without affecting anything and it would line up more closely with what Openssh does.
