### ISSUE TITLE
Questions/comments about about RequestServer

### ISSUE THREAD

**Issue by AGWA** [pkg/sftp#277]
Thanks for the great package! I'm using `RequestServer` to implement a very simple read-only server that's confined to a certain root directory, and I ran into the following questions/comments:

1. How do you distinguish between `Stat` and `Lstat` requests?  I see that `Server` [handles them separately](https://github.com/pkg/sftp/blob/08de04f133f27844173471167014e1a753655ac8/server.go#L160-L179), but with `RequestServer` they are [coalesced into a "Stat" request](https://github.com/pkg/sftp/blob/08de04f133f27844173471167014e1a753655ac8/request.go#L367-L368).

2. `os.FileInfo` isn't a good type for the result of a `Readlink` request.  `Readlink` needs to return the full path of the symlink target.  `os.FileInfo` has six methods, none of which are suitable for conveying a full path.  `RequestServer` currently uses the `Name()` method to get the target, but this is contrary to the [interface of `os.FileInfo`](https://golang.org/pkg/os/#FileInfo), which says that `Name()` returns the "_base_ name of the file".  In my project I ended up having to define a struct just to hold the symlink target.  `Name()` returns the target while the other five methods just panic.

3. It's pretty unergonomic for `Stat` and `Readlink` calls to return a `ListerAt` when they always return exactly one item.  This leads to a boilerplate type that implements `ListAt` to copy exactly one item.  Perhaps `Filelist` should be broken into several different methods with appropriate return types, instead of having one method that has to switch on a string and coerce the result into an unsuitable type?

**Comment by eikenb** [comment]
Sorry for the delay in responding. Personal life got kind of crazy. 

The goal was to make implementing a basic SFTP compatible server as simple as possible. To achieve this I decided to focus on the basics; listing, uploading and downloading. So stat, readlink, etc. were supported as a simplified versions of list and so all returned the same type as list.

**Comment by eikenb** [comment]
I plan on revisiting some aspects of the request-server when I port the filesystem based server to use the request-server. I want to be able to just swap out the existing server in all the integration tests to get better coverage of the request-server. This means it will need to be able to replicate the functionality of the filesystem based server (eg. things like readlink).

Doesn't help much in the short run, but I don't want to break compatibility at this point.
