### ISSUE TITLE
Client need a way to detect underyling SFTP connection closed

### ISSUE THREAD

**Issue by wutzx** [pkg/sftp#278]
When sftp-server have been killed or crashed, there need a way to detect SFTP connection closed and reconnect.

Like ssh which provides a Wait method, sftp can also provides a Wait method in https://github.com/pkg/sftp/blob/08de04f133f27844173471167014e1a753655ac8/conn.go#L34

**Comment by phoenixJu** [comment]
Is there any solution for reconnect (retry) when ssh is broken because of network shake？for an instance， download video file failed
