### ISSUE TITLE
Keeping request server open after a failed password attempt

### ISSUE THREAD

**Issue by cajund** [pkg/sftp#284]
Hi there, 

I appreciate your work. Thanks for it.

I am using the request server example as a base to crate a "drop box" type of functionally via sftp. Is the request server code the correct approach for a drop box?

Also, the user is authenticated against an external IDP service. I don't think this pertains to your code, so I am not sure this this the right place to ask this question. But here it goes:

If the user/password auth process fails, the `PasswordCallback` handler (in the `ssh.ServerConfig{}`) returns a non-nil error. As a result the `ssh.NewServerConn()` closes down and the server needs to be restarted. Is there a way to prevent this? 

Any help is appreciated, thanks.

**Comment by eikenb** [comment]
The example servers were initially written with using them as an SFTP backend for OpenSSH in mind. OpenSSH handles SFTP by spawning a new process for each incoming SFTP connection and then exiting when done. To write a long running SFTP server that 
handles the incoming requests requires looping over the connections.

So.. if I'm interpreting your question correctly you might find some help in a previous issue which asked about handling more than 1 connection; #276 

I'm thinking a more robust example might be useful to help document how you'd do this.. but for now if you have any questions please feel free to ask.

**Comment by cajund** [comment]
Thank you, yes - this worked perfectly. Used your example from #276, but spun off a `go func()` so as to not block any other incoming requests.
