### ISSUE TITLE
how to limit scp flow rate?

### ISSUE THREAD

**Issue by atdevp** [pkg/sftp#294]
# how  to limit flow rate ?  my sample code:

```bash
func Scp(srcdir, locdir, ip, splitType string, sftpClient *sftp.Client) (string, error) {

	absSrcfileName, filename := utils.GetLogFileName(srcdir, splitType)

	if absSrcfileName == "" || filename == "" {
		return "", errors.New("parse srcdir result is null")
	}

	absSrcfile, err := sftpClient.Open(absSrcfileName)
	if err != nil {
		return "", err
	}
	defer absSrcfile.Close()

	// /tmp/test/[yyyymmdd]/[hh]
	// return /tmp/test/20190202/22
	dir, err := utils.ParseDir(locdir, splitType)
	if err != nil {
		log.Println(err)
		return "", err
	}

	_, err = utils.Exists(dir)
	if err != nil {
		err := os.MkdirAll(dir, 0755)
		if err != nil {
			return "", err
		}
	}

	ipFilename := fmt.Sprintf("%s-%s", ip, filename)
	absLocfileName := path.Join(dir, ipFilename)
	absLocfile, err := os.Create(absLocfileName)
	if err != nil {
		return "", err
	}
	defer absLocfile.Close()

	if _, err = absSrcfile.WriteTo(absLocfile); err != nil {
		return "", err
	}

	sftpClient.Close()
	log.Printf("[I] pull %s  to %s from %s success", absSrcfileName, absLocfileName, ip)

	return absLocfileName, nil
}
```

**Comment by puellanivis** [comment]
You mean to ask how you would limit the speed at which `absSrcfile.WriteTo()` would copy at?

You would have to implement a bandwidth-limiting `io.Writer` wrapper that would write data at a limited rate. There are simple and complex ways to do that, depending on how much reliability you need. If all you need is just “best effort”, you could setup a `time.Ticker` and write out XY amount of data every tick.

For say, 1 MB/s, you could make a ticker at every 10 milliseconds, and then write out 10 kilobytes every tick.

**Comment by eikenb** [comment]
A ticker like @puellanivis suggests is probably the best way to implement this in the Go code. Your other choice would be to use a separate traffic/bandwidth shaper. There are ways to do it via the Linux kernel, firewalls and userspace tools. A quick googling came up with a couple decent points to start at...

https://unix.stackexchange.com/questions/28198/how-to-limit-network-bandwidth
http://xmodulo.com/limit-network-bandwidth-linux.html

These are all Linux based, so if you're on another platform you'll need to dig into that yourself if you don't like the timer/ticker solution.
