### ISSUE TITLE
sftp resume produces corrupted files

### ISSUE THREAD

**Issue by drakkan** [pkg/sftp#295]
I'm writing an SFTP server using this great library, I have a problem with uploads resume.

In my app I'm using `sftp.NewRequestServer` but the problem is reproducible also with the simple sftp example here 

https://github.com/pkg/sftp/blob/master/examples/go-sftp-server/main.go

please try this:

```
sftp -P 2022 testuser@127.0.0.1
sftp> put <path to some large file>
```

interrupt the transfer using CTRL+C and then resume the upload

```
sftp> reput <path to some large file>
```
the uploaded file has the same size as the original one but a different checksum

get/reget works as expected.

thanks

**Comment by eikenb** [comment]
Thanks for the report. I'll try to get to this ASAP though it might take a bit as I'm super busy at the moment.

**Comment by drakkan** [comment]
Hi,

I just tested this again, I don't exactly remember the tests I did in the past, but I cannot reproduce the reported behaviour, maybe I was doing something strange in my application at that time. 

Resume still fails and the problem is that we cannot use WriteAt with a file opened in append mode:

https://github.com/golang/go/blob/master/src/os/file.go#L176

so a workaround is to ignore the append flag, for example if I comment out this line:

https://github.com/pkg/sftp/blob/master/server.go#L401

the sftp-server seems to work fine, and I can got resume working in my application if I do the same there.

If you give some guidance I can try to send a proper patch. 

Since we use WriteAt that cannot work with O_APPEND flag maybe we just have to document this behaviour and fix `server.go`, what do you think about? thanks

**Comment by drakkan** [comment]
The specs says:

```
SSH_FXF_APPEND
      Force all writes to append data at the end of the file.  The
      offset parameter to write will be ignored.
```

so I tryed to open the file in APPEND mode and when `pkg/sftp` call `WriteAt` method of my interface I call `Write` on the underlying file instead: this way the file size match but the hash mismatch, probably this is what I did initially.

I confirm that ignoring O_APPEND and using `WriteAt` respecting the given offset works fine using the `sftp` CLI client but I would not be surprised if other clients will not work.

**Comment by eikenb** [comment]
Are you using the request based setup to write your server? If so, then you have control over how you open files and you don't need to use the append flag. Given it was designed to allow using non-traditional backends, it doesn't make sense to use append as they may not even support opening a file append-only. For resume you'd just need to be sure to use the offsets correctly. If the client just doesn't set the offsets on resume you'd just have to return an error in those cases. Though I haven't seen a client that does that yet.

For the server.go implementation I think this will just need to be documented. Both server implementations use WriteAt to allow for multiple threads to work with the same file. To speed things up. Switching to a setup that would allow for append would mean having to synchronize all writes in order which, while possible, would be a fairly major rewrite.

Thinking of a time in the future when we've been able to re-write the filesystem based server.go using the request backend. It could support it either by just not using the append flag with the files on the filesystem (just making sure offsets are relative to the EOF) or it could implement a write buffer that is used until it fills up a chunk then write that out.

**Comment by eikenb** [comment]
Hey @drakkan, sorry for the long silence on this. Life keeps making it hard to find  free time to spend on this. Glad to see you figured out a way to work with the behavior.

I was thinking about the append w/o offsets and the only way that would make sense for a client would be if they stat the partial upload, seek to that in the local file then start an upload from there in append mode. Seems like it might be possible to work with this by setting the initial offset to the end of file when the append flag is set. Taking a look at your code (1d91756 linked above) you had the same idea. Sorry if I'm rehashing... catching up again mentally.

Trying to nail down fixes for this.

1. Update server.go to set the offset to the end of the file when opening the file and the append flag has been set. It should be pretty straightforward, the changes would be encapsulated in... https://github.com/pkg/sftp/blob/8488d36edee795c85c0f878ef8df4c6e5175b34a/server.go#L388

2. Update the documentation for the request based server with a note about how you need to handle APPEND flags.

Sound about right?

**Comment by drakkan** [comment]
> Hey @drakkan, sorry for the long silence on this. Life keeps making it hard to find free time to spend on it. Glad to see you figured out a way to work with the behavior.
> 
> I was thinking about the append w/o offsets and the only way that would make sense for a client would be if they stat the partial upload, seek to that in the local file then start an upload from there in append mode. Seems like it might be possible to work with this by setting the initial offset to the end of file when the append flag is set. Taking a look at your code (1d91756 linked above) you had the same idea. Sorry if I'm rehashing... catching up again mentally.
> 
> Trying to nail down fixes for this.
> 
> 1. Update server.go to set the offset to the end of the file when opening the file and the append flag has been set. It should be pretty straightforward, the changes would be encapsulated in... https://github.com/pkg/sftp/blob/8488d36edee795c85c0f878ef8df4c6e5175b34a/server.go#L388
> 2. Update the documentation for the request based server with a note about how you need to handle APPEND flags.
> 
> Sound about right?

It seems ok to me, even if the specs say the offset is optional for resume, all the tested
clients sets the right offset
