### ISSUE TITLE
get nil error when kill remote sshd or disconnect network

### ISSUE THREAD

**Issue by sjx95** [pkg/sftp#300]
I'm trying to use sftp to transfer files via unstable connections.
In my test, I found that when I kill the remote sshd, 
in most cases sftp.File.ReadFrom returns nil error,
but a few cases return "failed to send packet: EOF".

I think it should be expected to return a "sender EOF",
at least the behavior should be in consist.

Besides, when I disconnect my WLAN, the above problem occurs too.

Here is my test code:
https://gist.github.com/sjx95/e279f937db86d964b6d6d028860ad626

The core line:
```
sentTotal, sentErr := fw.ReadFrom(fr)
```

**Comment by eikenb** [comment]
Are you saying it usually returns a `nil` error when in fact it failed to send the file or at least all of it? In other words, most of the time it returns nil even when there was an error but occasionally it does return an  error (as it should) and that error is "failed to send packet: EOF"?

**Comment by sjx95** [comment]
@eikenb Yes. In my test case, it writes bytes less than file length and usually returns nil error.

**Comment by eikenb** [comment]
Thanks. I just wanted to be sure I read it correctly. It should always return an error if not successful and I've labeled this a bug. I'm pretty swamped but am trying to make time to work on things here and will try to get to it as soon as possible.

**Comment by sjx95** [comment]
Just now I have some review on sftp.File.ReadFrom(),
and I notice some code like this:
https://github.com/pkg/sftp/blob/8fc59612f2b0bbd784120cdea44aebc999b17c1d/client.go#L1164-L1167

I think maybe it causes this problem if the reading files return EOF earlier than net error occurs, firstError will be set to io.EOF. This prevents the referred code to set firstError.

Could you please have some check later?

**Comment by eikenb** [comment]
@sjx95 .. You might be right, it does seem there might be a bit of a race in processing the packet returns.

Could you test changing that (line 1164 above) to...
```
if err != nil && (firstErr == nil || firstErr == io.EOF) { 
```
Seems like that would fix the issue.

If it does I'll look into fixing it in a more general way as multiple places should suffer from the issue.

Thanks.

**Comment by sjx95** [comment]
Sorry for that I have lost permission to access my code because I finished my internship.
I'll write a test case later, thanks.

**Comment by eikenb** [comment]
@sjx95, sorry we didn't get this addressed during your internship. Help testing it will be a big help, so please let me know if you get a chance to run that test. If you don't think you'll get time, maybe you could briefly describe the test case here so I could try to reproduce it?

Thanks for contributing!

**Comment by drakkan** [comment]
@sjx95 the client code has changed significantly, are you able to reproduce this issue with the current git master? Thank you

**Comment by drakkan** [comment]
This should be fixed in recent versions, please reopen if you are still able to reproduce the issue, thank you
