### ISSUE TITLE
Proposal: *request.ctx being exported

### ISSUE THREAD

**Issue by danfletcher1** [pkg/sftp#314]
I would like to make a proposal

You will have to forgive me if I am using this wrong. Please do explain how I should be using this better. In my project I liked the idea of using the InMemoryHandler() example in request-example.go

in a snip-it of my code here, I use ::

myHandlers := sftp.InMemHandler()
server := sftp.NewRequestServer(channel, myHandlers)

if err := server.Serve(); err == io.EOF {
	server.Close()
	// Save data from the InMemory filesystem
	_, err = saveUploads(myHandlers, srvconn.User(), nConn.RemoteAddr().String())
} else if err != nil {
	log.Fatal("sftp server completed with error:", err)
}

This saveUploads() function I created, makes a *request and uses the FileList() funciton to get data out of the *memFile. As show below ::

myrequest := sftp.Request{
	Method:   "List",
	Filepath: path1,
}

myListerAt, err := myHandlers.FileList.Filelist(&myrequest)

Since the introduction of the context, which is not exported, am now unable to generate a valid request outside of the package. 

I'm a bit stuck on what to do now, how should I get the data out. Any opinions? Making the ctx and cancelCtx exported would solve my issue, is that a sensible proposal.

If your enquiry is why. Well I give every login an empty virtual memory drive. On session exit, I read the data upload to a shared space, the files never actually exist on the disk. I have more than one sftp server, with a DB that logs who send what from where and generates filenames so I never have overwrites or clashes, and can see all the different versions uploaded. It seemed a good idea at the time.

**Comment by puellanivis** [comment]
Why does it not work to use `myrequest.WithContext`?

**Comment by danfletcher1** [comment]
Thank you for that pointer.

This is a new addition for me.

I will try this out.

Kind regards Dan

**Comment by eikenb** [comment]
@danfletcher1 Does WithContext() address your need?

And sorry for the poor state of the documentation.

**Comment by eikenb** [comment]
Hey @danfletcher1, I'm going to assume that you've been able to get it working using WithContext as suggested (thanks @puellanivis). If not, please let us know.
Thanks.
