### ISSUE TITLE
failed to send packet: EOF

### ISSUE THREAD

**Issue by jeriveromartinez** [pkg/sftp#319]
i try to download a file from remote server and the client.Open function return "failed to send packet: EOF".

**Comment by eikenb** [comment]
Hey @jeriveromartinez, thanks for taking the time to file a ticket.

Could you include a snippet of the code you are using? Also any information about the server you are trying to connect to would be helpful.

Thanks.

**Comment by LucasjuvR** [comment]
Hi was having the same issue with ReadDir. The solution for me was to get rid of closing the connection with defer, maybe somehow the method gets out of context and the deferred functions are called. I was calling close on both the ssh connection and the sftp client.

**Comment by puellanivis** [comment]
Hm… I’m doing something somewhat similar. But the connection, and the `defer`ed close are setup in `main`, and only in `main`. When I do end up closing (only when the program is ending), I make sure to close the sftp client before the ssh connection.

Although, I do have a side goroutine that uses the client’s `Wait` function, to notify me of when the sftp client closes, at which point, I also prophylactically close the ssh connection. This still strictly enforces the `happens after` order, so no issues about ordering…

But now that I look at the code, it’s also possible I could end up double closing an ssh connection this way. :woman_shrugging:

Ideally, you want the connection to be as long-lived as possible, preferably as much as possible the duration of the lifetime of the executable. If you are performing multiple connections, and tear-downs the odds of a bug happening increase a lot.

**Comment by eikenb** [comment]
@jeriveromartinez, @LucasjuvR, @puellanivis 

Without hearing back on the particulars from the original submitter, is there anything more we can do related to this? Seems like it is complexities that are inherent to the issue of working with long running (ssh) connections. Can't really document that and examples are by their nature simplified.

**Comment by eikenb** [comment]
Doing a bit of housecleaning and it seems we're done with this one.
