### ISSUE TITLE
sftp connected failed

### ISSUE THREAD

**Issue by xiejunshi** [pkg/sftp#320]
Why can't I connect to my sftp server with the command line?
![image](https://user-images.githubusercontent.com/37329665/68586069-c72af500-04be-11ea-87a1-97de1463f920.png)

Connect with winscp：
![image](https://user-images.githubusercontent.com/37329665/68586123-e3c72d00-04be-11ea-940d-8f343144f427.png)

**Comment by drakkan** [comment]
If you use a non standard port you need the `-P` option, for example:

```
sftp -P 13044 test@10.90.146.184
```

**Comment by xiejunshi** [comment]
thanks

**Comment by xiejunshi** [comment]
[](https://github.com/pkg/sftp/issues/318) 
There is still this problem
![image](https://user-images.githubusercontent.com/37329665/68590102-ae274180-04c8-11ea-8f31-31060c230528.png)
I want to control the size of this data, can it be achieved?

**Comment by puellanivis** [comment]
You don’t control that from our side. In this situation, the package contains the data chunk to write, and the server cannot at all make the packet contain a larger chunk.

**Comment by xiejunshi** [comment]
Do you mean that this packet size is specified by the sftp protocol itself?

**Comment by puellanivis** [comment]
Not necessarily. The client is sending the packet, which determines the `data` buffer size being given to `WriteAt` here.

**Comment by drakkan** [comment]
as for [specs](https://tools.ietf.org/html/draft-ietf-secsh-filexfer-02):

> The maximum size of a packet is in practice determined by the client
   (the maximum size of read or write requests that it sends, plus a few
   bytes of packet overhead).  All servers SHOULD support packets of at
   least 34000 bytes (where the packet size refers to the full length,
   including the header above).  This should allow for reads and writes
   of at most 32768 bytes.

we accept at most 262144 bytes packets
