### ISSUE TITLE
sftp forward

### ISSUE THREAD

**Issue by xiejunshi** [pkg/sftp#323]
I set up a sftp server, now I want to make a forwarding service between the client and my sftp server, how should I implement.

like this:
![image](https://user-images.githubusercontent.com/37329665/69607693-c36fa480-1060-11ea-92b1-763fc0c549c4.png)

**Comment by puellanivis** [comment]
This would be a proxy. It’s probably not best to use this library to proxy SFTP? You should be able to proxy SFTP through SSH `-o ProxyJump` settings?

**Comment by eikenb** [comment]
Hey @xiejunshi, good question.

To reiterate what @puellanivis, you are best proxying this at the underlying network level vs. at the protocol level. Ssh is a great tool for this if you have shell access on the forwarding server. If you don't but can put a service I'd suggest using [NGINX's  stream proxy module](http://nginx.org/en/docs/stream/ngx_stream_proxy_module.html). If you need more resources, a [quick googling](https://www.google.com/search?hl=en&q=nginx%20stream%20proxy%20ssh) should get you some help.
