### ISSUE TITLE
Request.Attributes() can panic when called with the Attr slice empty

### ISSUE THREAD

**Issue by vansante** [pkg/sftp#325]
As mentioned in the title, I got a panic in production.

Is this supposed to happen and am I supposed to check the byte slice myself prior to calling `Attributes()`, or can we just check that in the function (that would be my preference) ? Or is the byte slice always supposed to be filled? (My guess this is some weird client that did not comply to the SFTP standards).

Panic here:

```
panic: runtime error: index out of range [3] with length 0

goroutine 261287 [running]:
github.com/pkg/sftp.unmarshalUint32(...)
        /go/pkg/mod/github.com/pkg/sftp@v1.10.1/packet.go:73
github.com/pkg/sftp.getFileStat(0x138, 0xc0016125df, 0x4, 0x4, 0x3, 0x8, 0x30, 0x8)
        /go/pkg/mod/github.com/pkg/sftp@v1.10.1/attrs.go:118 +0x53d
github.com/pkg/sftp.(*Request).Attributes(...)
        /go/pkg/mod/github.com/pkg/sftp@v1.10.1/request-attrs.go:61
source-dir/sftp.(*RequestHandler).handleSetStat(0xc001324cc0, 0xc000dcd620, 0x6, 0x6, 0xc0006fe540, 0xc0011d1030, 0x6, 0x6)
        /source-dir/sftp/request_handler.go:296 +0x65
source-dir/sftp.(*RequestHandler).Filecmd(0xc001324cc0, 0xc0006fe540, 0xc00045bba0, 0x10)
        /source-dir/sftp/request_handler.go:276 +0x6e2
github.com/pkg/sftp.filecmd(0xfd6d00, 0xc001324cc0, 0xc0006fe540, 0xfe00c0, 0xc0023aba40, 0xfdf180, 0x40df9b)
        /go/pkg/mod/github.com/pkg/sftp@v1.10.1/request.go:267 +0xd4
github.com/pkg/sftp.(*Request).call(0xc0006fe540, 0xfd6d40, 0xc001324cc0, 0xfd6d60, 0xc001324cc0, 0xfd6d00, 0xc001324cc0, 0xfd6d20, 0xc001324cc0, 0xfe00c0, ...)
        /go/pkg/mod/github.com/pkg/sftp@v1.10.1/request.go:162 +0x389
github.com/pkg/sftp.(*RequestServer).packetWorker(0xc001161000, 0xfec780, 0xc000d2d180, 0xc000da4600, 0x70189a101, 0xc00082c7c8)
        /go/pkg/mod/github.com/pkg/sftp@v1.10.1/request-server.go:187 +0x559
github.com/pkg/sftp.(*RequestServer).Serve.func1.1(0xc000c07030, 0xc001161000, 0xfec780, 0xc000d2d180, 0xc000da4600)
        /go/pkg/mod/github.com/pkg/sftp@v1.10.1/request-server.go:98 +0x89
created by github.com/pkg/sftp.(*RequestServer).Serve.func1
        /go/pkg/mod/github.com/pkg/sftp@v1.10.1/request-server.go:96 +0xa1
```

**Comment by puellanivis** [comment]
It looks like `Attrs == nil` is true for almost all packet types. It would be a good idea probably to have a test that `len(r.Attrs) > 0` in the `Attributes()`, but that should also require it to return an `error`, which would change the API. We could return `nil` as the `*FileStat` but that also leads to the possibility of an unexpected panic, and the whole “do not use inband errors” thing.

Hm… you’re probably better off building a guard for `len(r.Attrs) < 1` yourself in `handleSetStat`, then you can determine exactly what kind of business logic makes sense to do in such a weird case.

**Comment by vansante** [comment]
I suppose Id rather see the `Attibutes()` function like this:
```golang
func (r *Request) Attributes() *FileStat {
	if len(r.Attrs) == 0 {
		return nil
	}
	fs, _ := getFileStat(r.Flags, r.Attrs)
	return fs
}
```
And then leave it up to the caller to check for a nil value rather than panicking halfway. But in the end, I suppose it's more or less the same. Ill check the request `Attrs` array prior to calling `Attributes()` for now.

**Comment by drakkan** [comment]
@vansante do you know which SFTP client has this behaviour? Can you please log the client version?

**Comment by vansante** [comment]
I am not 100% certain since my process crashed, but from prior logs my suspicion goes to https://www.smartftp.com/

**Comment by drakkan** [comment]
@vansante I did a quick test using smartfp 8.0. I tryed to change permissions on symlinks, folders and files and I was unable to replicate the issue, the permissions were successfully changed and I don't see this log:

https://github.com/drakkan/sftpgo/blob/master/sftpd/handler.go#L265

maybe it happens only with some (maybe older) versions.

Anyway thanks for sharing this issue so we can now guard against these clients

**Comment by vansante** [comment]
The client user agent was reported as `SSH-2.0-SmartFTP`, so no version numbers unfortunately. Thanks for testing regardless! And yeah, checking the slice will prevent this in any case, so if anyone else runs into this, they know what to do :)

**Comment by puellanivis** [comment]
So, yeah, the guard and return `nil` instead of a `panic` is a way of solving the issue. But then, instead of breaking the “don’t panic“ guideline, we’re breaking the `no inband errors” guideline.

Because now client still have to guard against the possibility of receiving a `nil` point of the object, which isn’t much any better. :woman_shrugging:

**Comment by vansante** [comment]
Wouldn't this also work (and be technically correct, since the values were not provided and thus zero) ?

```golang
func (r *Request) Attributes() *FileStat {
	if len(r.Attrs) == 0 {
		return &FileStat{}
	}
	fs, _ := getFileStat(r.Flags, r.Attrs)
	return fs
}
```

**Comment by puellanivis** [comment]
So, that would also still work, would prevent the need to check against nil, but I don’t know fully how much that might be a desirable behavior. 😕

**Comment by eikenb** [comment]
Sorry for not chiming in earlier. Catching up I find myself agreeing with @vansante's solution the most. I prefer "zero" values over nil when when you don't need nil for semantic reasons. I don't think nil conveys anything meaningful here, so the zero value makes more sense.

**Comment by vansante** [comment]
@eikenb I created a PR #328 which fixes the issue, also if the byte slice is not empty, but not large enough. It utilizes the safe unmarshal functions to just default everything to zero.
