### ISSUE TITLE
File.WriteTo implementation moved to Stat instead of FStat breaks IBM Sterling SFTP

### ISSUE THREAD

**Issue by erans** [pkg/sftp#331]
Due to #288 it seems the code of File.WriteTo was changed to use Stat instead of Fstat. That causes problems with IBM Sterling SFTP servers when extractability is set to 1.

It throws the error:
```The message [{FILENAME}] is not extractable!\" (SSH_FX_FAILURE)```

Debugging it further shows that if a certain configuration (which is very common for such SFTP servers in financial institutions) is set calling Stat after opening a file will cause it to freak out as it thinks someone tries to open/download more than 1 file at the same time.

Removing the call for Stat and just pulling the file until there are no more bytes to get seems to solve this.

We are working on a PR that will contain a ClientOption flag that will allow to control this behaviour, hopefully not breaking other servers by supporting both of these strange behaviours :-)

**Comment by erans** [comment]
Here is the pull request to allow both behaviours:
https://github.com/pkg/sftp/pull/332

**Comment by eikenb** [comment]
Hey @erans, thanks for the report  and sorry about the regression. SFTP servers and clients are all over the place in what/how they support and its an ongoing wack-a-mole to get them all happy.

I'll take a look at your PR...

**Comment by eikenb** [comment]
Forgot to add that the PR fixes this. Merged the PR so closing this as well.
