### ISSUE TITLE
Run as a subsystem behind sshd via ForceCommand

### ISSUE THREAD

**Issue by d4z3x** [pkg/sftp#336]
Hi guys,

I have some, but very little experience with subsystems. I know servers listening behind ssh judt need stdin/stdout/stderr. However, in this case, and my lack of experience with sftp servers, I was hoping someone could advise on how to use this package (where I would add some modifications) to be run via ForceCommand invocation?

I appreciate any help in advance.

Thanks!

**Comment by d4z3x** [comment]
Nevermind folks, I did get this to work just requires a few lines worth of changes. If anyone is interested, I can send a PR to make it a bit easier for otherwise along with a simple example.

**Comment by eikenb** [comment]
Hey @d4z3x,

If you get a chance you got me curious and I'd love to see what you did. Thanks.

**Comment by eikenb** [comment]
@d4z3x If you get a chance, I'd like to see those changes. But I'm going to go ahead and close this since it is resolved. Thanks.
