### ISSUE TITLE
"File does not exist" when copying remote file - SFTP client

### ISSUE THREAD

**Issue by newdayrising** [pkg/sftp#339]
I really wanted this to be a last resort, but I'm at my wits end trying to figure this out. My code is at the bottom. The main error I keep getting when using the typical configuration is "file does not exist." WinSCP has no issues.

Things I've tried:

1. Attempted the same operation using RClone to make sure my code is not the issue (see https://forum.rclone.org/t/sftp-remote-to-local-copy-failed-to-copy-file-does-not-exist/14414/2). RClone fails with the "File does not exist" error.

2. sftp.NewClient(conn) with sftpClient.Open(srcInvPath) - Received the error: "File does not exist"

3. sftp.NewClient(conn, sftp.MaxPacket(20480)) with sftpClient.OpenFile(srcInvPath, os.O_WRONLY|os.O_CREATE|os.O_TRUNC) - Received the error: "read from 13 for 20480 from 20497 not supported. (SSH_FX_FAILURE)"

4. sftp.NewClient(conn) with sftpClient.OpenFile(srcInvPath, os.O_WRONLY|os.O_CREATE|os.O_TRUNC) - Received the error: "read from 13 for 32768 from 32785 not supported. (SSH_FX_FAILURE)"

5. sftp.NewClient(conn) with sftpClient.OpenFile(srcInvPath, 0700)  - Received the error : "EOF". Have no idea why I tried this.

```go
package main

import (
	"bufio"
	"fmt"
	"io"
	"log"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/pkg/sftp"
	"golang.org/x/crypto/ssh"
)

var invImpRootPath = "C:\\Invoices\\"
var invImpErrPath = filepath.Join(invImpRootPath, "Errors")
var invImpProcPath = filepath.Join(invImpRootPath, "Processed")
var invRegExp = regexp.MustCompile(`(?m)^(Invoice)\.([0-9]*)\.([0-9]*)\.([0-9]{1,5})\.xml$`)
var sftpInvPath = "/Invoices/outbound"

func main() {
	err := os.MkdirAll(invImpRootPath, os.ModeDir)
	if err != nil {
		fmt.Printf("Error creating Invoices directory: %s", err.Error())
		panic(err)
	}

	err = os.MkdirAll(invImpErrPath, os.ModeDir)
	if err != nil {
		fmt.Printf("Error creating Errors directory: %s", err.Error())
		panic(err)
	}

	err = os.MkdirAll(invImpProcPath, os.ModeDir)
	if err != nil {
		fmt.Printf("Error creating Processed directory: %s", err.Error())
		panic(err)
	}

	user := {removed}
	pass := {removed}
	host := {removed}
	port := "22"

	hostKey := getHostKey(host)
	config := &ssh.ClientConfig{
		User: user,
		Auth: []ssh.AuthMethod{
			ssh.Password(pass),
		},
		HostKeyCallback: ssh.FixedHostKey(hostKey),
	}

	conn, err := ssh.Dial("tcp", host+":"+port, config)
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close()

	sftpClient, err := sftp.NewClient(conn, sftp.MaxPacket(20480))
	if err != nil {
		log.Fatal(err)
	}
	defer sftpClient.Close()

	files, err := sftpClient.ReadDir(sftpInvPath)
	if err != nil {
		log.Fatal(err)
	}

	for _, file := range files {
		srcInvPath := path.Join(sftpInvPath, file.Name())
		dstInvPath := filepath.Join(invImpRootPath, file.Name())

		dstFile, err := os.Create(dstInvPath)
		if err != nil {
			log.Fatal(err)
		}
		defer dstFile.Close()

		srcFile, err := sftpClient.OpenFile(srcInvPath, os.O_WRONLY|os.O_CREATE|os.O_TRUNC)
		if err != nil {
			log.Fatal(err) 
		}

		bytes, err := io.Copy(dstFile, srcFile)
		if err != nil {
			log.Fatal(err)
		}
		fmt.Printf("%d bytes copied\n", bytes)

		err = dstFile.Sync()
		if err != nil {
			log.Fatal(err)
		}
	}
}

func getHostKey(host string) ssh.PublicKey {
	// parse OpenSSH known_hosts file
	// ssh or use ssh-keyscan to get initial key
	file, err := os.Open("known_hosts")
	if err != nil {
		log.Fatal(err)
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	var hostKey ssh.PublicKey
	for scanner.Scan() {
		fields := strings.Split(scanner.Text(), " ")
		if len(fields) != 3 {
			continue
		}
		if strings.Contains(fields[0], host) {
			var err error
			hostKey, _, _, _, err = ssh.ParseAuthorizedKey(scanner.Bytes())
			if err != nil {
				log.Fatalf("error parsing %q: %v", fields[2], err)
			}
			break
		}
	}

	if hostKey == nil {
		log.Fatalf("no hostkey found for %s", host)
	}

	return hostKey
}
```
Server information from WinSCP:

![Snipaste_2020-02-19_12-34-59](https://user-images.githubusercontent.com/19381608/74859221-986db780-5314-11ea-8fae-8a65a17ee8cd.png)

![Snipaste_2020-02-19_12-34-15](https://user-images.githubusercontent.com/19381608/74859233-9c99d500-5314-11ea-8cb0-c3f3da20dbb2.png)

![Snipaste_2020-02-19_12-33-41](https://user-images.githubusercontent.com/19381608/74859244-a0c5f280-5314-11ea-8e19-ab75df62d082.png)

Thank you!

**Comment by eikenb** [comment]
Sorry for your problems. Let me grab that code and see if I can reproduce it and see what's going on.

**Comment by eikenb** [comment]
Hey @newdayrising,

I found a couple issues with your code that fixing should get you going. The main thing is how you open the source file... 

    `srcFile, err := sftpClient.OpenFile(srcInvPath, os.O_WRONLY|os.O_CREATE|os.O_TRUNC)`

Those flags `os.O_WRONLY|os.O_CREATE|os.O_TRUNC` are what you pass when you want to truncate and create a new file. But you are calling that for your source file. What you want is more along the lines..

    `srcFile, err := sftpClient.Open(srcInvPath)`

The client.Open() method is designed for read-only operations like this one. It uses the flag `os.O_RDONLY` in the open call.

The other thing was that you don't close the files properly. You close the dstFile using defer, which could queue up closing those files until they were all processed and the function exited. And you don't close the source file at all. Instead you should close both the dstFile and srcFile at the bottom of the loop block, after the Sync() call.

Note that you'll want to check your source files. The file, the one triggering the error, gets truncated (all the contents deleted) by that bad OpenFile call.

**Comment by puellanivis** [comment]
`"read from 13 for 20480 from 20497 not supported. (SSH_FX_FAILURE)"` This is saying that you cannot read from a file that you opened with `O_WRONLY`.

I’m not entirely sure what could be going wrong here. But rclone seems to be suffering from the same problem. Do you get the same problem if you try `scp` or `sftp` itself?

**Comment by andrecunhas** [comment]
Hello, I am facing the same issue.

I have follow @eikenb tips but I still have the same problem:

I am using Open and close my srcFile and dstFile after sync but I still get "file does not exist"

`srcFile, err := sftpClient.Open(srcInvPath)`

ps: If I put the file in sftp myself I can copy it, but when an external system put the file I got this errors. I have checked both my file and the external system one have same permission...

Any ideas? I am stuck in this for days

Thank you very much

**Comment by puellanivis** [comment]
Wha?! That sounds really weird.

Could you provide some kind of `ls -l` for both making it in sftp yourself and the external system making it?

Also, what information do you have about the server this being run against? Don’t care much about settings, etc, but rather what implementation is it, and version?

**Comment by andrecunhas** [comment]
@puellanivis I will try to get this information

My guess is that my file is locked by another application so I cannot find it. This sounds right for you?

**Comment by puellanivis** [comment]
🤷‍♀ There are a lot of weird reasons why it might happen. But without knowing any more details, it’s not really something we will be able to look at.

**Comment by eikenb** [comment]
> ps: If I put the file in sftp myself I can copy it, but when an external system put the file I got this errors. I have checked both my file and the external system one have same permission...

I'd focus on trying to figure out what is different between the files on the server when you upload it vs. when the external system uploads it. There *must* be some difference. You could use `ls -l` type functionality in your favorite client or `stat` them using this library's client.Stat() method.

> My guess is that my file is locked by another application so I cannot find it.

File locks are implemented in the application. So for them to be an issue the SFTP server would need to support them and I'm not aware of any SFTP server that does. Also file locks are used to limit write access, not read access.

I'd focus on permissions and ownership issues.

**Comment by eikenb** [comment]
@newdayrising .. Have you had any  luck figuring this out on your end? Was my reply helpful at all? Hoping you're quiet as you've got it working and so stopped paying attention here.

**Comment by newdayrising** [comment]
> 
> 
> @newdayrising .. Have you had any luck figuring this out on your end? Was my reply helpful at all? Hoping you're quiet as you've got it working and so stopped paying attention here.

Sorry about the delay in my response. I've been working with @ncw over in the RClone forums. He believes this is a symlink issue. I wish I could confirm, but the third party hosting the SFTP server is very coy about providing server details - the told me to "just use WinSCP."

I provided Nick with the log of an SFTP app I use on Android (I was mobile at the time):

> 2020/02/29 20:23 Creating session to server:22...
> 2020/02/29 20:23 Session has been created successfully.
> 2020/02/29 20:23 Adding password identity...
> 2020/02/29 20:23 Authorizing as user.
> 2020/02/29 20:23 Connecting...
> 2020/02/29 20:23 Connected successfully!
> 2020/02/29 20:23 Opening channel...
> 2020/02/29 20:23 Channel has been opened.
> 2020/02/29 20:23 CWD: /BK
> 2020/02/29 20:23 CWD command successful.
> 2020/02/29 20:23 CWD: /SEVENREST
> 2020/02/29 20:23 CWD command successful.
> 2020/02/29 20:23 CWD: /outbound
> 2020/02/29 20:23 CWD command successful.
> 2020/02/29 20:23 LIST
> 2020/02/29 20:23 LIST command successful.
> 2020/02/29 20:23 DOWNLOAD ./test.txt to /storage/emulated/0/Download
> 2020/02/29 20:23 DOWNLOAD command successful.
> 2020/02/29 20:24 LIST
> 2020/02/29 20:24 LIST command successful.
> 2020/02/29 20:24 DOWNLOAD ./McLaneFS-C.20200227131245.0062821035.26446.xml to /storage/emulated/0/Download
> 2020/02/29 20:24 DOWNLOAD command successful.

His response was this:

> I can see that that app uses a changing to the current directory approach - rclone uses a path based approach so that might make the difference.
> 
> I still suspect symlinks might be making the difference...

I've provided further output per his direction and I'm waiting on a response.

Thank you!

**Comment by ncw** [comment]
I didn't realise there was a thread here too!

Looking at the debug supplied I can see exactly where the error message is returned. The file is opened correctly (so my conjectures about symlinks and directory paths were incorrect), however the error is returned from `io.Copy`

    2020/03/01 16:35:58 ERROR : file.xml: Failed to send to output: file does not exist

https://github.com/rclone/rclone/blob/38a4d50e73060e1b486de6dc0caba68fa0a0c0a0/fs/operations/operations.go#L1301

```go
		_, err = io.Copy(w, in)
		if err != nil {
			err = fs.CountError(err)
			fs.Errorf(o, "Failed to send to output: %v", err)
		}
```

I'd say returning "File does not exist" from `io.Copy` is a bit strange... I don't know whether that is coming from the library or from the remote end - is there debug I can turn on in pkg/sftp to show that? I grepped/examined pkg/sftp and I think it is probably coming from the remote end.

The file is opened here in read only mode.

https://github.com/rclone/rclone/blob/38a4d50e73060e1b486de6dc0caba68fa0a0c0a0/backend/sftp/sftp.go#L1194

**Comment by andrecunhas** [comment]
Hello @puellanivis and @eikenb, thank you for your help, I was not able to post more details, something was blocking me from posting. 

Anyways, after some attempts, I decided to rewrite my code and finally solved my issue!
I based my new code in this example [here]( https://github.com/pkg/sftp/blob/master/examples/streaming-read-benchmark/main.go)
the differences from this code to my new code is that I am copying a specific file, 

In order to this to work, at line 61 I am using my role path with the file name

`r, err := c.Open("/dev/zero/myfile.txt")`

Before line 67 I added
`os.Create(destinationPath)`

And I put my role path in the destination as well
`w, err := os.OpenFile(destinationPath, syscall.O_WRONLY, 0600)`

**Comment by newdayrising** [comment]
> I didn't realise there was a thread here too!
> 
> Looking at the debug supplied I can see exactly where the error message is returned. The file is opened correctly (so my conjectures about symlinks and directory paths were incorrect), however the error is returned from `io.Copy`
> 
> ```
> 2020/03/01 16:35:58 ERROR : file.xml: Failed to send to output: file does not exist
> ```
> 
> https://github.com/rclone/rclone/blob/38a4d50e73060e1b486de6dc0caba68fa0a0c0a0/fs/operations/operations.go#L1301
> 
> ```go
> 		_, err = io.Copy(w, in)
> 		if err != nil {
> 			err = fs.CountError(err)
> 			fs.Errorf(o, "Failed to send to output: %v", err)
> 		}
> ```
> 
> I'd say returning "File does not exist" from `io.Copy` is a bit strange... I don't know whether that is coming from the library or from the remote end - is there debug I can turn on in pkg/sftp to show that? I grepped/examined pkg/sftp and I think it is probably coming from the remote end.
> 
> The file is opened here in read only mode.
> 
> https://github.com/rclone/rclone/blob/38a4d50e73060e1b486de6dc0caba68fa0a0c0a0/backend/sftp/sftp.go#L1194

@eikenb Any ideas? It looks like this was investigated at one point but the user gave up: https://github.com/pkg/sftp/issues/212.

**Comment by andrecunhas** [comment]
@newdayrising Hello, I think you should try this, it solved my issue:
In your destination you user only `os.Create`, add a line to `OpenFile` as well

```
os.Create(dstInvPath)
w, err := os.OpenFile(dstInvPath, syscall.O_WRONLY, 0600)
```

**Comment by puellanivis** [comment]
`os.Create(dstInvPath)`should return an `*os.File` that you can write to, without also having to use `osOpenFile(dstInvPath, …)`. In fact, if you do not close this file, you’re likely to end up leaking file descriptors.

**Comment by newdayrising** [comment]
@puellanivis @eikenb  I think I need to be able to CD into the directory. I'm attempting to do this using the code below, but the command keeps failing.

err = sess.Run("cd /BK/SEVENREST/outbound")
	if err != nil {
		log.Fatal(err)
	}

I'm not sure how to proceed. Any tips on how to cd into the directory?

**Comment by newdayrising** [comment]
Please ignore the last comment. From what I'm reading there is no concept of changing a directory in the SSH protocol.

I'm attaching a detailed WinSCP log.
[winscp log.txt](https://github.com/pkg/sftp/files/4300357/winscp.log.txt)

**Comment by eikenb** [comment]
>  From what I'm reading there is no concept of changing a directory in the SSH protocol.

Yep. All 'cd' like functionality in SFTP comes from the client. The server has no such concept.

> @eikenb Any ideas? It looks like this was investigated at one point but the user gave up: #212.

Re-reading through #212 I'm curious if you might try what setting a lower MaxPacket as I suggest here, https://github.com/pkg/sftp/issues/212#issuecomment-354929733. The problems that people had in #212 were all unrelated to that but maybe it is relevant here...

Also reading through that thread made me wonder if you can possibly test it with OpenSSH's sftp client. If that works we can use it for more ideas like above as it is pretty straightforward C that is well commented and easy to read.... so makes for a good reference.

**Comment by newdayrising** [comment]
@eikenb @puellanivis @ncw 

OK. Got a big piece of information after some troubleshooting. **I also found that the Paramiko Python library downloads the files without issue.**

When testing using Paramiko I noticed the files were being deleted. So I sent an email to the third party company inquiring how/why the files were being deleted. 

I was informed that the server is an "SFTP mailbox" server. After some research, probably IBM Sterling. 

I found this commit/discussion:
https://github.com/pkg/sftp/pull/332/files/09f03e7bff7c927325abf0e6cd2f8ec4961a296d

> It has been found that that with IBM Sterling SFTP servers which have "extractability" level set to 1 which means only 1 file can be opened at any given time.
> 
> If the server you are working with still has an issue with both Stat and Fstat calls you can always open a file and read it until the end.
> 
> Another reason to read the file until its end and Fstat doesn't work is that in some servers, reading a full file will automatically delete the file as some of these mainframes map the file to a message in a queue. Once the file has been read it will get deleted.
> 

I'm slightly confused, am I supposed to use sftp.UseFstat(true), or some other method? When I use  UseFstat(true) I then get the error:
> The message [{filename}] is not extractable!" (SSH_FX_FAILURE)

I found this guide that looks like it could be of use, but I'm still at a loss:
https://www.ibm.com/support/pages/troubleshooting-guide-why-does-sb2bi-sftp-server-adapter-reports-message-not-extractable-error-when-extractabilitycount1

Python code:
```Python
import os
import paramiko 
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect('server', username="user", password="pass")
sftp = ssh.open_sftp()
cat = sftp.listdir(path=os.path.dirname('/BK/SEVENREST/outbound/'))
print(cat)
localpath = 'invoice.xml'
remotepath = '/BK/SEVENREST/outbound/invoice.xml'
sftp.get(remotepath, localpath)
sftp.close()
ssh.close()
```
Here's where they had a discussion about the same issue with Paramiko: https://github.com/paramiko/paramiko/issues/194

**Comment by newdayrising** [comment]
@puellanivis I see that you've dealt with a similar issue with the Paramiko library here: https://github.com/pkg/sftp/pull/206

**Comment by puellanivis** [comment]
So, I didn’t deal with it, but yeah, reading your post I was like, “ugh, again?”

I don’t think I’m still sure about what a work around or fix would look like. :(

**Comment by newdayrising** [comment]
Finally figured this out.

I had to use a combination of the option "sftp.UseFstat(true)" and io.Copy() when copying the file. "sftp.Writeto()" would not work, I think because of the extra stat calls? I'm not sure.

An example of the code:
```go
package main
import (
	"bufio"
	"fmt"
	"io"
	"log"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/pkg/sftp"
	"golang.org/x/crypto/ssh"
)

func main() {
	user := "funuser"
	pass := "coolpasswd"
	host := "niceserver"
	port := "22"

	hostKey := getHostKey(host)
	config := &ssh.ClientConfig{
		User: user,
		Auth: []ssh.AuthMethod{
			ssh.Password(pass),
		},
		HostKeyCallback: ssh.FixedHostKey(hostKey),
	}

	conn, err := ssh.Dial("tcp", host+":"+port, config)
	if err != nil {
		log.Fatal(err) //TODO update error
	}
	defer conn.Close()

	sftpClient, err := sftp.NewClient(conn, sftp.UseFstat(true))
	if err != nil {
		log.Fatal(err) ///TODO update error
	}
	defer sftpClient.Close()

	files, err := sftpClient.ReadDir(sftpInvPath)
	if err != nil {
		log.Fatal(err) //TODO update error
	}

	for _, file := range files {
		fileNameMatch := invRegExp.FindAllStringSubmatch(file.Name(), -1)

		if fileNameMatch != nil {

			srcInvPath := path.Join(sftpInvPath, file.Name())
			dstInvPath := filepath.Join(invImpRootPath, file.Name())

			dstFile, err := os.Create(dstInvPath)
			if err != nil {
				log.Fatal(err) //TODO update err
			}
			defer dstFile.Close()

			srcFile, err := sftpClient.Open(srcInvPath)
			if err != nil {
				log.Fatal(err) //TODO update err
			}

			bytes, err := io.Copy(dstFile, srcFile)
			if err != nil {
				log.Fatal(err) //TODO update error
			}
			fmt.Printf("%d bytes copied\n", bytes)

			err = dstFile.Sync()
			if err != nil {
				log.Fatal(err) //TODO update error
			}
		}
	}
}

func getHostKey(host string) ssh.PublicKey {
	file, err := os.Open("known_hosts")
	if err != nil {
		log.Fatal(err)
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	var hostKey ssh.PublicKey
	for scanner.Scan() {
		fields := strings.Split(scanner.Text(), " ")
		if len(fields) != 3 {
			continue
		}
		if strings.Contains(fields[0], host) {
			var err error
			hostKey, _, _, _, err = ssh.ParseAuthorizedKey(scanner.Bytes())
			if err != nil {
				log.Fatalf("error parsing %q: %v", fields[2], err)
			}
			break
		}
	}

	if hostKey == nil {
		log.Fatalf("no hostkey found for %s", host)
	}

	return hostKey
}
```

**Comment by newdayrising** [comment]
@puellanivis @eikenb @ncw 

Finally figured this out.

The issue is the stat/fstat call in the WriteTo method, particularly *while the file is open*. Stat calls can occur as long as the file is not already open. I call sftpClient.Lstat() on the file before opening it and then pass the file size obtained into the modified WriteTo method. If someone could provide insight into the validity of my code below that would be helpful. Is it safe to grab the file size and pass it into the WriteTo method before the file is opened? 

Modified WriteTo method. I pass in the fileSize from the sftpClient.Lstat() call in my code:

```go
func (f *File) WriteTo(w io.Writer, fileSize uint64) (int64, error) {
	inFlight := 0
	desiredInFlight := 1
	offset := f.offset
	writeOffset := offset
	// see comment on same line in Read() above
	ch := make(chan result, f.c.maxConcurrentRequests+1)
	type inflightRead struct {
		b      []byte
		offset uint64
	}
	reqs := map[uint32]inflightRead{}
	pendingWrites := map[uint64][]byte{}
	type offsetErr struct {
		offset uint64
		err    error
	}
	var firstErr offsetErr

	sendReq := func(b []byte, offset uint64) {
		reqID := f.c.nextID()
		f.c.dispatchRequest(ch, sshFxpReadPacket{
			ID:     reqID,
			Handle: f.handle,
			Offset: offset,
			Len:    uint32(len(b)),
		})
		inFlight++
		reqs[reqID] = inflightRead{b: b, offset: offset}
	}

	var copied int64
	for firstErr.err == nil || inFlight > 0 {
		if firstErr.err == nil {
			for inFlight+len(pendingWrites) < desiredInFlight {
				b := make([]byte, f.c.maxPacket)
				sendReq(b, offset)
				offset += uint64(f.c.maxPacket)
				if offset > fileSize {
					desiredInFlight = 1
				}
			}
		}

		if inFlight == 0 {
			if firstErr.err == nil && len(pendingWrites) > 0 {
				return copied, ErrInternalInconsistency
			}
			break
		}
		res := <-ch
		inFlight--
		if res.err != nil {
			firstErr = offsetErr{offset: 0, err: res.err}
			continue
		}
		reqID, data := unmarshalUint32(res.data)
		req, ok := reqs[reqID]
		if !ok {
			firstErr = offsetErr{offset: 0, err: errors.Errorf("sid: %v not found", reqID)}
			continue
		}
		delete(reqs, reqID)
		switch res.typ {
		case sshFxpStatus:
			if firstErr.err == nil || req.offset < firstErr.offset {
				firstErr = offsetErr{offset: req.offset, err: normaliseError(unmarshalStatus(reqID, res.data))}
			}
		case sshFxpData:
			l, data := unmarshalUint32(data)
			if req.offset == writeOffset {
				nbytes, err := w.Write(data)
				copied += int64(nbytes)
				if err != nil {
					// We will never receive another DATA with offset==writeOffset, so
					// the loop will drain inFlight and then exit.
					firstErr = offsetErr{offset: req.offset + uint64(nbytes), err: err}
					break
				}
				if nbytes < int(l) {
					firstErr = offsetErr{offset: req.offset + uint64(nbytes), err: io.ErrShortWrite}
					break
				}
				switch {
				case offset > fileSize:
					desiredInFlight = 1
				case desiredInFlight < f.c.maxConcurrentRequests:
					desiredInFlight++
				}
				writeOffset += uint64(nbytes)
				for {
					pendingData, ok := pendingWrites[writeOffset]
					if !ok {
						break
					}
					// Give go a chance to free the memory.
					delete(pendingWrites, writeOffset)
					nbytes, err := w.Write(pendingData)
					// Do not move writeOffset on error so subsequent iterations won't trigger
					// any writes.
					if err != nil {
						firstErr = offsetErr{offset: writeOffset + uint64(nbytes), err: err}
						break
					}
					if nbytes < len(pendingData) {
						firstErr = offsetErr{offset: writeOffset + uint64(nbytes), err: io.ErrShortWrite}
						break
					}
					writeOffset += uint64(nbytes)
				}
			} else {
				// Don't write the data yet because
				// this response came in out of order
				// and we need to wait for responses
				// for earlier segments of the file.
				pendingWrites[req.offset] = data
			}
		default:
			firstErr = offsetErr{offset: 0, err: unimplementedPacketErr(res.typ)}
		}
	}
	if firstErr.err != io.EOF {
		return copied, firstErr.err
	}
	return copied, nil
}

```

An example of the code:


```go

package main
import (
	"bufio"
	"fmt"
	"io"
	"log"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"github.com/pkg/sftp"
	"golang.org/x/crypto/ssh"
)

func main() {
	user := "funuser"
	pass := "coolpasswd"
	host := "niceserver"
	port := "22"

	hostKey := getHostKey(host)
	config := &ssh.ClientConfig{
		User: user,
		Auth: []ssh.AuthMethod{
			ssh.Password(pass),
		},
		HostKeyCallback: ssh.FixedHostKey(hostKey),
	}

	conn, err := ssh.Dial("tcp", host+":"+port, config)
	if err != nil {
		log.Fatal(err) //TODO update error
	}
	defer conn.Close()

	sftpClient, err := sftp.NewClient(conn, sftp.UseFstat(true))
	if err != nil {
		log.Fatal(err) ///TODO update error
	}
	defer sftpClient.Close()

	files, err := sftpClient.ReadDir(sftpInvPath)
	if err != nil {
		log.Fatal(err) //TODO update error
	}

	for _, file := range files {
		fileNameMatch := invRegExp.FindAllStringSubmatch(file.Name(), -1)

		if fileNameMatch != nil {

			srcInvPath := path.Join(sftpInvPath, file.Name())
			dstInvPath := filepath.Join(invImpRootPath, file.Name())

			dstFile, err := os.Create(dstInvPath)
			if err != nil {
				log.Fatal(err) //TODO update err
			}
			defer dstFile.Close()

			fileStat, err := sftpClient.Lstat(srcInvPath)
			if err != nil {
				log.Fatal(err)
			}

			srcFile, err := sftpClient.Open(srcInvPath)
			if err != nil {
				log.Fatal(err) //TODO update err
			}

			bytes, err := srcFile.WriteTo(dstFile, uint64(fileStat.Size()))
			if err != nil {
				log.Fatal(err) //TODO update error
			}
			fmt.Printf("%d bytes copied\n", bytes)

			err = dstFile.Sync()
			if err != nil {
				log.Fatal(err) //TODO update error
			}
		}
	}
}

func getHostKey(host string) ssh.PublicKey {
	file, err := os.Open("known_hosts")
	if err != nil {
		log.Fatal(err)
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	var hostKey ssh.PublicKey
	for scanner.Scan() {
		fields := strings.Split(scanner.Text(), " ")
		if len(fields) != 3 {
			continue
		}
		if strings.Contains(fields[0], host) {
			var err error
			hostKey, _, _, _, err = ssh.ParseAuthorizedKey(scanner.Bytes())
			if err != nil {
				log.Fatalf("error parsing %q: %v", fields[2], err)
			}
			break
		}
	}

	if hostKey == nil {
		log.Fatalf("no hostkey found for %s", host)
	}

	return hostKey
}
```

**Comment by puellanivis** [comment]
You want a `dstFile.Close` instead of the `dstFile.Sync` in your loop, and do not actually defer the `Close`.

Modifying the `WriteTo` signature in general is going to be a no-go, because we need it to implement [io.WriterTo](https://golang.org/pkg/io/#WriterTo).

The documentation for https://pkg.go.dev/github.com/pkg/sftp?tab=doc#UseFstat should give you an answer of what to do here: you should read the file in full: `data, err := ioutil.ReadAll(…)` and then write it to the local file. This will of course take up more memory, and if the file is big enough, might cause serious issues with memory ballooning, but it’s at least something that might work for you.

**Comment by newdayrising** [comment]
@puellanivis I knew I could read the file buffered or in-full. I wanted to use the preferred method. I'm not sure how this all relates to "high latency" but there have been issues with this corporate SFTP server in the past.

**Comment by puellanivis** [comment]
To be clear: changing the signature of `WriteTo` is not going to be the “preferred method”. And in this case, reading the whole file is basically the preferred (and recommended) method.

**Comment by newdayrising** [comment]
@eikenb @puellanivis @andrecunhas 
Thanks everyone. I'll go ahead and close this!

@ncw 
You may want to include an option in Rclone to accommodate these types of servers. When researching I saw a lot of similar issues with other languages. Most people just give up and use software. These servers are very common in the corporate financial sector. 

Of course not a lot of people will want to read entire files into memory and I wish this library would be updated to reflect that (like Paramiko), but it's something.
