### ISSUE TITLE
Licensing and reuse

### ISSUE THREAD

**Issue by ezbercih** [pkg/sftp#34]
I am working on implementing a simple SFTP server and I would like to reuse the types and marshaling logic in the code. But since they are not exported, I have no choice but to copy them in my own package. How does the licensing clause apply to this condition? Do I copy the LICENSE file in my repo as well?

**Comment by davecheney** [comment]
I cannot help you with that, IANAL. As far as I'm concerned you can do whatever the heck you like with this code, that is what I believe open source means.
