### ISSUE TITLE
support Chinese folder name or filename?

### ISSUE THREAD

**Issue by leffss** [pkg/sftp#346]
can it support Chinese folder name or filename?

**Comment by drakkan** [comment]
yes it should work, please try it yourself using one of the provided [sample](https://github.com/pkg/sftp/tree/master/examples), thanks

**Comment by leffss** [comment]
> yes it should work, please try it yourself using one of the provided [sample](https://github.com/pkg/sftp/tree/master/examples), thanks

i test the sample, it did not work well for chinese folder name or filename

![1585645832(1)](https://user-images.githubusercontent.com/49055524/78008788-acc0bd80-7372-11ea-9349-a9a925b2dc19.jpg)

**Comment by puellanivis** [comment]
You need to be sure that you have converted the filename to UTF-8 before you try and use it. If your local filesystem is reporting the name in a different encoding, then Go code will not handle it well.

**Comment by leffss** [comment]
> You need to be sure that you have converted the filename to UTF-8 before you try and use it. If your local filesystem is reporting the name in a different encoding, then Go code will not handle it well.

yes, i know this. my os is windows 7 in chinese so the default code is gbk. i want use this package to run a sftp server, but it could not let me converted the filename before use it ...

**Comment by drakkan** [comment]
It seems to work for me, can you please provide a  test program that reproduce the issue? thanks

**Comment by leffss** [comment]
> It seems to work for me, can you please provide a test program that reproduce the issue? thanks

my code:
```
// An example SFTP server implementation using the golang SSH package.
// Serves the whole filesystem visible to the user, and has a hard-coded username and password,
// so not for real use!
package main

import (
	"flag"
	"fmt"
	"io"
	"io/ioutil"
	"log"
	"net"
	"os"

	"github.com/pkg/sftp"
	"golang.org/x/crypto/ssh"
)

// Based on example server code from golang.org/x/crypto/ssh and server_standalone
func main() {

	var (
		readOnly    bool
		debugStderr bool
	)

	flag.BoolVar(&readOnly, "R", false, "read-only server")
	flag.BoolVar(&debugStderr, "e", false, "debug to stderr")
	flag.Parse()

	debugStream := ioutil.Discard
	if debugStderr {
		debugStream = os.Stderr
	}

	// An SSH server is represented by a ServerConfig, which holds
	// certificate details and handles authentication of ServerConns.
	config := &ssh.ServerConfig{
		PasswordCallback: func(c ssh.ConnMetadata, pass []byte) (*ssh.Permissions, error) {
			// Should use constant-time compare (or better, salt+hash) in
			// a production setting.
			fmt.Fprintf(debugStream, "Login: %s\n", c.User())
			if c.User() == "root" && string(pass) == "123456" {
				return nil, nil
			}
			return nil, fmt.Errorf("password rejected for %q", c.User())
		},
	}

	privateBytes, err := ioutil.ReadFile("ssh_proxy_rsa.key")
	if err != nil {
		log.Fatal("Failed to load private key", err)
	}

	private, err := ssh.ParsePrivateKey(privateBytes)
	if err != nil {
		log.Fatal("Failed to parse private key", err)
	}

	config.AddHostKey(private)

	// Once a ServerConfig has been configured, connections can be
	// accepted.
	listener, err := net.Listen("tcp", "0.0.0.0:2022")
	if err != nil {
		log.Fatal("failed to listen for connection", err)
	}
	fmt.Printf("Listening on %v\n", listener.Addr())

	nConn, err := listener.Accept()
	if err != nil {
		log.Fatal("failed to accept incoming connection", err)
	}

	// Before use, a handshake must be performed on the incoming
	// net.Conn.
	_, chans, reqs, err := ssh.NewServerConn(nConn, config)
	if err != nil {
		log.Fatal("failed to handshake", err)
	}
	fmt.Fprintf(debugStream, "SSH server established\n")

	// The incoming Request channel must be serviced.
	go ssh.DiscardRequests(reqs)

	// Service the incoming Channel channel.
	for newChannel := range chans {
		// Channels have a type, depending on the application level
		// protocol intended. In the case of an SFTP session, this is "subsystem"
		// with a payload string of "<length=4>sftp"
		fmt.Fprintf(debugStream, "Incoming channel: %s\n", newChannel.ChannelType())
		if newChannel.ChannelType() != "session" {
			newChannel.Reject(ssh.UnknownChannelType, "unknown channel type")
			fmt.Fprintf(debugStream, "Unknown channel type: %s\n", newChannel.ChannelType())
			continue
		}
		channel, requests, err := newChannel.Accept()
		if err != nil {
			log.Fatal("could not accept channel.", err)
		}
		fmt.Fprintf(debugStream, "Channel accepted\n")

		// Sessions have out-of-band requests such as "shell",
		// "pty-req" and "env".  Here we handle only the
		// "subsystem" request.
		go func(in <-chan *ssh.Request) {
			for req := range in {
				fmt.Fprintf(debugStream, "Request: %v\n", req.Type)
				ok := false
				switch req.Type {
				case "subsystem":
					fmt.Fprintf(debugStream, "Subsystem: %s\n", req.Payload[4:])
					if string(req.Payload[4:]) == "sftp" {
						ok = true
					}
				}
				fmt.Fprintf(debugStream, " - accepted: %v\n", ok)
				req.Reply(ok, nil)
			}
		}(requests)

		serverOptions := []sftp.ServerOption{
			sftp.WithDebug(debugStream),
		}

		if readOnly {
			serverOptions = append(serverOptions, sftp.ReadOnly())
			fmt.Fprintf(debugStream, "Read-only server\n")
		} else {
			fmt.Fprintf(debugStream, "Read write server\n")
		}

		//root := sftp.InMemHandler()
		//server := sftp.NewRequestServer(channel, root)

		server, err := sftp.NewServer(
			channel,
			serverOptions...,
		)

		if err != nil {
			log.Fatal(err)
		}

		if err := server.Serve(); err == io.EOF {
			server.Close()
			log.Print("sftp client exited session.")
		} else if err != nil {
			log.Fatal("sftp server completed with error:", err)
		}
	}
}
```
thinks!

**Comment by drakkan** [comment]
Hi,

I executed you code this way:

```
go run main.go
```

then from another shell I connected to the server

```
sftp -P 2022 root@127.0.0.1
root@127.0.0.1's password: 
Connected to 127.0.0.1.
sftp> ls
main.go             ssh_proxy_rsa.key   测试文件名     
sftp> get 测试文件名 /tmp/
Fetching /tmp/aa/测试文件名 to /tmp/测试文件名
/tmp/aa/测试文件名                       100% 4033     2.6MB/s   00:00    
sftp> quit
```

this is basically the same test I did before. I have no chinese keyboard so I copy and pasted the filename from internet and I'm sure that the filename is UTF-8 encoded

**Comment by leffss** [comment]
> Hi,
> 
> I executed you code this way:
> 
> ```
> go run main.go
> ```
> 
> then from another shell I connected to the server
> 
> ```
> sftp -P 2022 root@127.0.0.1
> root@127.0.0.1's password: 
> Connected to 127.0.0.1.
> sftp> ls
> main.go             ssh_proxy_rsa.key   测试文件名     
> sftp> get 测试文件名 /tmp/
> Fetching /tmp/aa/测试文件名 to /tmp/测试文件名
> /tmp/aa/测试文件名                       100% 4033     2.6MB/s   00:00    
> sftp> quit
> ```
> 
> this is basically the same test I did before. I have no chinese keyboard so I copied and pasted the filename and I'm sure that the filename is UTF-8 encoded.
> 
> I also tested from winscp and it seems fine there too:
> 
> ![winscp](https://user-images.githubusercontent.com/553263/78135082-8b6ada80-7421-11ea-911a-a28abb2c91c5.png)
> 
> so I'm unable to reproduce, sorry

thinks, i just found other way to slove it.

> Hi,
> 
> I executed you code this way:
> 
> ```
> go run main.go
> ```
> 
> then from another shell I connected to the server
> 
> ```
> sftp -P 2022 root@127.0.0.1
> root@127.0.0.1's password: 
> Connected to 127.0.0.1.
> sftp> ls
> main.go             ssh_proxy_rsa.key   测试文件名     
> sftp> get 测试文件名 /tmp/
> Fetching /tmp/aa/测试文件名 to /tmp/测试文件名
> /tmp/aa/测试文件名                       100% 4033     2.6MB/s   00:00    
> sftp> quit
> ```
> 
> this is basically the same test I did before. I have no chinese keyboard so I copied and pasted the filename and I'm sure that the filename is UTF-8 encoded.
> 
> I also tested from winscp and it seems fine there too:
> 
> ![winscp](https://user-images.githubusercontent.com/553263/78135082-8b6ada80-7421-11ea-911a-a28abb2c91c5.png)
> 
> so I'm unable to reproduce, sorry

Thanks. I've found another way to solve it.

I have a question about the SFTP protocol. According to the description of https://tools.ietf.org/html/draft-ietf-secsh-filexfer-02, when the SFTP server send SSH_FXP_NAME packets to the SFTP Client, it just contains the filename, longname, attrs, and the attrs does not contain the file type, so how does the SFTP Client to know that the file is a normal file, directory or link? Via longname? How?

**Comment by leffss** [comment]
> Hi,
> 
> I executed you code this way:
> 
> ```
> go run main.go
> ```
> 
> then from another shell I connected to the server
> 
> ```
> sftp -P 2022 root@127.0.0.1
> root@127.0.0.1's password: 
> Connected to 127.0.0.1.
> sftp> ls
> main.go             ssh_proxy_rsa.key   测试文件名     
> sftp> get 测试文件名 /tmp/
> Fetching /tmp/aa/测试文件名 to /tmp/测试文件名
> /tmp/aa/测试文件名                       100% 4033     2.6MB/s   00:00    
> sftp> quit
> ```
> 
> this is basically the same test I did before. I have no chinese keyboard so I copied and pasted the filename and I'm sure that the filename is UTF-8 encoded.
> 
> I also tested from winscp and it seems fine there too:
> 
> ![winscp](https://user-images.githubusercontent.com/553263/78135082-8b6ada80-7421-11ea-911a-a28abb2c91c5.png)
> 
> so I'm unable to reproduce, sorry

Thanks. I've found another way to solve it.

I have a question about the SFTP protocol. According to the description of https://tools.ietf.org/html/draft-ietf-secsh-filexfer-02, when the SFTP server send SSH_FXP_NAME packets to the SFTP Client, it just contains the filename, longname, attrs, and the attrs does not contain the file type, so how does the SFTP Client to know that the file is a normal file, directory or link? Via longname? How?

**Comment by leffss** [comment]
> > Hi,
> > I executed you code this way:
> > ```
> > go run main.go
> > ```
> > 
> > 
> > then from another shell I connected to the server
> > ```
> > sftp -P 2022 root@127.0.0.1
> > root@127.0.0.1's password: 
> > Connected to 127.0.0.1.
> > sftp> ls
> > main.go             ssh_proxy_rsa.key   测试文件名     
> > sftp> get 测试文件名 /tmp/
> > Fetching /tmp/aa/测试文件名 to /tmp/测试文件名
> > /tmp/aa/测试文件名                       100% 4033     2.6MB/s   00:00    
> > sftp> quit
> > ```
> > 
> > 
> > this is basically the same test I did before. I have no chinese keyboard so I copied and pasted the filename and I'm sure that the filename is UTF-8 encoded.
> > I also tested from winscp and it seems fine there too:
> > ![winscp](https://user-images.githubusercontent.com/553263/78135082-8b6ada80-7421-11ea-911a-a28abb2c91c5.png)
> > so I'm unable to reproduce, sorry
> 
> Thanks. I've found another way to solve it.
> 
> I have a question about the SFTP protocol. According to the description of https://tools.ietf.org/html/draft-ietf-secsh-filexfer-02, when the SFTP server send SSH_FXP_NAME packets to the SFTP Client, it just contains the filename, longname, attrs, and the attrs does not contain the file type, so how does the SFTP Client to know that the file is a normal file, directory or link? Via longname? How?

thinks, i just found the answer.

**Comment by drakkan** [comment]
> > Hi,
> > I executed you code this way:
> > ```
> > go run main.go
> > ```
> > 
> > 
> > then from another shell I connected to the server
> > ```
> > sftp -P 2022 root@127.0.0.1
> > root@127.0.0.1's password: 
> > Connected to 127.0.0.1.
> > sftp> ls
> > main.go             ssh_proxy_rsa.key   测试文件名     
> > sftp> get 测试文件名 /tmp/
> > Fetching /tmp/aa/测试文件名 to /tmp/测试文件名
> > /tmp/aa/测试文件名                       100% 4033     2.6MB/s   00:00    
> > sftp> quit
> > ```
> > 
> > 
> > this is basically the same test I did before. I have no chinese keyboard so I copied and pasted the filename and I'm sure that the filename is UTF-8 encoded.
> > I also tested from winscp and it seems fine there too:
> > ![winscp](https://user-images.githubusercontent.com/553263/78135082-8b6ada80-7421-11ea-911a-a28abb2c91c5.png)
> > so I'm unable to reproduce, sorry
> 
> Thanks. I've found another way to solve it.

Great! I think it could be helpful for other users if you could share the solution. Based on your solution we can also understand if we have to improve something in pkg/sftp to better support your use case, thanks

> 
> I have a question about the SFTP protocol. According to the description of https://tools.ietf.org/html/draft-ietf-secsh-filexfer-02, when the SFTP server send SSH_FXP_NAME packets to the SFTP Client, it just contains the filename, longname, attrs, and the attrs does not contain the file type, so how does the SFTP Client to know that the file is a normal file, directory or link? Via longname? How?

**Comment by leffss** [comment]
> > > Hi,
> > > I executed you code this way:
> > > ```
> > > go run main.go
> > > ```
> > > 
> > > 
> > > then from another shell I connected to the server
> > > ```
> > > sftp -P 2022 root@127.0.0.1
> > > root@127.0.0.1's password: 
> > > Connected to 127.0.0.1.
> > > sftp> ls
> > > main.go             ssh_proxy_rsa.key   测试文件名     
> > > sftp> get 测试文件名 /tmp/
> > > Fetching /tmp/aa/测试文件名 to /tmp/测试文件名
> > > /tmp/aa/测试文件名                       100% 4033     2.6MB/s   00:00    
> > > sftp> quit
> > > ```
> > > 
> > > 
> > > this is basically the same test I did before. I have no chinese keyboard so I copied and pasted the filename and I'm sure that the filename is UTF-8 encoded.
> > > I also tested from winscp and it seems fine there too:
> > > ![winscp](https://user-images.githubusercontent.com/553263/78135082-8b6ada80-7421-11ea-911a-a28abb2c91c5.png)
> > > so I'm unable to reproduce, sorry
> > 
> > 
> > Thanks. I've found another way to solve it.
> 
> Great! I think it could be helpful for other users if you could share the solution. Based on your solution we can also understand if we have to improve something in pkg/sftp to better support your use case, thanks
> 
> > I have a question about the SFTP protocol. According to the description of https://tools.ietf.org/html/draft-ietf-secsh-filexfer-02, when the SFTP server send SSH_FXP_NAME packets to the SFTP Client, it just contains the filename, longname, attrs, and the attrs does not contain the file type, so how does the SFTP Client to know that the file is a normal file, directory or link? Via longname? How?

I use `github.com/taruti/sftpd` instead of `github.com/pkg/sftp` to run the SFTP server, because I like its filesystem interface design. `github.com/taruti/sftpd` does not support Chinese filename either. so i modified it. My solution may only be suitable for Chinese encoding. When the SFTP server sends data to the SFTP Client, the encoding of filename is changed from UTF-8 to GB18030; when the SFTP server receives the data sent from the SFTP Client, it first determines whether the filename is GB18030 encoding, and if so, it is converted to UTF-8.
