### ISSUE TITLE
sftp server FileSystem interface support

### ISSUE THREAD

**Issue by leffss** [pkg/sftp#347]
Is there a filesystem interface design like `github.com/taruti/sftpd` ? If there is, it will be more perfect.

**Comment by eikenb** [comment]
Hey @leffss, thanks for the input.

When designing the Request server interface I specifically avoided modeling a virtual filesystem, at the original authors prompting, instead going with more of an event based system. I'm pretty happy with the result. If you look back at my early PRs you can dig up the discussions about this.

I'm looking to extend the Request server to fully cover the operations needed for a full filesystem backed SFTP server (like the older server.go implementation). I think adding support for a few more optional interfaces is going to be the way to go. Where you can implement one or more of them and the server will assert for the interface and use it if present. The idea is to keep the required interfaces down to the minimum useful set while allowing a more full featured server.

Thanks for the pointer to github.com/taruti/sftpd, I hadn't seen that project and it is interesting to read through an alternative approach.
