### ISSUE TITLE
sftp server could not support symlink

### ISSUE THREAD

**Issue by leffss** [pkg/sftp#348]
i use the stfp server example [sftp-server](https://github.com/pkg/sftp/tree/master/examples/go-sftp-server), i found it did not support symlink, the sftp client is srt, os is windows 7

![1585709066(1)](https://user-images.githubusercontent.com/49055524/78093893-c7904200-7405-11ea-8a58-0e30483d68d9.png)

**Comment by drakkan** [comment]
Hi, I did a quick test (on Linux) and it works for me, on windows you need Administrator Privileges to create symbolic links.

Please try to be more detailed when asking questions, for example describing the steps required to replicate the issue or providing a small test program that reproduce the issue. A screenshot with a symlink is not so clear, at least for me. Thanks

**Comment by leffss** [comment]
> Hi, I did a quick test (on Linux) and it works for me, on windows you need Administrator Privileges to create symbolic links.
> 
> Please try to be more detailed when asking questions, for example describing the steps required to replicate the issue or providing a small test program that reproduce the issue. A screenshot with a symlink is not so clear, at least for me. Thanks

I am sorry, i just test in windows 7. Now i test in linux, it work, thinks!
