### ISSUE TITLE
how to change sftp directories?

### ISSUE THREAD

**Issue by gevuong** [pkg/sftp#350]
hello,

I am trying to change sftp directories before uploading files to a z/OS MVS dataset. On the CLI, I normally change directories with the following command: `cd //ABC.DEFG`, then `put <filename>`. The two forward slashes are used to identify a MVS top level qualifier. 

Recently, I figured out that I can run `ls`-specific cli commands (ie. ` ls /+mode=text`) by passing `/+mode=text` into the `ReadDir` method because apparently, I think the binary structure of the content that gets sent to the sftp server is recognized as executing an `ls` command on the server-side. There are no change directory methods so I'm wondering if there's a way I can do something similar with changing the directory (ie. `cd`)?

I tried passing in the full path (ie. `//ABC.DEFG`) to methods such as `Walk()`, `Open()`, `Create()`, `ReadDir()`. I then run `Getwd()` but the current working directory remains unchanged.

The sftp server I'm using is the Co:Z SFTP dovetailed technologies
http://dovetail.com/docs/sftp/sftp-doc.pdf

**Comment by puellanivis** [comment]
SFTP itself does not have a concept of a “workingdir” everything works through absolute paths.

This library presents this level of abstraction, and does not build this CLI-style of concept with workingdirs, etc.

**Comment by eikenb** [comment]
Hey @gevuong, thanks for the interest.

As puellanivis pointed out the server/protocol has no concept of a working directory. In practice the interactive clients mimic this behavior. This library doesn't do that but you could pretty easily add it on top.

Did you have any other followup questions?

**Comment by gevuong** [comment]
ic ok. no other follow up questions. thanks for your help.
