### ISSUE TITLE
failed to send packet: EOF

### ISSUE THREAD

**Issue by tech-geek29** [pkg/sftp#357]
I cannot paste the code as it is for the organization I am working in and is confidential. But yes I am getting this error while I try to Upload File on SFTP server. The file size is 22 KB. Even for download file I am getting same error. Not sure what is the issue.

**Comment by drakkan** [comment]
Hi,

we don't want to see your full code :) a small reproducer is enough. If you want to get help you need to provide a way to reproduce your issue, thanks

**Comment by tech-geek29** [comment]
Below is the reproducer code:

// SFTPConnectionInterface is the interface for SFTP SFTPConnection
type SFTPConnectionInterface interface {
	// ConnectWithPassword function will get an sftp conenction using a password
	// Returns client ssh SFTPconnection handler and error object if fails
	ConnectWithPassword(sftpDetails model.SFTPDetails, hostKeyCallback ssh.HostKeyCallback) (SFTPOperationsInterface, error)
}

// SFTPConnection the implementation for SFTPConnectionInterface
type SFTPConnection struct{}

// ConnectWithPassword function will get an sftp conenction using a password
// Returns client ssh SFTPconnection handler and error object if fails
func (conn *SFTPConnection) ConnectWithPassword(sftpDetails model.SFTPDetails, hostKeyCallback ssh.HostKeyCallback) (SFTPOperationsInterface, error) {
	// Create SFTP server URL
	var url strings.Builder
	url.WriteString(sftpDetails.Hostname)
	url.WriteString(":")
	url.WriteString(sftpDetails.Port)
	timeout, _ := strconv.Atoi(sftpDetails.Timeout)
	// Client configurations for SFTP SFTPconnection
	config := getSSHClientConfig(sftpDetails.Username, sftpDetails.Password, timeout, hostKeyCallback)
	// Dial to the SFTP server
	client, err := ssh.Dial("tcp", url.String(), config)
	if err != nil {
		return nil, fmt.Errorf("failed to dial: %v", err)
	}
	var SFTPconnection SFTPOperationsInterface = &SFTPOperations{SSHClient: client}
	return SFTPconnection, nil
}

func getSSHClientConfig(username, password string, timeout int, hostKeyCallback ssh.HostKeyCallback) *ssh.ClientConfig {
	// Client configurations for SFTP SFTPconnection
	config := &ssh.ClientConfig{
		User:            username,
		HostKeyCallback: hostKeyCallback,
		Timeout:         time.Duration(timeout) * time.Second,
		Auth: []ssh.AuthMethod{
			ssh.Password(password),
		},
	}
	return config
}

// SFTPOperations the sftp SFTPconnection implementation struct
type SFTPOperations struct {
	SSHClient  *ssh.Client
	SFTPClient *sftp.Client
}

// CreateSFTPClient creates an SFTP Client which will be used for SFTP operations
func (sftpOperations *SFTPOperations) CreateSFTPClient() error {
	// Establish SFTP SFTPConnection
	sftpClient, err := sftp.NewClient(sftpOperations.SSHClient, sftp.MaxPacketUnchecked(262119))
	if err != nil {
		log.Error(context.Background(), err)
		return fmt.Errorf("failed to create sftp client: %v", err)
	}
	sftpOperations.SFTPClient = sftpClient
	return nil
}

// CloseSSHClient Closes the SSH Session
func (sftpOperations *SFTPOperations) CloseSSHClient() error {
	err := sftpOperations.SSHClient.Close()
	if err != nil {
		return err
	}
	return nil
}

// CloseSFTPClient Closes the SFTP Session
func (sftpOperations *SFTPOperations) CloseSFTPClient() error {
	err := sftpOperations.SFTPClient.Close()
	if err != nil {
		return err
	}
	log.Info(context.Background(), "Connection successfully closed")
	return nil
}

**Comment by tech-geek29** [comment]
Below is the code:

`
func ConnectWithPassword(host, username, password string) (*SFTPConnection, error) {

	//Check Port if not passed with host
	if strings.Contains(host, ":") == false {
		host = host + ":22"
	}

	config := &ssh.ClientConfig{
		User:            username,
		HostKeyCallback: nil,
		Auth: []ssh.AuthMethod{
			ssh.Password(password),
		},
	}

	// Dial to the FTP server
	client, err := ssh.Dial("tcp", host, config)
	if err != nil {
		return nil, fmt.Errorf("Failed to dial: %v", err)
	}

	// Establish SFTP Connection
	sftp, err := sftp.NewClient(client)
	if err != nil {
		return nil, fmt.Errorf("Failed to create ftp session: %v", err)
	}

	sftpConnection := &SFTPConnection{}
	sftpConnection.SftpClient = sftp
	sftpConnection.IsVerbose = false

	return sftpConnection, nil
}

// Close : Close the SFTP Session
func (sftpConnection *SFTPConnection) Close() error {
	err := sftpConnection.SftpClient.Close()
	if err != nil {
		fmt.Println(err)
		return err
	}
	sftpConnection.logMsg("Closed SFTP Connection")
	return nil
}

// UploadFile : Copy source file to target
func (sftpConnection *SFTPConnection) UploadFile(sourcePath, targetPath string) error {

	sftpClient := sftpConnection.SftpClient

	targetFile, err := sftpClient.Create(targetPath)
	if err != nil {
		return err
	}

	// Open the source file
	srcFile, err := sftpClient.Open(sourcePath)
	if err != nil {
		return err
	}
	defer srcFile.Close()

	srcFile.WriteTo(targetFile)

	return nil
}


func invoker(){
        sftpConnection, err := sftphelper.ConnectWithPassword(host, username, password)
	if (err != nil){
		panic(err)
	}
	defer sftpConnection.Close()
        sftpConnection.UploadFile(filepath,<source filepath>)
	if (err != nil){
		fmt.Println(err)
	}
}

`

**Comment by tech-geek29** [comment]
I tried to create a long-lived SFTP cpnnection on long-lived SSH connection but after few days I start getting failed to send packet: EOF error. This may be because remote SFTP closes the connection. What should I do then?

**Comment by drakkan** [comment]
> I tried to create a long-lived SFTP cpnnection on long-lived SSH connection but after few days I start getting failed to send packet: EOF error. This may be because remote SFTP closes the connection. What should I do then?

Maybe you can re-create the client connection on errors

**Comment by tech-geek29** [comment]
> > I tried to create a long-lived SFTP cpnnection on long-lived SSH connection but after few days I start getting failed to send packet: EOF error. This may be because remote SFTP closes the connection. What should I do then?
> 
> Maybe you can re-create the client connection on errors

I even tried that but within the time it reconnects some of the requests fails. I do not want that to happen in production code.

**Comment by puellanivis** [comment]
Before using a connection check that it is still there with a `Getwd`, if that fails, then you need to redail. Redialing should be done under an exclusive lock, to ensure that you do not stampede a server with multiple threads all trying to redial all at the same time.

So, one thread will be reconnecting, and all the other threads will be waiting on the lock until the reconnection is complete, and then once the reconnect is done, they can then get the same client and continue working.

**Comment by tech-geek29** [comment]
Thanks @puellanivis. The solution suggested by you works. Youe explaination was really helpful. Appreciate a lot.

Also thanks to @drakkan I guess you also gave the same suggestion which I misunderstood (Silly me!)

**Comment by puellanivis** [comment]
Happy to hear that this solves your issue. Shall you close the issue, or should we?

**Comment by tech-geek29** [comment]
> Happy to hear that this solves your issue. Shall you close the issue, or should we?

Thanks again. I am closing the issue.
