### ISSUE TITLE
multiple SFTP clients on single ssh client results in "ssh: rejected: administratively prohibited (open failed)"

### ISSUE THREAD

**Issue by tech-geek29** [pkg/sftp#359]
Hi, when I try to create multiple SFTP clients on single ssh client, it results in "ssh: rejected: administratively prohibited (open failed)"

**Comment by drakkan** [comment]
Hi,

I guess this is a server side restrictions, 

anyway without some code we can only guess. Can you please write a small reproducer? Thanks

**Comment by puellanivis** [comment]
This is unrelated to this project, and your remote ssh server is refusing to allow you to run more than one SFTP session per ssh connection.

The solution is, if you need to build more than one SFTP connection to a client to build a completely new SSH connection.

However, if you just want to perform multiple SFTP operations without reconnecting, then just use a long-lived SFTP connection over a long-lived SSH connection.

**Comment by tech-geek29** [comment]
@puellanivis I tried to create a long-lived SFTP cpnnection on long-lived SSH connection but after few days I start getting failed to send packet: EOF error. This may be because remote SFTP closes the connection. What should I do then?

**Comment by tech-geek29** [comment]
> This is unrelated to this project, and your remote ssh server is refusing to allow you to run more than one SFTP session per ssh connection.
> 
> The solution is, if you need to build more than one SFTP connection to a client to build a completely new SSH connection.
> 
> However, if you just want to perform multiple SFTP operations without reconnecting, then just use a long-lived SFTP connection over a long-lived SSH connection.

@puellanivis I tried to create a long-lived SFTP cpnnection on long-lived SSH connection but after few days I start getting failed to send packet: EOF error. This may be because remote SFTP closes the connection. What should I do then?

**Comment by puellanivis** [comment]
When I was writing a long-lived service that had to access SFTP from time to time, I used the [sftp.Client.Wait()](https://pkg.go.dev/github.com/pkg/sftp?tab=doc#Client.Wait) call to detect disconnects, and also just before using a Client, I used the [sftp.Client.Getwd](https://pkg.go.dev/github.com/pkg/sftp?tab=doc#Client.Getwd) as a sort of “ping” to test if the connection were still open and valid.

With every disconnect, shutdown the `ssh.Dial` as well, and every reconnect started over again from the `ssh.Dial`.
