### ISSUE TITLE
ubuntu 18.04 crash

### ISSUE THREAD

**Issue by wYtMNaPx-dotcom** [pkg/sftp#395]
ubuntu 18.04 always crashes if i use this to send file to it. how can i do with this crash...?

**Comment by davecheney** [comment]
Thank you for raising this issue. Can you please provide some details. What did you try? What happened when you tried? How can someone else try to reproduce what happened?

**Comment by wYtMNaPx-dotcom** [comment]
Thank you for answering, ive tried on Ubuntu 18.04.1 Server , Ubuntu 18.04.5 Server ,  Ubuntu 18.04.1 Live Server,  these OS always crash when i'm testing,  but it works on Ubuntu 16.04 and CentOS, so i think maybe its some problems on Ubuntu, so I also used winscp to test, there was no crashes yet. 

OS: VMWare Machine Ubuntu 18.04.1, Ubuntu 18.04.5

go code for test : 

func GetRemotePath(localHome string,remoteHome string, localPath string) string{
	return strings.ReplaceAll(remoteHome + localPath[len(localHome):],"\\","/")
}

func UploadDir(c *ssh.Client) error{

	sfc,err := sftp.NewClient(c)
	if err != nil{
		return err
	}
	defer sfc.Close()

	localHome := `D:\testDir`
	remoteHome := "/home/test"

	err = filepath.Walk(localHome,
		func(path string, info os.FileInfo, err error) error {
			if info.IsDir(){

				remoteDir := GetRemotePath(localHome,remoteHome,path)

				if err := sfc.MkdirAll(remoteDir); err != nil{
					panic(err)
				}

			}else{

				remotePath := GetRemotePath(localHome,remoteHome,path)

				dest, err:= sfc.Create(remotePath)
				if err != nil{
					panic(err)
				}
				defer dest.Close()
				src, err := os.Open(path)
				if err != nil{
					panic(err)
				}
				defer src.Close()

				if _,err := io.Copy(dest,src);
				err != nil{
					panic(err)
				}

			}
			return nil
		},
	)

	return err
}

func TestSSHKeyboard(t *testing.T){

	knownFile := `D:\gocodes\go_ssh_test\knownFile`

	var answers = keyboardInteractive(map[string]string{
		"Password: ": "123456",
	})

	config := &ssh.ClientConfig{
		User: "root",
		Auth: []ssh.AuthMethod{

			ssh.KeyboardInteractive(answers.Challenge),
			ssh.Password("123456"),
		},
		HostKeyCallback:func(host string, remote net.Addr, key ssh.PublicKey) error {


			hostFound, err := goph.CheckKnownHost(host, remote, key, knownFile)

			if hostFound && err != nil {

				return err
			}

			if hostFound && err == nil {

				return nil
			}

			return goph.AddKnownHost(host, remote, key, knownFile)
		},
	}

	c,err := ssh.Dial("tcp4","192.168.0.29:22",config)

	if err != nil{
		log.Fatal(err)
	}

	UploadDir(c)

}

**Comment by davecheney** [comment]
You mention that this program crashes. What did you see when you ran this program?

**Comment by wYtMNaPx-dotcom** [comment]
> You mention that this program crashes. What did you see when you ran this program?

Sorry for indeterminate statment.
I means when i ran the test code  to send files to Ubuntu 18.04, the Ubuntu 18.04 crashed, while my testing work normally to send files to any other OS on my vmware. In fact i've configured three Ubuntu 18.04 vmware virtual machine, and the three virtual machine both crashed.

**Comment by drakkan** [comment]
Can you please provide a fully runnable program (something we can execute using `go run` for example) and report the expected output and the actual one?

Thank you for your patience

**Comment by wYtMNaPx-dotcom** [comment]
Thanks for helping.
[sshupload.zip](https://github.com/pkg/sftp/files/5559714/sshupload.zip)
Here is the code, just go run with args
![image](https://user-images.githubusercontent.com/74637713/99525894-70ab9d00-29d5-11eb-8916-bff1229a87c0.png)

**Comment by puellanivis** [comment]
What do you mean by “the OS crashed”? As in a kernel panic?

**Comment by wYtMNaPx-dotcom** [comment]
> What do you mean by “the OS crashed”? As in a kernel panic?

 The Ubuntu 18.04 just being like "paused" while i'm using the code to upload files and i can't do any operation unless reboot.

**Comment by drakkan** [comment]
Hi,

I tested your example with minor modifications and it works for me.

Here is the ouput:

```
go run sshupload.go -local /tmp/aa -host 192.168.1.101:2022 -user nicola -password password
2020/11/18 12:54:56 mkdir: /tmp/sshupload
2020/11/18 12:54:56 sending file content to: /tmp/sshupload/main.go
```

remote side is Ubuntu 18.04 (arm64 and not amd64 but this should make no difference).

Here is the modified code used in my test

[sshupload.zip](https://github.com/pkg/sftp/files/5559823/sshupload.zip)

are you able to upload a file to your ubuntu 18.04 vm using another sftp client? For example `sftp` cli?

**Comment by drakkan** [comment]
This option

```
sftp.MaxPacketUnchecked(1)
```

will make uploading large files really slow, I suggest setting a higher value, with this setting you send packet with only 1 byte of data

**Comment by wYtMNaPx-dotcom** [comment]
> Hi,
> 
> I tested your example with minor modifications and it works for me.
> 
> Here is the ouput:
> 
> ```
> go run sshupload.go -local /tmp/aa -host 192.168.1.101:2022 -user nicola -password password
> 2020/11/18 12:54:56 mkdir: /tmp/sshupload
> 2020/11/18 12:54:56 sending file content to: /tmp/sshupload/main.go
> ```
> 
> remote side is Ubuntu 18.04 (arm64 and not amd64 but this should make no difference).
> 
> Here is the modified code used in my test
> 
> [sshupload.zip](https://github.com/pkg/sftp/files/5559823/sshupload.zip)
> 
> are you able to upload a file to your ubuntu 18.04 vm using another sftp client? For example `sftp` cli?

Yes i used WinSCP and it worked, but when i run my code on my own OS (win10) then it crashes the ubuntu 18.04.
Thank you for helping, i didn't use any option at first, it didn't work so i tried to change option param.
And can you please tell me what the environment you run the code on?

**Comment by drakkan** [comment]
Hi,

I run the code on Arch Linux, but I just tested it on a Win10 VM and it works there too:

```
Z:\>go run sshupload.go -local Z:\aa -host 192.168.1.101:2022 -user nicola -password password
2020/11/18 14:15:13 mkdir: /tmp/sshupload
2020/11/18 14:15:14 sending file content to: /tmp/sshupload/main.go
2020/11/18 14:15:14 sending file content to: /tmp/sshupload/sub.mkv
```

I suggest to login via ssh to you Ubuntu VM and  monitor what happen when you transfer the file, for example using `top`. Using your original example I see a very high CPU usage until the transfer ends. Please also try to upload a folder with only one small text file as first attempt

**Comment by wYtMNaPx-dotcom** [comment]
> Hi,
> 
> I run the code on Arch Linux, but I just tested it on a Win10 VM and it works there too:
> 
> ```
> Z:\>go run sshupload.go -local Z:\aa -host 192.168.1.101:2022 -user nicola -password password
> 2020/11/18 14:15:13 mkdir: /tmp/sshupload
> 2020/11/18 14:15:14 sending file content to: /tmp/sshupload/main.go
> 2020/11/18 14:15:14 sending file content to: /tmp/sshupload/sub.mkv
> ```
> 
> I suggest to login via ssh to you Ubuntu VM and monitor what happen when you transfer the file, for example using `top`. Using your original example I see a very high CPU usage until the transfer ends. Please also try to upload a folder with only one small text file as first attempt

Sorry i've just tested on another vmware environment, it still worked, thanks for your help, maybe its my own problem. 
I have captured the tcp packets, the server always stop to reply (crash), so i think its a bug on ubuntu 18.04, now its maybe a problem on my machine, actually my original plartform is vm exsi 6.5,  i'll try to configure on another.  
Thanks a lot for your help.
