### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by greatroar** [pkg/sftp#396]
Would someone with push access please push a new release tag? There have been several features added and bugs fixed since 1.12.0. Restic could do with some of those bug fixes, and maybe the new Sync method too.

**Comment by drakkan** [comment]
Hi,

I would like the see the `more-optimization` branch merged before the next release, 

I need the `WriteAt` method to add support for an sftp based backend in SFTPGo.

However a release is not a blocker for me, I can use [my fork](https://github.com/drakkan/sftp/tree/clientWriteAt) or the `more-optimization` branch while waiting for this feature to be included in a release.

@greatroar is restic using pkg/sftp now? The last time I checked it there were some compatibility issues, see #321, but it used `sftp` CLI at that time

**Comment by greatroar** [comment]
It is, and it has been since 2014. It runs an ssh command on the other end of a pipe, but uses pkg/sftp to speak to it.

**Comment by vansante** [comment]
I concur, I would like a release with this fixed :) :

https://github.com/pkg/sftp/issues/398

**Comment by puellanivis** [comment]
I’m working on the `WriteTo` implementation, but with EOY coming up work priorities are zapping a lot of my time.

**Comment by greatroar** [comment]
@puellanivis Is pushing a release tag before doing the optimizations an option?

**Comment by puellanivis** [comment]
It’s not impossible, but I’m not so sure what the benefit of pushing a new release just to be followed a week or so later by yet another one.

But if the bugs fixed are critical enough, it’s something we could consider. But I know personally, I don’t even have the time to cut a release right now, let alone work on the optimization branch. So, this would be a case where someone else would need to cut this “stepping stone” branch.

**Comment by vansante** [comment]
Is there an update on this? Its taking a while now

**Comment by puellanivis** [comment]
Yeah, sorry. The concerns raised in the `more-optimizations` branch mean we want to rework how we call these functions, and not just default to parallel transferring without consent of the caller, as it would require additional cleanup on error cases.

Unfortunately, I’ve been incredibly busy with work and personal life matters the last few weeks, and haven’t had much time to touch them.

**Comment by puellanivis** [comment]
OK, let’s merge https://github.com/pkg/sftp/pull/410 then cut a release? 👍

**Comment by drakkan** [comment]
I just released v1.13, @puellanivis  please take a look at the changelog, thank you

**Comment by puellanivis** [comment]
Changelog looks great! 👍
