### ISSUE TITLE
method "RealPath" is needed for sftp.Client

### ISSUE THREAD

**Issue by ltmit** [pkg/sftp#399]
We can see that Client.Getwd() uses a hidden method "realpath" to make path translation.
This method is useful for many situations, but there is no other public method to provide the same functionality.
So I suggest to make the function public.

**Comment by drakkan** [comment]
I'm not very fluent on client side, @puellanivis what do you think about? Thank you

**Comment by puellanivis** [comment]
It seems like it’s a genuine request packet, and as noted could have some utility for clients. I don’t really see any reason not to expose it.

However, this comes with a caveat. I’m not sure we’re handling all the Host/Client OS situations properly. It should probably have a good and thorough check up before just exporting the functionality.

**Comment by puellanivis** [comment]
https://github.com/pkg/sftp/pull/410

**Comment by drakkan** [comment]
This is now fixed
