### ISSUE TITLE
Is there a way in RequestServer to determine the max packet size

### ISSUE THREAD

**Issue by cchantep** [pkg/sftp#409]
In RequestServer it could be useful to know the max packet size to implement custom handler (for Put operation).
For know it seems that on OSX it's `32768` but would be nicer to have a clean/portable way to determine that.

**Comment by drakkan** [comment]
Hi,

please take a look [here](https://tools.ietf.org/html/rfc4253#page-8). The pkg/sftp limit is [256KB](https://github.com/pkg/sftp/blob/master/packet.go#L22). It will refuse to accept bigger [packets](https://github.com/pkg/sftp/blob/master/packet.go#L172). So in your `WriterAt` implementation you can receive at most 256KB buffers

**Comment by cchantep** [comment]
On osx, each packet passed to `WriteAt` is at most `32768` bytes.

**Comment by drakkan** [comment]
On Linux is the same, it is the client that sets the packet size. When used as client pkg/sftp use 32768 as default too.

**Comment by cchantep** [comment]
Then it would be nice to make available the detected packet size from the current session at hook level.

**Comment by drakkan** [comment]
> Then it would be nice to make available the detected packet size from the current session at hook level.

I don't understand sorry, you already have the size for each packet. A strange client might send packets of different sizes, and the final packet will almost always have a different size.

**Comment by cchantep** [comment]
The last packet is another story but the max size of packet in current session is useful

**Comment by drakkan** [comment]
There is no concept of max packet per session, is the client that decide the packet size, this library accepts 256*1024 bytes as max packet size

**Comment by cchantep** [comment]
Apart from using the `offset / sessionMaxPacketSize` there is no way to determine the absolute order (aka index starting from 0) of the current packet a custom `WriteAt` provided by hook.
Some logic to write the received packet require that.

**Comment by puellanivis** [comment]
Every `WriteAt` will have the `offset` tracked properly by the calls to `WriteAt()`, and the packet size of the data to write tracked by `len(b)`.

I just don’t understand by what you mean by “absolute order” when… oh wait, I think I just got it. You want to be able to order the _packets_ not just the `offset`? I don’t understand why that would be necessary. And writers could write these packets in any order of sizes, they don’t always need to be the same length as the maximum packet size.

For instance, a client could write per buffered line of output, rather than waiting until it had a completely full buffer then transmitting.

I don’t think what you want is possible.

**Comment by cchantep** [comment]
The `len(b)` is the size of the current buffer, not the expected max packet size.
And yes, absolute order may be required, as where you write in `WriteAt` may require it and not support the very same offset as reference.

**Comment by drakkan** [comment]
Hi, you can convert the `WriteAt` to a sequential writer using for example [pipeat](https://github.com/eikenb/pipeat) or reordering the packet yourself based on the offset in a similar way. The server cannot limit the packet size, it can only refuse to handle too big packets, where too big is quite arbitrary

**Comment by cchantep** [comment]
The use case is not to pipe and the offset by itself is not sufficient to reorder. It only makes possible to determine whether the current offset is greater than the last processed one, not that the current one it's the next one as there is no guarantee another packet must be processed between.

**Comment by drakkan** [comment]
I don't know your use case, maybe you should better explain it. 

Anyway, the offset is enough to reorder the received packets if you accumulate them until you have no "holes". This is what pipeat does.

Another option is to set `SftpServerWorkerCount` to 1 [here](https://github.com/pkg/sftp/blob/master/server.go#L22): this way reads/writes will become sequential (and the server will become slower)

**Comment by puellanivis** [comment]
I’m sorry, but there’s just no way that the SFTP protocol will allow us to obtain the feature you are looking for. A client could send any data it wants in any particular arbitrary order, with any number of offsets and packet sizes.

We have a ton of extensive code to coördinate multiple parallel requests in `WriteTo` and `ReadFrom`. There is no way to get you an absolute order, except by, as drakkan noted, keeping track of how much has been written in total, and delaying the writing of packets until you receive a packet at `lastWrite.offset + lastWrite.length`.

The SFTP protocol itself does not provide any sequential writing/reading, it is always “WriteAt` and `ReadAt`, it is, in this way, similar to a raw file-system store, and ensuring the consistency of your data is a problem left for the client and server to negotiate.

**Comment by drakkan** [comment]
There is nothing we can do here, sorry
