### ISSUE TITLE
undefined: "github.com/pkg/errors".Is

### ISSUE THREAD

**Issue by bharathtnt** [pkg/sftp#412]
please guide us how to fix this we are getting below error 
we are using Go:1.10

github.com/pkg/sftp
../github.com/pkg/sftp/client.go:987:7: undefined: "github.com/pkg/errors".Is

**Comment by davecheney** [comment]
Sorry, the minimum supported version is Go 1.14

**Comment by bharathtnt** [comment]
Thankyou @davecheney  and @drakkan 

updating to Go 1.14 is a huge change for us 
we have multiple services which run on Go 1.10 
will discuss  internally and get Back to u if  any help needed
thanks

**Comment by puellanivis** [comment]
Updating to Go 1.14 might seem like it’s a drastic change, but because of the Go compatibility guarantees, the likelihood of that actually causing any issues is extremely low.
