### ISSUE TITLE
v1.13.1

### ISSUE THREAD

**Issue by drakkan** [pkg/sftp#442]
@puellanivis here is a draft release note for v1.13.1

New features and bugfixes.

Request Server:

- [GH-437] Add support for a start directory

Client:

- [GH-439] Export a ReadFromWithConcurrency function that permits ensuring concurrency usage
- [GH-430] Add the internal SSH filexfer module
- [GH-435] Fix math overflows on 32-bit architectures
- [GH-436] Sequentially issue read requests, fixes several data loss issues
- add fuzzer support and fix some potential crashes
- other minor improvements and bugfixes

am I missing something? Do you plan to add other features before the next release? Thank you

**Comment by puellanivis** [comment]
No, I don’t think there are plans for anything else.

**Comment by drakkan** [comment]
ok, I'll tag a new release then, thank you
