### ISSUE TITLE
RealPathFileLister

### ISSUE THREAD

**Issue by d4z3x** [pkg/sftp#448]
How do I use this interface to customize the start directory?

```
type RealPathFileLister interface {
	FileLister
	RealPath(string) string
}
```

I do see this in request-example.go:

```
// implements RealpathFileLister interface
func (fs *root) Realpath(p string) string {
	fs.startDirectory = "/test"

	if fs.startDirectory == "" || fs.startDirectory == "/" {
		return cleanPath(p)
	}
	return cleanPathWithBase(fs.startDirectory, p)
}
```

Do I implement the RealPath method and change the dir there? My apologies in advance for asking a basic question.

**Comment by drakkan** [comment]
Hi,

yes do you need to implement the RealpathFileLister interface and returns the response for the `SSH_FXP_REALPATH` request from there. This way you can implement the start directory logic.

**Comment by drakkan** [comment]
RealpathFileLister works only with smart clients, I proposed a better approach in #498
