### ISSUE TITLE
file.Close() panics when internal variable is nil

### ISSUE THREAD

**Issue by samprakos** [pkg/sftp#45]
https://github.com/pkg/sftp/blob/master/client.go#L627

If a call to SFTPServer.NewFile produces an error, a non-nil WriterCloser is still returned...and subsequent calls to Close() (like in a defer statement) causes a panic due to the internal variable c being nil.

**Comment by davecheney** [comment]
Sorry, won't fix.

if a method or function returns a non nil error, you can say nothing about the state of any of the other values, and that includes invoking methods on them.
