### ISSUE TITLE
Permission issue writing

### ISSUE THREAD

**Issue by xbassols** [pkg/sftp#454]
Hello,

I've been trying to find a permission issue that I'm having when writing via SFTP using the client. Reading is fine and writing via terminal too (using sftp and put) but when using the library I'm having a permission problem. I've tried with OpenFile trying different flags and with Create with no luck always returning permission denied as error (on the Create or OpenFile instruction).

Can you throw some light to the issue? What should I test next?

Thanks!

**Comment by puellanivis** [comment]
Do you have any error messages available?

**Comment by xbassols** [comment]
The only error I get is **permission denied** when executing

`w, err := client.Create(remoteFilePath)`
or
`client.OpenFile(remoteFilePath, os.O_WRONLY|os.O_CREATE|os.O_TRUNC)`

No other error whatsoever. It's worth noting that it does work via sftp terminal client (MacOS) and via ssh2-sftp-client on NodeJS.

Reading works just fine.

**Comment by puellanivis** [comment]
Could you copy paste the whole error from the `err.Error()`?

Also, what is the form of your `remoteFilePath`? Know that it has to be an absolute path, there is no support for a relative path.

**Comment by xbassols** [comment]
The error is only **permission denied** no matter how you print it. Even inspecting it with the debugger. And the path should be ok since I can list the folder content.

**Comment by xbassols** [comment]
Alright happy to report that I've found the issue. 

It looks like that either the naming of the file is too long (45 char) or there is some kind of glitch when using a file with a name like FILE-2006-01-02T15:04:05Z.txt on this server. I've shortened the file name to FILE-20060102150405.txt and now its writing properly.

Hopefully that helps someone in the future.
