### ISSUE TITLE
Latest commit broke the windows build

### ISSUE THREAD

**Issue by jtwatson** [pkg/sftp#47]
build on mac works nicely, but cross compile for windows and it blows up.   I also tried it on a windows box, and received similar error.  Roll back the latest PR, and all is well.

```
sftp $ go install
sftp $ env GOOS="windows" GOARCH="386" go install
# github.com/pkg/sftp
./attrs.go:134: undefined: syscall.Stat_t
./server_stubs.go:5: undefined: os in os.FileInfo
./server_stubs.go:6: undefined: path in path.Join
```

**Comment by davecheney** [comment]
Opps. Sorry about that, do you want to take a crack at fixing it ?

**Comment by marksheahan** [comment]
I'll have a look, sorry for the breakage

**Comment by marksheahan** [comment]
PR with a fix; compiling on win7 amd64, and cross compiling from mac:
https://github.com/pkg/sftp/pull/48


mark@MARK-WIN7-VM /C/Users/mark/Documents/go/src/github.com/pkg/sftp
(windows_fix)
$ go install

mark@MARK-WIN7-VM /C/Users/mark/Documents/go/src/github.com/pkg/sftp
(windows_fix)
$ uname -a
MINGW32_NT-6.1 MARK-WIN7-VM 1.0.12(0.46/3/2) 2012-07-05 14:56 i686 unknown


Marks-MacBook-Pro:sftp mark$ go install

Marks-MacBook-Pro:sftp mark$ env GOOS="windows" GOARCH="386" go install

Marks-MacBook-Pro:sftp mark$ env GOOS="windows" GOARCH="amd64" go install

Marks-MacBook-Pro:sftp mark$

**Comment by jtwatson** [comment]
Wow.  Quick response!  I will test the PR.

**Comment by jtwatson** [comment]
I tested the PR in my project and everything is working again.

**Comment by marksheahan** [comment]
Ok great; again sorry, I should have tested all platforms.

Dave can you review when you get a chance, and pull into master if it looks
okay?

Thanks,
Mark
