### ISSUE TITLE
ioutil.ReadAll never finishes downloading a file with disabled concurency

### ISSUE THREAD

**Issue by glebteterin** [pkg/sftp#489]
I'm connecting to a server with `sftp.UseConcurrentReads(false)`, then open a file with Client.Open and read it to memory with ioutil.ReadAll. Due to the `readAtSequential` function (client.go) suppressing io.EOF error, the ioutil.ReadAll can't know when the file is fully read and won't finish.

I'm not sure I understand the reasoning for File.Read() doesn't return io.EOF, it seems like a bug introduced during refactoring. If so, would you accept a PR that fixes it?

**Comment by puellanivis** [comment]
OOooooof… yeah, this looks like it was copied from `writeToSequential` which has an entirely different semantic here. We definitely shouldn’t be swallowing the `io.EOF` for `readAtSequential`.

I’ll be happy to accept a PR. 👍

**Comment by puellanivis** [comment]
Fixed in https://github.com/pkg/sftp/pull/490
