### ISSUE TITLE
How can i get link count field by this library 

### ISSUE THREAD

**Issue by kexirong** [pkg/sftp#495]
### How can i get link count field 
same of standard library `syscall.Stat_t.Nlink`
### the openssh rfc screenshot 
[www.openssh.com/txt/draft-ietf-secsh-filexfer-02.txt](http://www.openssh.com/txt/draft-ietf-secsh-filexfer-02.txt)
![RO~ P_JQUQN`IM8G9%ML`~B](https://user-images.githubusercontent.com/31177595/155266477-baa88e6c-f1a6-4391-8751-3435c5f28bb5.png)
ps: my native language is not english

**Comment by puellanivis** [comment]
There is no standards compliant way to access this information.
