### ISSUE TITLE
Create file using env variables

### ISSUE THREAD

**Issue by pioz** [pkg/sftp#508]
I don't know if this is possible in some way, but what I would like to do is:
```
dstFile, err := sftp.Create("$HOME/.config/systemd/user/hello.service")
```
using the `$HOME` environment variable.

I've tried but I get the error "file does not exist", if instead I use the exploded path "/home/pioz/.config/systemd/user/hello.service" I get no errors.

**Comment by puellanivis** [comment]
Go does not do string environment-variable interpolation. In order to get this you need to expand the value yourself. So: `sftp.Create(filepath.Join(os.Getenv("HOME"), "/.config/systemd/user/hello.service"))`

**Comment by puellanivis** [comment]
Use `sftp.Client.Getwd()` to get the current working directory from the server, this should default to the user’s home directory.

**Comment by pioz** [comment]
Thanks, it works! 😗

**Comment by SwagLYY** [comment]
> Use `sftp.Client.Getwd()` to get the current working directory from the server, this should default to the user’s home directory.

why `sftp.Client.Getwd()` always reutrn the same directory ? like '/root' , which method could effect this result?
