### ISSUE TITLE
Lenience with non-compliant servers?

### ISSUE THREAD

**Issue by boomlinde** [pkg/sftp#52]
I recently used this library for a client sftp setup. Their server software (unknown to us at the moment) disregards the relevant IETF document by not including the language tag in all its status messages. For this use case, I patched `unmarshalStatus` to use `unmarshalStringSafe` when reading the language tag from the status message which works fine.

The question now is whether this project is aiming for strict compliance, or if the patch I made is relevant to the project. `sftp` from OpenSSH seems to ignore that the language tag is missing, and I found that WinSCP had patched for similar issues with broken server software (http://winscp.net/tracker/show_bug.cgi?id=770).

**Comment by davecheney** [comment]
> The question now is whether this project is aiming for strict compliance, or if the patch I made is relevant to the project.

Given that there is no spec (no really, there isn't) for sftp, and most impls just try to do what scp(1) does, I'd be happy to review any PR's you have.
