### ISSUE TITLE
Question: How does the library internally talk to the SFTP subsystem?

### ISSUE THREAD

**Issue by hbgl** [pkg/sftp#520]
Hi,
let me preface this by saying that I am not a direct user of this package and I am not even a Go developer. I stumbled upon this project because I use the backup tool [restic](https://github.com/restic/restic) which is written in Go and which does use this package. With restic you can pass it a [command as an option](https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html?highlight=sftp.command#sftp) (e.g. `-o sftp.command="foobar"`) that creates an SFTP client and then restic uses that client to send and receive data. I found that mechanism quite intricate so I wanted to know how it works, which is why I am here.

I read through the source code and here is what I gathered so far:

1. An sftp client process is created (e.g. [openssh-client](https://packages.ubuntu.com/search?keywords=openssh-client)). See [example](https://github.com/restic/restic/blob/b824d8cdcc0221ee22fcd6582716777d895fb204/internal/backend/sftp/sftp.go#L51) in restic.
2. [NewClientPipe](https://github.com/pkg/sftp/blob/cf523d99b5d2f41128caaaafc4c908a6a4d2fa0e/client.go#L201-L248) is called with the stdin and stdout pipes from the process.
3. The library then uses the stdin pipe to send [raw SFTP packets](https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-02#section-3) to the sftp client process ([see code](https://github.com/pkg/sftp/blob/cf523d99b5d2f41128caaaafc4c908a6a4d2fa0e/packet.go#L232-L259)).
4. Raw sftp responses are read from the stdout pipe ([see code](https://github.com/pkg/sftp/blob/cf523d99b5d2f41128caaaafc4c908a6a4d2fa0e/packet.go#L261-L293)).

Is this correct so far? Is there any external documentation about how to send and receive raw packages via stdin and stdout using the sftp client? I tried starting the sftp client and sending it packets via stdin but it only accepts text commands. I must be missing something here.

Thanks for reading this far and if there is a better channel to ask these sort of questions, please let me know.

**Comment by puellanivis** [comment]
Your step 1 is not entirely accurate. It does not start an `sftp` client process, it creates an `ssh` client process with the command-line argument `-s sftp` which is a raw connection to the SFTP as expected by this package, rather than the `sftp` client itself, which as you note only accepts text commands.

I’ve tested calling `ssh mycomputer -s sftp` and it does indeed open a raw SFTP pipe to the remote machine.

From point 2 onwards, you are correct.

**Comment by hbgl** [comment]
Many thanks!
