### ISSUE TITLE
we got unnecessary logging occurs

### ISSUE THREAD

**Issue by alhamsya** [pkg/sftp#527]
we got unnecessary logging occurs when there is an error. Should be isn't any print logging .zip and .txt at the log management

"Unable to update a stale item: item.save()\" (SSH_FX_FAILURE)"

![image](https://user-images.githubusercontent.com/56905970/193169445-f7f0c293-0034-4d6e-81da-0340e49529dc.png)

**Comment by puellanivis** [comment]
I don’t see how this could be caused by us: 🤔 
```
sftp$ grep --exclude="*_test.go" "[^sS][pP]rint" *.go internal/encoding/ssh/filexfer/{*.go,*/*.go}
debug.go:       log.Printf(fmt, args...)
request-example.go:     // fmt.Println(string(p), off)
server.go:              fmt.Fprintf(svr.debugStream, "sftp server file with handle %q left open: %v\n", handle, file.Name())
```
