### ISSUE TITLE
sftp client hang when exit in sftp server example

### ISSUE THREAD

**Issue by wwcd** [pkg/sftp#563]
cause this problem after fix #554，err == nil should be added

https://github.com/pkg/sftp/blob/b0487bc4a60bb90023150bd771caee04ce281723/examples/go-sftp-server/main.go#L139

**Comment by puellanivis** [comment]
Hm… I would probably rework it to:
```
if err := server.Serve(); err != nil {
	if err != io.EOF {
		log.Fatal("sftp server completed with error:", err)
	}
}
server.Close()
log.Print("sftp client exited session.")

```

**Comment by wwcd** [comment]
ok, my pleasure
