### ISSUE TITLE
TestClientRemoveDir failure on macosx 10.11.2

### ISSUE THREAD

**Issue by sykesm** [pkg/sftp#57]
When running the integration tests against macosx's OpenSSH sftp server, the `TestClientRemoveDir` test fails. The server returns an `SSH_FX_PERMISSION_DENIED` error when attempting to remove the empty directory and, since this error is not `SSH_FX_FAILURE`, the remove directory path in Client#Remove is never attempted.

It appears that `unlink` on macosx will fail with `EPERM` when attempting to delete an empty directory and the sftp server is simply propagating that up.

```
$ mkdir empty-dir; sudo dtruss -f -t unlink unlink empty-dir

unlink: cannot unlink ‘empty-dir’: Operation not permitted
	PID/THRD  SYSCALL(args) 		 = return
38284/0x6b422:  unlink("empty-dir\0", 0x7F802240387C, 0x12)		 = -1 Err#1
```

In practice this means that the `Client#Remove` can't be used to delete an empty directory on macosx as the sftp rmdir function isn't surfaced and the current implementation does not attempt a `removeDirectory` when `removeFile` fails with a permission error.

Seems like `Remove` should be attempting a `removeDirectory` when the path represents a directory regardless of the error from `removeFile`. Short of that, it may make sense to expose `RemoveDirectory` on the client.

**Comment by davecheney** [comment]
Thanks for reporting this bug. I have a fix and also fixed the integration tests to run by default on darwin.
