### ISSUE TITLE
how to handle binary and ascii file transfer to and from sftp server?

### ISSUE THREAD

**Issue by aashakabra** [pkg/sftp#573]
Hello,

I wanted to understand if there is any explicit flag that can be set while uploading or downloading the binary vs ascii file from sftp server?

How should we handle this?

Thanks in Advance!

**Comment by drakkan** [comment]
Hello,

ASCII and BINARY modes are FTP concepts. SFTP is a different protocol, there is no ASCII mode, transfers are always in BINARY mode in FTP terms
