### ISSUE TITLE
Strongly-typed accessor for FileStat

### ISSUE THREAD

**Issue by liori** [pkg/sftp#589]
For the purposes of [this PR](https://github.com/rclone/rclone/pull/7897#issuecomment-2159405969) it would be nice if sftp offered a strongly-typed accessor for the `sftp.FileStat` structure.

Would it be possible for the `fileInfoFromStat` function to return something _assignable_ to `os.FileInfo`, but also offering a method to access the `stat` field without having to convert from `interface{}`?

**Comment by puellanivis** [comment]
The `Sys()` function signature is already defined by the `os.FileInfo` interface. And there’s not really a strong reason why we would want to provide Yet Another Accessor, when type assertion works just fine to unwrap the `interface{}`.

**Comment by puellanivis** [comment]
Thinking about this a little more. It wouldn’t even be particularly useful, as one would need to type-assert from the `os.FileInfo` into an `interface{ FileStat() *sftp.FileStat }` in order to access the proposed typed return anyways.

**Comment by puellanivis** [comment]
I’m going to go ahead and close this as we have no intent to provide such a function, and even after providing such a function, a type inference would still be necessary.
