### ISSUE TITLE
Connection hangs if too many are open and close quickly

### ISSUE THREAD

**Issue by CErika** [pkg/sftp#608]
# Description
I try upload a file 5 times to a server, opening and closing the connection every time, and the 5th time the connection just hangs: sometimes it hangs on the `ssh.Dial`, sometimes on the `sftp.NewClient`. 
If  I rerun it just after closing it, the connection hangs directly on the first try instead of the 5th.
The app hangs even if there is a timeout in the ssh configuration.

## Degugging
- I have tried with 2 different servers
- I have checked the logs in the servers and no connection is visible when the app hangs
- it works to open 5 or more SFTP connection to the servers manually
- I have tried adding 1 and then 5 seconds between the sending but the same problem appears

## Software version
Local: Linux Mint 21.3, go1.22.2, OpenSSL 3.0.2
Server: Ubuntu 24.04.1, OpenSSL 3.0.13

## Step to reproduce
The below code reproduce the issue:
```go
package main

import (
	"encoding/csv"
	"fmt"
	"os"
	"time"

	"github.com/pkg/sftp"
	"golang.org/x/crypto/ssh"
	"golang.org/x/crypto/ssh/knownhosts"
)

func main() {

	key, err := os.ReadFile("sftp_key")
	if err != nil {
		fmt.Printf("error reading private key: %v", err)
		os.Exit(1)
	}

	// Create the Signer for this private key.
	signer, err := ssh.ParsePrivateKey(key)
	if err != nil {
		fmt.Printf("error parsing private key: %v", err)
		os.Exit(1)
	}

	hostKeyCallback, err := knownhosts.New("~/.ssh/known_hosts")
	if err != nil {
		fmt.Println("error reading known host")
		os.Exit(1)
	}

	sshConfig := &ssh.ClientConfig{
		User:            "fake-sender",
		HostKeyCallback: hostKeyCallback,
		Auth: []ssh.AuthMethod{
			// Use the PublicKeys method for remote authentication.
			ssh.PublicKeys(signer),
		},
		Timeout: 5 * time.Second,
	}

	data := [][]string{
		{"Name", "Surname", "Age"},
		{"John", "Clerk", "6"},
		{"John", "Clark", "9"},
		{"John", "Clark", "9"},
		{"John", "Clark", "9"},
		{"John", "Clark", "9"},
		{"John", "Clark", "9"},
	}
	for i := 0; i < 5; i++ {
		if err := send("sftp-address:port", data, sshConfig); err != nil {
			fmt.Printf("error sending data: %v", err)
			os.Exit(2)
		}
	}

	fmt.Println("sending successful")

}

func send(addr string, data [][]string, sshConfig *ssh.ClientConfig) error {
	fmt.Println("sending data")
	conn, err := ssh.Dial("tcp", addr, sshConfig)
	if err != nil {
		return fmt.Errorf("dial: %v", err)
	}
	defer func() {
		if err := conn.Close(); err != nil {
			fmt.Printf("conn close: %v", err)
		}
	}()

	fmt.Println("connection open")

	client, err := sftp.NewClient(conn)
	if err != nil {
		return fmt.Errorf("sft new client: %v", err)
	}
	defer func() {
		if err := client.Close(); err != nil {
			fmt.Printf("client close: %v", err)
		}
	}()
	fmt.Println("sftp client open")

	sftpFilename := fmt.Sprintf("file_%d.csv", time.Now().UnixMicro())
	file, err := client.OpenFile(sftpFilename, os.O_CREATE|os.O_RDWR)
	if err != nil {
		return err
	}
	defer file.Close()

	fmt.Println("file opened")

	writer := csv.NewWriter(file)
	if err = writer.WriteAll(data); err != nil {
		return err
	}
	fmt.Println("file written")

	return nil
}
```

**Comment by puellanivis** [comment]
I’ve used your reproduction code, but it does not lock up for me.

However, that it can happen during the `ssh.Dial` indicates something entirely outside of the control of sftp is going on here.

**Comment by puellanivis** [comment]
I’ve run it even with `for range 1000` and no hangs… I tested going to localhost, and also another machine on my local area network… both no hangs.

**Comment by CErika** [comment]
Thank you to have checked!
At least now I know it is something on how the SSH is configured either in my server or on my computer :)
