### ISSUE TITLE
Make it possible to open ssh session in NewClient with envs

### ISSUE THREAD

**Issue by raydent** [pkg/sftp#610]
Hi! We have a use case to use ssh.Session's Setenv method within NewClient call. 

Currently session init looks like this: 

```go
func NewClient(conn *ssh.Client, opts ...ClientOption) (*Client, error) {
	s, err := conn.NewSession()
	if err != nil {
		return nil, err
	}
	// ! Here we would like to be able to call s.Setenv()
	if err := s.RequestSubsystem("sftp"); err != nil {
		return nil, err
	}
	pw, err := s.StdinPipe()
	if err != nil {
		return nil, err
	}
	pr, err := s.StdoutPipe()
	if err != nil {
		return nil, err
	}

	return NewClientPipe(pr, pw, opts...)
}
```

We wanted to make a patch, however current NewClient signature does not seem to fit such changes well. So, we have a few possible solutions:
1) Create a new option.  Currently opts are not used in NewClient and are just passed directly to NewClientPipe, where client init happens. Possible solution here - split client init into separate function 
```go
// initClient returns Client with no underlying connection
func initClient(opts ...ClientOption) (*Client, error) {
	sftp := &Client{
		clientConn: clientConn{
			conn: conn{
				Reader:      nil,
				WriteCloser: nil,
			},
			inflight: make(map[uint32]chan<- result),
			closed:   make(chan struct{}),
		},

		ext: make(map[string]string),

		maxPacket:             1 << 15,
		maxConcurrentRequests: 64,
	}

	for _, opt := range opts {
		if err := opt(sftp); err != nil {
			return nil, err
		}
	}
	return sftp, nil
}
```
Then, use it both in NewClientPipe and NewClient. NewClient body will look like this: 
```go
// NewClient creates a new SFTP client on conn, using zero or more option
// functions.
func NewClient(conn *ssh.Client, opts ...ClientOption) (*Client, error) {
	s, err := conn.NewSession()
	if err != nil {
		return nil, err
	}
	c, err := initClient(opts...)
	if err != nil {
		return nil, err
	}
	for name, value := range c.envs {
		s.Setenv(name, value)
	}
	if err := s.RequestSubsystem("sftp"); err != nil {
		return nil, err
	}
	pw, err := s.StdinPipe()
	if err != nil {
		return nil, err
	}
	pr, err := s.StdoutPipe()
	if err != nil {
		return nil, err
	}

	return NewClientPipe(pr, pw, opts...)
}
```
Looks like a better solution, however, two times client creation both in NewClient and in NewClientPipe might be confusing.

2) Create a separate function with signature like 
```go
func NewClientWithEnv(conn *ssh.Client, envs map[string]string, opts ...ClientOption) (*Client, error) {
```
Seems worse, as there might be more changes to session init required in future, as well as having two slightly different functions does not seems like a good idea.

If you accept such functionality changes, could you please suggest solution you see the best one (or maybe the third option)?

**Comment by puellanivis** [comment]
Hm… I’m not sure if the `sftp` package is even the right place for this sort of thing. It would probably be better to just have a function that accepts a `*ssh.Session` and then does the sftp-specific setup. So, if one needs to do anything on the session, they can just do that directly, before passing it in to build the sftp client on top of it. I’m kind of hesitant to add `sftp` package options into how an `ssh` package type is manipulated.

I’m curious though why you would need to set any env vars on the server, because the sftp syntax doesn’t allow for dereferencing any env vars? (I’m asking to genuinely better understand your use case, because I don’t at all know about what you could want to accomplish with this feature.)

**Comment by raydent** [comment]
After revisiting function signatures I understood that we (and anyone who has similar demands) can just configure his own session and use NewClientPipe with it. I will drop the issue, because such reuse seems like a best solution. Sorry for disturbance.

About the use case - we have ssh proxy that creates tunnel based on passed envs. It also allows to use sftp, however, underlying ssh session needs envs for tunnel configuration.
