### ISSUE TITLE
(*Client).Stat and (*Client).Open don't return os.ErrNotExist for nonexistent paths

### ISSUE THREAD

**Issue by LMMilewski** [pkg/sftp#71]
Running the following test:

    go test --integration

    func TestNonexistentPath(t *testing.T) {
            sftp, cmd := testClient(t, READONLY, NO_DELAY)
            defer cmd.Wait()
            defer sftp.Close()
    
            if _, err := sftp.Stat("/doesnt/exist/"); !os.IsNotExist(err) {
                    t.Errorf("os.IsNotExist(%v) = false, want true", err)
            }
    
            if _, err := sftp.Open("/doesnt/exist/"); !os.IsNotExist(err) {
                    t.Errorf("os.IsNotExist(%v) = false, want true", err)
            }
    }

Results in 

    --- FAIL: TestNonexistentPath (0.01s)
            client_integration_test.go:171: os.IsNotExist(sftp: "No such file" (SSH_FX_NO_SUCH_FILE)) = false, want true
            client_integration_test.go:175: os.IsNotExist(sftp: "No such file" (SSH_FX_NO_SUCH_FILE)) = false, want true
    process_write: write failed
    FAIL
    exit status 1
    FAIL        github.com/pkg/sftp     2.149s

**Comment by davecheney** [comment]
Yes, that is a bug. Do you want to send a PR, or I can have a look in a few
days.

**Comment by LMMilewski** [comment]
Looks like mdlayher@ took care of this already. Thank you!
