### ISSUE TITLE
Proposal: remove all named and naked returns

### ISSUE THREAD

**Issue by mdlayher** [pkg/sftp#76]
Named returns can be useful for documentation purposes, but are often unneeded.  Naked returns go hand-in-hand with named returns, and in my personal experience, only lead to confusing code.

I propose removing every named and naked return from this repository, with a few exceptions:

1) interface declarations, e.g.
```go
type Filesystem interface {
    Open(path string) (info *os.FileInfo, err error)
}
```

2) functions which return several values of the same type, hypothetical example:
```go
func Stat(path string) (freeSpace uint64, usedSpace uint64, totalSpace uint64, err error) { }
```

3) capturing panic recovery value into an error (haven't seen this at all in this repository, but it's occasionally useful)

Thoughts?

**Comment by davecheney** [comment]
1. sgtm

2. if a funciton returns so many values of the same type they are confusing, it's a good argument for returning a structure containing those values instead.

3. yeah, i've used that in the past, feels like a lot of magic. it would have to pay for itself several times over to account of its oddness.

**Comment by mdlayher** [comment]
Regarding 2, totally agreed, it was just hypothetical.  I would personally always use a `struct` in that situation.

Will start a PR either tonight or tomorrow to fix this.
