### ISSUE TITLE
No mechanism exists to provide a `start_directory` for an sftp server instance

### ISSUE THREAD

**Issue by sykesm** [pkg/sftp#82]
I have a golang ssh daemon that includes the sftp server. When an sftp subsystem request comes in, an instance of the sftp server is created, wired to the session, and started. The sftp server runs in the same OS process as the ssh daemon so it inherits the working directory of the daemon. Since the sftp server is running in the working directory of the daemon, the initial working directory of sftp clients becomes the working directory of the daemon.

For user experience reasons (not for security or isolation reasons), when a user initiates an sftp session with the server, I would like the client to start in a "remote working directory" that is different from the working directory of the ssh daemon.

---

The openssh sftp server implementation has a `start_directory` option that can be specified on launch. When specified, a client of the server will be placed in the `start_directory` as their initial working directory.

For example, using the following script as my sftp-server wrapper:

``` sh
#!/bin/sh

exec /usr/libexec/sftp-server $SFTP_SERVER_ARGS
```

I can change the starting directory that clients see:

```
$ export SFTP_SERVER_ARGS="-d /usr"; echo pwd | sftp -D $PWD/sftp-wrapper -b-
sftp> pwd
Remote working directory: /usr

$ export SFTP_SERVER_ARGS="-d /"; echo pwd | sftp -D $PWD/sftp-wrapper -b-
sftp> pwd
Remote working directory: /

$ export SFTP_SERVER_ARGS="-d /etc"; echo pwd | sftp -D $PWD/sftp-wrapper -b-
sftp> pwd
Remote working directory: /private/etc
```

The client observes the initial working directory by sending a `realpath "."` to the server:

```
$ export SFTP_SERVER_ARGS="-d /etc"; echo pwd | sftp -vvv -D $PWD/sftp-wrapper -b-
debug2: Remote version: 3
...
debug3: Sent message fd 3 T:16 I:1
debug3: SSH_FXP_REALPATH . -> /private/etc size 0
sftp> pwd
Remote working directory: /private/etc
```

A similar mechanism would be useful for pkg/sftp's server. Ideally the `start_directory` could be specified as a server option with the following characteristics:
1. The start directory does not rely on the OS level current working directory of the sftp process.
2. Client operations can rely on relative paths being treated as relative to the starting directory and not the OS current working directory of the process.

**Comment by tv42** [comment]
This is something I would like to have, too. The code change doesn't look too bad, basically add a simple `path.Join` filter in front of places where the path from network is used.

This filter could also be used to provide another, semi-related feature: restrict the session to a subtree (without OS-level `chroot`). Thanks to the stdlib path manipulation library, that's only couple of lines of code.
