### ISSUE TITLE
File.Read work incorrectly

### ISSUE THREAD

**Issue by dos65** [pkg/sftp#83]
Hi, i trying to read file by sftp and it does not work. 
On small files `Read` returns `io.EOF`, on large not full file content.
[Here code example](https://gist.github.com/dos65/a02d6632b6e5259b0aa8)

**Comment by davecheney** [comment]
I don't think this is a bug in the sftp package. Your code is not following
the contract for io.Reader. Specifically a call to io.Reader.Read may
return n bytes of data and an error. This is an exception to the usual rule
where you check the error then other values, in the case of Read, handle n
bytes of data (n is guaranteed to be a valid value in spite of an error),
then investigate the error.

**Comment by dos65** [comment]
Yes - you right about currently sftp behavior.
It exactly return `n > 0` and `io.EOF` , but `os.File.Read` return err on second call after reach EOF.

**Comment by davecheney** [comment]
> It exactly return n > 0 and io.EOF , but os.File.Read return err on second call after reach EOF.

This sounds like the documented behaviour. Is that what you expected? If not, what did you expect?

**Comment by dos65** [comment]
https://golang.org/pkg/os/#File.Read
> EOF is signaled by a zero count with err set to io.EOF

According to the documentation it can return n > 0 and err, but not in EOF case.
Sftp has similar description for `Read`.

I expect behavior like `os` package, but i don't mind to just document that.

**Comment by davecheney** [comment]
That's the os.File.Read method. I'm talking about the io.Reader contract.

**Comment by dos65** [comment]
Ok, sorry, now got it.
I have been confused by README, where written about `os`.
I think it should be changed - https://github.com/pkg/sftp/blob/master/client.go#L730-L731

**Comment by davecheney** [comment]
Ok. Thanks. I think I understand the issue now.

Either sftp.Conn.Read does not obey the documented behaviour, or the
documentation is wrong -- it's likely that we'll change the latter.

As a workaround, I suggest you adopt this logic

b := make([]byte, ...)
n, err := NNN.Read()
b = b[:n]
// hand b
// inspect err

This logic will work for all implementations of io.Reader.
