### ISSUE TITLE
Provide a net/http-like API for the Server type

### ISSUE THREAD

**Issue by mdlayher** [pkg/sftp#84]
This will be an issue to track progress for providing a `net/http`-like API for the Server type.

TODO list:
- [ ] create `sftp.Handler` interface
  - https://golang.org/pkg/net/http/#Handler
- [ ] create `sftp.Request` type with request information
  - https://golang.org/pkg/net/http/#Request
- [ ] create `sftp.Responder` interface to respond to clients
  - https://golang.org/pkg/net/http/#ResponseWriter
  - name is tentative, suggestions appreciated
- [ ] create `sftp.FileServer` type which can serve files from the local filesystem, as is done now.
  - enables generic interface backend for fronting many different "filesystems" with SFTP
  - could also implement `chroot`-like functionality this way
- [ ] figure out how to cleanly integrate underlying SSH server configuration
  - retrieve information like SSH username

Ideas:
- [ ] add `sftp.ServeMux` type for using different handlers for different requests, e.g. create, open, read, write: https://golang.org/pkg/net/http/#ServeMux

Here's a couple sketches of what this might look like from previous samples:

``` go
type Handler struct {}

func (h *Handler) ServeSFTP(w sftp.Responder, r *sftp.Request) {
    log.Println("request:", r.Type)
    _, _ = sftp.PermissionDenied(w)
}

func main() {
    s := &sftp.Server{
        Handler: &Handler{},
    }

    _ = s.Serve()
}
```

``` go
func ServeSFTP(w sftp.Responder, r *sftp.Request) {
    if !authenticated(r) {
        sftp.FileServer(sftp.Dir("/srv/sftpchroot/"))(w, r)
        return
    }

    sftp.FileServer(sftp.Dir("/"))(w, r)
}
```

cc: @davecheney @marksheahan @xor-gate @PunKeel

**Comment by PunKeel** [comment]
I don't understand how this would work. (http is stateless, SFTP is not. I think there should be a shared "session" object, at least ... But I don't see how to name it/what it could hold)

**Comment by eikenb** [comment]
@PunKeel - The SFTP server implements version 3 of the spec which allows for stateless servers (other versions may as well).  For how this works read the intro to section 6 in the RFC.

https://tools.ietf.org/html/draft-ietf-secsh-filexfer-02#section-6

**Comment by eikenb** [comment]
#130 isn't exactly this, but I think it covers some of the same ground. What do you think?

**Comment by eikenb** [comment]
I'm going to say this is done enough as #130 addresses most of it and what it doesn't aren't as useful in the context of SFTP.
