### ISSUE TITLE
Versioning would be wise

### ISSUE THREAD

**Issue by xor-gate** [pkg/sftp#86]
Hi guys,

Probably it would be wise to have some kind of versioning (branches/tags). I recently wrote a extension of the Afero filesystem (https://github.com/spf13/afero/issues/59) project and it seemed it broken exactly 6 days ago after preparing for the new architecture. Probably it could be wise to have some versioning like this: http://labix.org/gopkg.in. The gopkg.in service may be used as a tag/branch to url which is go-gettable, people may use or not use this service but can also rely on the tags/branches itself so stuff wont break as development goes forward.

Then people can still use the tag/branch which includes hotfixes and dont have to vendor the sftp source into their own repo.

Let me know what you think.

**Comment by davecheney** [comment]
I'm happy to tag a release of this package.

**Comment by xor-gate** [comment]
Maybe the best way is to branch from a point where everything "is stable" into `v1` and then when some fixes (no api changes) need to be done they can be cherrypicked or patched in the branch? As a extra feature this `v1` branch can have tags like `v1.0.0`, v1.0.1`, etcetera. Ala semver.org. Then when `v2` is ready we could branch from master and then tag as appropriate.

**Comment by davecheney** [comment]
I don't think this package is 1.0 ready, but I'll tag a version soon.

**Comment by xor-gate** [comment]
A `v0` branch/tag could also be made. As people are using the sftp package in "production" already (the "old" api).

**Comment by davecheney** [comment]
I'm sorry about the breakage, I'll tag a version soon.

**Comment by xor-gate** [comment]
No problem, there are multiple ways to fix things. But most people who currently use sftp without vendorizing will scratch their heads. It would be wise to mention in the README how we will handle versioning in the future (semantic versioning, tags, branches) so developers will be less annoyed :-). And people then can use the http://gopkg.in service to directly include it in their go projects.

**Comment by davecheney** [comment]
@xor-gate yes, I understand this, I'm not happy about the lack of support for versioning in the go tooling either.

**Comment by xor-gate** [comment]
We hope for the best in the future, the nice thing with the tooling is you will not be enforced to have some style but it would be nice to have something standarized (`godep`, `gopkg.in` and others feel a bit like a hack). But for the upcoming time it would be wise to mention the development flow in the readme (or docs) of the package itself. 

Thanks for your understanding :+1:

**Comment by joeblew99** [comment]
If this is stable can it be released for now ?

**Comment by davecheney** [comment]
I'm not ready to tag a release yet. I'm sorry but I have no date when I
expect to be ready.

**Comment by joeblew99** [comment]
ok. I have a use case where i need to only pull data from a sftp server. Any idea if this functionality works currently ?

**Comment by eikenb** [comment]
For those who care, once all the current major issues have been ironed out I plan on tagging an initial version. Not sure if I'll call it 1.0, but at least it will be a known state you can pin your code to.

**Comment by davecheney** [comment]
sgtm.

**Comment by fd0** [comment]
What's the state of a release tag here? For [restic](https://github.com/restic/restic), we'll switch to `dep` shortly, and it would be very helpful if you could tag a release. Thanks!

**Comment by eikenb** [comment]
I'll look into doing it this next week. The bug reports have calmed down and there are currently no outstanding bugs that I haven't addressed in some way.

FYI does anyone care about the versioning scheme? SemVer seems the best default for this sort of project, so I'll probably just go with that.

**Comment by fd0** [comment]
Please use semantic versioning, that's what the upcoming [`dep`](https://github.com/golang/dep) prefers. Thanks!

**Comment by xor-gate** [comment]
Semver would be a good choice, as most people know it in opensource projects.

**Comment by eikenb** [comment]
Semver it shall be... in  a few more days. I want to nail down my revised code for the file-listing in the request based server (#184) as it will break backwards compatibility. Once I have that merged I'll tag the version.

**Comment by fd0** [comment]
Awesome!

**Comment by eikenb** [comment]
Sorry for the delays. I am going to tag a version soon. Just another influx of tickets makes me want to review them to be sure.

**Comment by eikenb** [comment]
I keep putting this off in expectation of a breaking API bug... but I need to get over it and just do it. So this is it.
I tagged the current head 1.0.0 (semantic versioning) and things are now versioned.

**Comment by xor-gate** [comment]
When the API compat gets broken you just bump the major version, no problem at all. Great you tagged the first release. Congrats :+). Now people who are going to use tooling can just refer to this one without breaking stuff by pulling master.
