### ISSUE TITLE
Retrieve owner/group as per v03+ spec?

### ISSUE THREAD

**Issue by eldondevcg** [pkg/sftp#87]
We are currently using this package with providers who do not offer meaningful GID's/UID's, but instead offer owners and groups via the v03+ protocol drafts. It would be really nice to be able to fetch those extended attributes. Has adding that functionality to this package been investigated?

**Comment by eikenb** [comment]
My goal for this project is to implement version 3 of the protocol as published in draft 02 of the RFC, the same supported by OpenSSH.
