### ISSUE TITLE
blowfish requested by sftp server.

### ISSUE THREAD

**Issue by joeblew99** [pkg/sftp#91]
I am having issues connecting with this type of SFTP server:
http://docs.ipswitch.com/WS_FTP_Server71/ReleaseNotes/index.htm?k_id=ipswitch_com_ftp_documents_worldwide_ws_ftpserverv71releasenotes

I can connect with filezilla fine with settings:
Protocol: "SFTP - SSH File Transfer Protocol"
Logon Type: "Normal"
Username: ***
Password: ***

SO i am using this method call:

```
sshcfg := &ssh.ClientConfig{
        User: user,
        Auth: []ssh.AuthMethod{
            ssh.Password(password),
        },
    }

```

When i hit: func (c *connection) clientAuthenticate(config *ClientConfig) error {

I get back err:

```

ssh: handshake failed: ssh: no common algorithm for client to server cipher; client offered: [aes128-ctr aes192-ctr aes256-ctr aes128-gcm@openssh.com arcfour256 arcfour128], server offered: [3des-cbc blowfish-cbc aes256-cbc aes128-cbc cast128-cbc]


```

SO looking at : https://github.com/golang/crypto/blob/master/ssh/cipher.go#L95
It looks like its not implemented yet ?

**Comment by davecheney** [comment]
The Go ssh package does not support CBC mode ciphers as a policy because
they are insecure. The sftp package uses the ssh package but does not
control the ciphers that are used.

https://github.com/golang/go/issues/13385

**Comment by joeblew99** [comment]
Ok thanks. That was my understanding too.

I noticed there is a blowfish implementation on github.
Is there an easy way to use it ? I read in the source that I can use a
config file to hint to use it.
But not sure ?

**Comment by eikenb** [comment]
The ssh config file allows you to select which cipher is supports you want to use by setting a list of strings to the names of the ciphers. It doesn't (AFAIK) let you plug in arbitrary ciphers. You'd probably need to patch that in.
